<?php
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); $misc_obj->generateToken();
$authUserNamespace = new Zend_Session_Namespace("Aranca_Auth"); 
?>
<html>
<head>
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/crud.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/jquery-1.4.2.min.js"></script>
<script src="<?php echo BASEPATH;?>/js/jquery.alerts.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASEPATH;?>/css/jquery.alerts.css" />
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/jquery.ui.core.js"></script>
<link rel="stylesheet" type="text/css" src="<?php echo BASEPATH;?>/js/ckeditor/content.css"></link>
<link type="text/css" rel="stylesheet" media="all" href="<?php echo BASEPATH;?>/css/jquery.ui.theme1.css">
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/jquery.ui.datepicker1.js"></script>




<script type="text/javascript">


	window.onload = function()
	{
		document.getElementById("save").onclick = function()
		{				
			//alert('java');
			saveForm('<?php echo BASEPATH; ?>/employee/add','addemployee_form','addemployee_form');
		}
	}
	function set_value(getvalue){
		document.getElementById('radiosexval').value = getvalue;
	}
	function set_value1(getvalue){
		document.getElementById('radiomaritalval').value = getvalue;
	}
</script>
<style>
.mandatory{
	color:red;
}
.dividerline{
	background-color: #CECECE;
    float: left;
    height: 1px;
    line-height: 1px;
    margin-bottom: 10px;
    width: 99%;
}
textarea
{
	width:495px;
	max-width:495px;
}
</style>
</head>
<body>
<div id="dynamic_content" align="center">
<?php $empresult = $this->result;?>
<?php $empresult1 = $this->result1;?>

<?php $empresult2 = $this->result2;?>
<?php $empresult3 = $this->result3;?>



<form  action="" id="addemployee_form" name="addemployee_form" method="post" enctype="multipart/form-data">
	<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
	<div class="set_header_width_school" align="left" style="width:730px;">
	<div>
				<div class="set_row_div_width">
					<div class="header_row_merchant"><span class="mendatory">*</span>UserName</div>
					<div class="header_row_merchant">
						<input type="text" name="usernametxt" value="<?php if(isset($empresult->username) && $empresult->username !=""){ echo $empresult->username;}?>" id="usernametxt" errortag="UserName" maxlength="50"/>
						<span style="padding-left:5px;color:#bcbcbc;"></span>
						<div class="message" id="usernametxt_error">&nbsp;</div>
					</div>
				</div>
	</div>

	<div class="clear_fix">&nbsp;</div>
	<div>
				<div class="set_row_div_width">
					<div class="header_row_merchant"><span class="mendatory">*</span>Password</div>
					<div class="header_row_merchant">
						<input type="password" name="passwordtxt" value="<?php if(isset($empresult->password) && $empresult->password !=""){ echo $empresult->password ;}?>"  id="passwordtxt" errortag="Password" maxlength="50"/>
						<span style="padding-left:5px;color:#bcbcbc;"></span>
						<div class="message" id="passwordtxt_error">&nbsp;</div>
					</div>
				</div>
				
	<div class="clear_fix">&nbsp;</div>
				
				<div class="set_row_div_width">
					<div class="header_row_merchant"><span class="mendatory">*</span>Employee ID</div>
					<div class="header_row_merchant">
						<input type="text" name="employee_idtxt" value="<?php if(isset($empresult->employee_id) && $empresult->employee_id !=""){ echo $empresult->employee_id ;}?>" <?php if(isset($empresult->employee_id) && $empresult->employee_id !=""){?>readonly<?php }?>  id="employee_idtxt" errortag="Employee ID" maxlength="50"/>
						<span style="padding-left:5px;color:#bcbcbc;"></span>
						<div class="message" id="employee_idtxt_error">&nbsp;</div>
					</div>
				</div>
	</div>
	<div class="clear_fix">&nbsp;</div>
	<div>
				<div class="set_row_div_width">
					<div class="header_row_merchant"><span class="mendatory">*</span>First Name</div>
					<div class="header_row_merchant">
						<input type="text" name="firstname" value="<?php if(isset($empresult->firstname) && $empresult->firstname !=""){ echo $empresult->firstname;}?>" id="firstname" maxlength="10" errortag="First Name" />
						<span style="padding-left:5px;color:#bcbcbc;"></span>
						<div class="message" id="firstname_error">&nbsp;</div>
					</div>
				</div>
	<div class="clear_fix">&nbsp;</div>			
				
				<div class="set_row_div_width">
					<div class="header_row_merchant"><span class="mendatory">*</span>Last Name</div>
					<div class="header_row_merchant">
						<input type="text" name="lastname" value="<?php if(isset($empresult->lastname) && $empresult->lastname !=""){ echo $empresult->lastname;}?>" id="lastname" errortag="Last Name" />
						<div class="message" id="lastname_error">&nbsp;</div>
					</div>
				</div>
	</div>
	
	<div class="clear_fix">&nbsp;</div>
	<div>
				<div class="set_row_div_width">
					<div class="header_row_merchant"><span class="mendatory">*</span>Designation</div>
					<div class="header_row_merchant">
						<select class="select" id="designationid" name="designationid" style="width:145px;" errortag="Designation ID">
							<option value="">--Select--</option>
	       	  	  			<?php	foreach ($this->userdata2 as $userauth2){?>
							<option  <?php if(isset($empresult->designation_id)) {if($userauth2->id == $empresult->designation_id) {?> selected="selected" <?php }} ?> value="<?php  if(isset($userauth2->id) && $userauth2->id !=""){ echo $userauth2->id;}?>"><?php echo $userauth2->value;?></option>
							<?php } ?>
						</select>
<!--						<input type="text" name="cname" value="" id="cname" errortag="Creator Name" maxlength="23"/>-->
						<div class="message" id="designationid_error">&nbsp;</div>
					</div>
				</div>
				
	</div>
	<div class="clear_fix">&nbsp;</div>
	<div>
				<div class="set_row_div_width">
					<div class="header_row_merchant"><span class="mendatory">*</span>Practice</div>
					<div class="header_row_merchant">
						<select class="select" id="practiceid" name="practiceid" style="width:145px;" errortag="Practice ID">
							<option value="">--Select--</option>
	       	  	  			<?php	foreach ($this->userdata1 as $userauth1){?>
							<option <?php if(isset($empresult->practice_id)){if($userauth1->id == $empresult->practice_id){?> selected="selected" <?php }}?>value="<?php if(isset($userauth1->id) && $userauth1->id !=""){ echo $userauth1->id;}?>"><?php echo $userauth1->value;?></option>
							<?php } ?>
						</select>
<!--						<input type="text" name="cname" value="" id="cname" errortag="Creator Name" maxlength="23"/>-->
						<div class="message" id="practiceid_error">&nbsp;</div>
					</div>
				</div>
				
	</div>
	<div class="clear_fix">&nbsp;</div>
	<div>
				<div class="set_row_div_width">
					<div class="header_row_merchant"><span class="mendatory">*</span>Role</div>
					<div class="header_row_merchant">
						<select class="select" id="roleid" name="roleid" style="width:145px;" errortag="Role ID">
							<option value="">--Select--</option>
	       	  	  			<?php	foreach ($this->userdata as $userauth){?>
							<option <?php  if(isset($empresult->role_id)){if($userauth->id == $empresult->role_id && isset($empresult->role_id)) {?> selected="selected" <?php }}?> value="<?php  if(isset($userauth1->id) && $userauth1->id !=""){ echo $userauth->id;}?>"><?php echo $userauth->value;?></option>
							<?php } ?>
						</select>
<!--						<input type="text" name="cname" value="" id="cname" errortag="Creator Name" maxlength="23"/>-->
						<div class="message" id="roleid_error">&nbsp;</div>
					</div>
				</div>
			
	</div>
	<div class="clear_fix">&nbsp;</div>
	<div align="center">
				<div>
					<input type="button" class="stdButton" value="Submit" name="save" id="save" />&nbsp;&nbsp;
					<input type="button" class="stdButton" name="cancel" id="cancel" onclick="window.location.href='<?php echo BASEPATH; ?>/employee/index'" value="Cancel">
					<input type="hidden" id="idforupdate" name="idforupdate" value="<?php if(isset($empresult->id) && $empresult->id !=""){ echo $empresult->id;}?>">	
				</div>
			</div>
			<br/>
	
</form>

</div>
</body>
</html>
