<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>
 <div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12">
                    <h1 class="page-header gain-bit-Titletxt"></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
           
              <ol class="breadcrumb">
                  <li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a> > </li>
                  <li>Withdrawals</li>
  
            </ol>
         


      

     
<div class="clearfix">&nbsp;</div>

        <div class="col-lg-12 ">
            <div class="clearfix lightgraybg">

                <div class="bs-example table-responsive" data-example-id="bordered-table"> 

             
                                       <table id="data-table-simple"  class="table table-bordered innertbl display" cellspacing="0">
                     <thead>
                    <tr>
                       <th class="sortdesc">SR. NO </th>
                        <th class="sortboth">USERNAME</th> 
                        <th class="sortboth">AMOUNT</th>
                        <th class="sortboth">paymentTxId</th>
                         <th class="sortboth">ADDRESS</th> 
                         <th class="sortboth">TYPE</th> 
                          <th class="sortboth">TIMESTAMP</th>
                           <th class="sortboth">STATUS</th>
                           <th class="sortboth">CHANGE STATUS</th>
						    <th class="sortboth">ACTION</th>
                         
                     </tr> 
                 </thead>
                  <tbody> 
                  <?php $j=1;
                  foreach($this->result as $result1){?>
                    <tr>
					<td scope="row"><?php echo $j; ?></td> 
                     <td scope="row"><?php echo $result1['username'];?></td> 
                     <td><?php echo($result1["chosen_coin"]=="BTC")?$result1["btc_amt"]:$result1["alt_amt"];?></td>
                      <td><?php echo $result1['paymentTxId'];?></td> 
                      <td><?php echo $result1['wallet_addr'];?></td> 
                      <td><?php echo $result1['withdrawal_type'];?></td> 
                       <td><?php echo "".date("D jS M, y", strtotime($result1['timestamp']));?> </td>
                      <td><?php  $withdrawal_status = $result1['status'];
                                                    if($withdrawal_status==0){
                                                        echo "Inactive";
													}else{
                                                        echo "Active";
													}?>
					</td> 
                      <td><div class="button">
                      <a class="confirmation" onclick="changeWithdrawalStatus(<?php echo $result1['id']; ?>,<?php echo isset($withdrawal_status)? $withdrawal_status:""; ?>)"  href="#">
                                                         <?php 
                                                    	 
														$withdrawal_status = $result1['status'];
														if($withdrawal_status==0){?>
														 <label><?php echo "Activate"; ?></label>	
														<?php }else{?>
														</a>
														
                                                       <label><?php echo "Inactive"; ?></label>
													
														<?php }?>
														
                                                         
                                                </div>   
                        
                        
                          </td>
                             <td><?php  if($withdrawal_status==0){?>
                                                <a href="#" onclick="return deleteGeNWithdraw('<?php echo $result1['id'];?>')">Delete</a>	
                                                <?php } ?>
                           </td>
                  </tr> 

                

                  

               
             
             
             <?php $j++;}?>
                 </tbody>
                  </table> 
              </div>

        </div>

    </div>

       
        
      
    </div>
         

      

       

       

       

            <!-- /.row -->
            
            <!-- /.row -->
        </div>
  <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">      
        <!-- /#page-wrapper -->

    </div>
    
    <!-- Script for this page -->
    <script  data-cfasync='false' type="text/javascript">
			$(window).load(function() {
				var oTable1 = $('#widraw').dataTable();				
			});
			$('.confirmation').on('click', function () {
        return confirm('Are you sure?');
    });
    
    function deleteGeNWithdraw(witdrawId)
    {
        var x=confirm('Are You sure want to delete');
        if(x)
        {
            $.ajax({
                        type: 'POST',
                        url: "<?php echo BASEPATH; ?>/Pendwithdrawals/deletestatus" ,
                        data:{'withId':witdrawId},
                        success: function (response) {
                //           alert(data);return false;
							var data = JSON.parse(response);
                           if(data['success']!="")
                           {
								alert("deleted successfully");
                                location.reload();
                           }
                           else{
                               //alert("An error occured please try again later!");
							    alert(data['failure']);
                               location.reload();
                               
                           }
                }
            });
        }
    }
			
		</script>
<script>
			function changeWithdrawalStatus(id,status)
			{
                            var x=confirm('It will Active/Inactive data as well');
                            if(x)
                            {
				$.ajax({
                      type: 'POST',
                      url: "<?php echo BASEPATH; ?>/Pendwithdrawals/changewithdrawalstatus" ,
				  data:"withdrawalId="+id+"&status_value="+status,
                  success: function (response) {
                   var data = JSON.parse(response);
				   if(data['success']!="")
				   {
						//alert("Updated successfully");                                   
						 window.location ="<?php echo BASEPATH;?>/Pendwithdrawals";
				   }
                   else{
                       alert(data['failure']);return false;
                       window.location ="<?php echo BASEPATH;?>/Pendwithdrawals";
                   }
                   
                }

               
               
            	});
			}
		}
</script>