<?php
$misc_obj = new Gbc_Model_Custom_Miscellaneous();
$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); $misc_obj->generateToken();
?>
<style>
.innertbl th.sortboth {
	background: rgba(0, 0, 0, 0) url("../images/sort_both.png") no-repeat
		scroll 100% 10px;
}

.innertbl th.sortdesc {
	background: rgba(0, 0, 0, 0) url("../images/sort_desc.png") no-repeat
		scroll 100% 6px;
}

.clearfix {
	margin-top: -7px;
}
</style>
<script>
$(window).load(function() {
	var oTable1 = $('#data-table-simple-1').dataTable();	
                    
});

</script>
<div id="innerpage-wrapper">
<div class="row lightgraybg">
<div class="col-lg-12 offset-1">
<h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
</div>
<!-- /.col-lg-12 --></div>
<!-- /.row -->
<div class="row">
<ol class="breadcrumb">
	<li class="active">Home</li>
	<li></li>

</ol>
</div>

<div class="clearfix">

<div class="col-lg-12">
	<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
	<div class="clearfix">&nbsp;</div>
</div>

<div class="clearfix">&nbsp;</div>

<?php if(!empty($authUserNamespace->msg) && $authUserNamespace->msg!='' && $authUserNamespace->user!='admin')
{
	?>
	<div class=""><label for="" class="lblTxt"
	style="color: red; padding: 0 14px 12px;"><?php echo $authUserNamespace->msg;  
	?> 
	<?php $authUserNamespace->msg = ''; ?></label></div>
	<?php } ?>
	<div class="col-lg-12 ">
	<div class="clearfix lightgraybg">
	
	<?php if(!empty($this->result) && sizeof($this->result)>0) { ?>
		<div class="panel-heading faqtitlebg text-center  text-uppercase Title">Monthly Business Details</div>
		<div class="bs-example table-responsive" data-example-id="bordered-table">

		<table id="data-table-simple"
			class="table table-bordered innertbl display" cellspacing="0">
			<thead>
				<tr>
					<th class="sortdesc">Sr. No.</th>
					<th class="sortboth">Total Sales Amount</th>
					<th class="sortboth">Sales</th>
					<th class="sortboth">Users</th>
					<th class="sortboth">Date</th>
				</tr>
			</thead>
			<tbody>
		
				<tr>
				<?php
				
					for($i=0;$i<sizeof($this->result);$i++) { ?>
					<td scope="row"><?php echo $i+1; ?></td>
					<td scope="row"><?php echo $this->result[$i]["total_sales"]; ?></td>
					<td><?php echo $this->result[$i]["sales"]; ?></td>
					<td><?php echo $this->result[$i]["countusers"]; ?></td>
					<td><?php echo $this->result[$i]["date"]; ?></td>
		
				</tr>
		
				<?php }	?>
			</tbody>
		</table>
		<div class="clearfix">&nbsp;</div>
		</div>
				<?php } ?></div>

		</div>

<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="clearfix">&nbsp;</div>
<div class="col-lg-12 ">
<div class="clearfix lightgraybg">
<div class="clearfix lightgraybg">
<?php if(!empty($this->today) && sizeof($this->today)>0) { ?>
	<div class="panel-heading faqtitlebg text-center  text-uppercase Title">
		Today's Contracts Details</div>
	<div class="bs-example table-responsive"
	data-example-id="bordered-table">
		<table id="data-table-simple-1"
	class="table table-bordered innertbl display" cellspacing="0">
			<thead>
				<tr>
					<th class="sortdesc">Sr. No.</th>
					<th class="sortboth">Invoice Id</th>
					<th class="sortboth">User Name</th>
					<th class="sortboth">Amount</th>
					<th class="sortboth">Created</th>
				</tr>
			</thead>
			<tbody>
		
				<tr>
				<?php for($i=0;$i<sizeof($this->today);$i++) { ?>
					<td scope="row"><?php echo $i+1; ?></td>
					<td scope="row"><?php echo $this->today[$i]["invoice_id"]; ?></td>
					<td><?php echo $this->today[$i]["username"]; ?></td>
					<td><?php echo $this->today[$i]["amtPaid"]; ?></td>
					<td><?php echo $this->today[$i]["created_on"]; ?></td>
		
				</tr>
		
				<?php } ?>
		
			</tbody>
		</table>
		<div class="clearfix">&nbsp;</div>
		<div class="clearfix">&nbsp;</div>
		<div class="clearfix">&nbsp;</div>
	</div>
		<?php } ?>
</div>

</div>
</div>
</div>
</div>
