<?php 
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); $misc_obj->generateToken();
?>
    <div id="innerpage-wrapper">
    <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
      <div class="row lightgraybg">
        <div class="col-lg-12 offset-1">
          <h1 class="page-header gain-bit-Titletxt innpercontentPad">Buy/ Sell Bitcoins</h1>
        </div>
        <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->
      <div class="row">
        <ol class="breadcrumb">
          <li><a href="<?php echo BASEPATH; ?>/Dashboard">Dashboard ></a></li>
          <li class="active">Buy/ Sell Bitcoins</li>
        </ol>
        <div class="buy-sell-container">
          <p>Easily buy bitcoin with INR from any online banking or through NEFT/RTGS/IMPS. Selling bitcoin is just as easy, you will receive INR directly into your bank account. All banks that have IFSC are currently supported.</p>
          <div class="btn_container"><a href=""><input type="button" class="btn_" value="CLICK HERE" onclick="newtabfun()"></a></div>
        </div>
      </div>
    </div>
    
    <script>
    function newtabfun(){
    window.open('https://thebitex.com/');
    }
    </script>