<?php
$unique = rand(1111, 9999);
$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
$common_obj = new Gbc_Model_Custom_CommonFunc();
$flag = $common_obj->cleanQueryParameter($_REQUEST['flag']);
?>

<script data-cfasync='false'>
    function ValidationEvent(event) {
		//        $('#preloader2').show();
        var kit_no = $('#kit_number').val();

        var con_type = $('#contract_type1').val();
        var total_amount = $('#total_amount1').val();
     
        var kt_type = $('#kt_type').val();
        if(!(con_type) && !(kit_no) && !(total_amount)){
			$("#err_purch").css("display", "block");
            document.getElementById("err_purch").innerHTML = '';
            document.getElementById("err_purch").innerHTML = "There is some error, please try again.";
            event.preventDefault();
            return false;
		}
        else {
            //alert("herefdfhfgh");
            var token = $('#token1').val();
            $.ajax({
                type: "POST",
                url: '<?php echo BASEPATH; ?>/Checkleg/checkkit',
                data: {'kit_number': kit_no, 'kit_type': con_type, 'total_amount': total_amount, 'token': token},
//                async: false,
                beforeSend: function () {
                    $("#preloader2").show();
                },
                complete: function () {

                },
                success: function (res) {  
					//alert(res->value);return false;
					
                    $("#preloader2").hide();
                    if (res === 'false') {
                        $("#err_purch").css("display", "block");
                        document.getElementById("err_purch").innerHTML = "This kit is not available or already used, pls try with another kit";
                        //$('#err_purch').empty();
                    } else if (res == 2) {
                        $("#err_purch").css("display", "block");
                        document.getElementById("err_purch").innerHTML = "Contract type is not the same as the kit";
                    }
                    else {
						if(res != "true"){
							$("#err_purch").css("display", "block");
							document.getElementById("err_purch").innerHTML = res;
						}else{
							token = $('#token1').val();
							$("#preloader2").show();
							$.ajax({
								type: "POST",
								url: '<?php echo BASEPATH; ?>/Purchasecontract/purchasekit2',
								data: 'buy_now=' + $('#buy_now').val() + '&contract_type=' + $('#contract_type1').val() + '&hiddencontractId=' + $('#hiddencontractId').val() + '&kit_number=' + $('#kit_number').val() + '&total_amount=' + $('#total_amount1').val() + '&type=' + $('#type').val() + '&kt_type=' + kt_type + '&token=' + token,
								dataType: "json",
					//             async: false,
								beforeSend: function () {
									$("#preloader2").show();
								},
								complete: function () {

								},
								success: function (res) {
									$("#preloader2").hide();

                                if (res.success == 'success') {
                                    if (res.tran_flag != 0) {
                                        $("#buycontract").css("display", "none");
                                        $("#select_kit").css("display", "none");
                                        $("#payment_details").css("display", "none");
                                        $("#contractlist").css("display", "none");
                                        $("#contractlist1").css("display", "none");
                                        $("#confirmation").css("display", "block");
                                        $("#confirmid").css("display", "block");
                                        $('#kitselectid').removeClass('active');
                                        $('#buycontractid').removeClass('active');
                                        $('#confirmid').addClass('active');
                                        $('#confirmationPartial').css("display", "none");

                                    }
                                    else {
                                        $("#buycontract").css("display", "none");
                                        $("#select_kit").css("display", "none");
                                        $("#payment_details").css("display", "none");
                                        $("#contractlist").css("display", "none");
                                        $("#contractlist1").css("display", "none");
                                        $("#confirmation").css("display", "none");
                                        $("#confirmid").css("display", "none");
                                        $('#confirmationPartial').css("display", "block");
                                        $('#kitselectid').removeClass('active');
                                        $('#buycontractid').removeClass('active');
                                        $('#confirmid').addClass('active');
                                        $('#amntpaid').empty();
                                        $('#amntpaid').append(res.kitprice);
                                        $('#amntdue').empty();
                                        $('#amntdue').append(res.amount);

										}

									}
									else if (res.failure != '') {
										$("#err_purch").css("display", "block");
										document.getElementById("err_purch").innerHTML = res.failure;

									}
									else {
										$("#err_purch").css("display", "block");
										document.getElementById("err_purch").innerHTML = "This kit is not available or already used, pls try with another kit!!";

									}
								}
							});
						}

                    }
                }
            });
        }
//        $('#preloader2').hide();
        return false;

    }

</script>

<style>
    #menu, #sample .footer, #sample p, .breadcrumb > li + li:before {
        display: none;
    }
	
	#bg_img{
		padding:0;
	}

    li a:hover, a li:focus {
        background: transparent;
        color: #364a5e;
    }

    .req-table {
        margin-bottom: 20px;
        width: 100%;
    }

    .req-admin .modal-body {
        background: none repeat scroll 0 0 #e6e7e8;
    }

    .req-admin .modal-header {
        color: #fff;
        font: 20px "robotobold";
    }

    .req-table > tbody > tr > td, .req-table > thead > tr > th {
        font-family: "robotobold";
        font-size: 16px;
        padding: 5px 0;
        text-align: center;
        text-transform: uppercase;
    }

    .req-table > tbody > tr > td {
        font-family: "robotoregular";
        text-transform: none;
    }

    .search-con input {
        border: medium none;
        border-radius: 0;
        margin-bottom: 10px;
    }

    .req-btn, .req-btn:hover {
        background: none repeat scroll 0 0 #34495e;
        color: #fff;
    }

    .sizecls {
        display: inline-block;
        float: left;
        margin-right: 3%;
        text-align: left;
        width: 45%;
    }

    .col-lg-2 {
        width: 9.667%;
    }

    textarea {
        resize: none;
    }

	
	
    #ship_addr {
        display: none;
    }
	
	input[type="radio"]:checked+label {
	  background-color: #60b761;
	}

	.c-con{
		background: #fff;
		text-align: center;
		padding: 10px;	
	}
	
	.panel-body{
		background: #f0f3f4;
		text-align:center;
	}
	
	
    .form-group {
        text-align: left;
    }

    textarea.form-control {
        height: 34px;
    }

    .col-xs-3, .col-xs-9, .col-xs-6 {
        padding: 0 5px !important;
    }

    .shippingadd {
        float: left;
        width: 100%;

    }

    @media (min-width: 768px) and (max-width: 870px) {
        .form-group {
            width: 100%;
        }
    }

    @media (max-width: 570px) {
        .form-group {
            width: 100%;
        }
    }
    
    
	/*
	.waitingForConnection {
	  animation: blinker .2s cubic-bezier(.5, 0, 1, 1) infinite alternate;  
	}
	@keyframes blinker { to { opacity: 0; } }
	*/
	.blink{
		  font-size: 22px;
	  	  background: -webkit-linear-gradient(#00F, #F33);
	  	-webkit-background-clip: text;
	  	-webkit-text-fill-color: transparent;
		}
	
		 .blink_me {
		  animation: blinker .5s linear infinite;
		}

		@keyframes blinker {  
		  50% { opacity: 0.6; }
		}

	.gradient{  
		font-size: 16px;
		background: -webkit-linear-gradient(#ff0000, #ffff00);
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
	
	}
    .btn-float{
        float:left;
        margin-left:10px;
    }
    
    @media (max-width:480px){
     .btn-float{
        float:none;
    }   
    
    }
</style>
<input type="hidden" value="<?php echo $authUserNamespace->token; ?>" id="token1" name="token1">

<div class="content">
	<!-- Page-Title -->
	<div class="page-title-group">
		<h4 class="page-title">Contracts</h4>
		<h5 class="text-muted page-title-alt">Buy Contract</h5>
	</div>
	<div class="cb-page-content">
		<div class="container">
			<div class="row" style = "text-align: center; margin: 10px;">
				<a href = "https://etherscan.io/ether-mining-calculator" target = "_blank">
				<img src="<?php echo BASEPATH; ?>/images/eth_calc.jpg">
				</a>
			</div>
			
			<div class="row">
				<div class="col-md-12">
					<div class="card-box">
						<div class="card-box-content form-compoenent">
							<div class="clearfix"></div>
							<br>
							<div class="row"> 
								<div class="col-lg-12"> 
									<div class="panel-group" id="accordion-test-2"> 
										<div class="panel  panel-primary "> 
											<div class="panel-heading"> 
												<h4 class="panel-title"> 
													<a data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseOne-2" onclick="show('select_kit');" aria-expanded="true" class="collapsed">
													   Select Kit Type
													</a> 
												</h4> 
											</div> 
											<div id="collapseOne-2" class="panel-collapse collapse in" aria-expanded="true" > 
												<div id = "select_kit">
													<div style="font-weight:bold; text-align: center;padding:10px 0;"><?php echo $daterange; ?></div>
													<form action="<?php echo BASEPATH; ?>/Invoice" method="post" id="kit_form">
														<input type="hidden" name="unique" value="<?php echo $unique; ?>">
														<input type="hidden" value="<?php echo $authUserNamespace->token; ?>" name="token">
														<div class="panel-body">
														<?php if (!empty($flag) && $flag != 'hw') { ?>
															<div class="con-container">
															<?php
																$i = 0;

																foreach ($this->sha_contract as $getCotracts) {
																	$AvailableKits = $getCotracts['available_limit'];
																	$ExpiryDate = date("Y-m-d h:i:s", strtotime($amaze_q_max_date));
																	$currentDateTime = date("Y-m-d h:i:s");
																	$contractArray = array(11, 10, 9, 8);
																	$type = "ROI";
																	
																		if ($getCotracts['max_limit'] > 0 && $AvailableKits <= 0) {
																			$disabled = 1;
																		} else {
																			$disabled = 0;
																		}
																	
																	
																	//	if($getCotracts['total_price'] <=  15){
																			 if ($i % 3 == 0) {

																?>
																<div class="con-content">
																	<?php } ?>
																	<div class="col-lg-4" style ="padding:5px;">
																		<div class="c-con"  >
																			<h4><?php echo $getCotracts['contract_name']; ?></h4>
																			<!--
																			<span style ="display:block;"><?php echo $getCotracts['contract_qty'] ?> <?php if ($getCotracts['total_price'] <= 0.5) { ?>GHS <?php } else { ?> THS <?php } ?></span>-->
																			<span style ="display:block;"><?php
																		
																		
																		echo '<div style ="font-size:16px; height:20px;text-decoration:line-through; margin: 5px;color:red;">';
																		if($getCotracts['discount']){
																
															$totalAmount = round(($getCotracts['total_price'] - (($getCotracts['total_price'] * $getCotracts['discount']) / 100)),4);			
																		//	echo $getCotracts['total_price'].' MCAP';
																		}else{
																			$totalAmount = $getCotracts['total_price'];
																		}
																		 echo '</div>';
																
																		//echo '<div style ="font-size:16px; height:30px; margin: 5px;">'.$totalAmount.' MCAP</div>';
																		echo '<div style ="font-size:16px; height:50px; margin: 5px;">'.$getCotracts['contract_qty'].' MH/s</div>';
															?>
															</span>
																			
																			
																			
																			<div class="btn_container" style = "margin: 5px;">
																				<!--<input type="button" value="BUY NOW" class="btn_"
																											  onclick="purchase('mining<?php echo $i ?>');">-->
																				<input type="hidden" name="price" id = "price<?php echo $getCotracts['contract_id'] ?>" value="<?php echo  $totalAmount; ?>" >
																				<input <?php //echo ($getCotracts['contract_id'] == 1) ? "checked" : ""; ?>
																						type="radio" name="kit_type"
																						class="" <?php if (!empty($disabled) && $disabled == 1) {  ?> disabled <?php } ?>
																						value="<?php echo $getCotracts['contract_id'] ?>"
																						id="<?php echo $getCotracts['contract_name']; ?><?php echo $getCotracts['contract_id'] ?>"
																						onclick="$('#no_of_kits').val('');" style = "display:none;">
																			
																					<label for = "<?php echo $getCotracts['contract_name']; ?><?php echo $getCotracts['contract_id'] ?>" <?php if (!empty($disabled) && $disabled == 1) {  echo "style = 'background-color:#c1c1d2;'"; } ?> class="btn btn-inverse btn-md" >SELECT</label>
																				
																				<div style ="height:20px;padding-top: 10px;font-style:italic;text-align:left;">
																					
																					
																					<span style ="display:block;text-decoration:italics; height:20px;">
																			<?php
																		
																				if ($getCotracts['max_limit'] > 0){
																					if ($AvailableKits > 0 || $AvailableKits == 'max_limit') {
																							echo "** In stock: Available $AvailableKits Kits Only ";
																																																									} else {
																						echo "** Out of stock";
																					}
																				} 
																																				
																			?>
																			</span>
																					
																					
																			<?php
																		//	if($getCotracts['discount']){
																		//		echo	'**Available Discount '. $getCotracts['discount']."%"; 
																		//	}
																			?>
																				
																			</div>
																		</div>
																	</div>
																</div>

																	<?php if ($i == 2 || $i == 5 || $i == 8 || $i == 11 || $i == 14 || $i == (sizeof($this->sha_contract) - 1)) { 
																			 if ($i != 0) { ?>
																			<div class="clearfix"></div>
																			</div>
																<?php 
																			} 
																		} 
																		 $i++;
																	}
																?>
													

																 <div class="clearfix"></div>
																<div class="con-content" >
																	<div class="col-lg-12" style ="padding:5px;">						
																		<div class="c-con" style = "padding:30px;">
																			<div style="text-align:left;font-size:14px;font-family:robotoregular;color:red;" id="selectkits"></div>
																			<div class="col-lg-4">
																				<div class="input-type-select">
																					<select name="no_of_kits" id="no_of_kits" class = "form-control" style = "margin-top: 25px;">
																						<option value="">Select No of Kits</option>
																				<!--		<option value="1">1</option>
																						<option value="2">2</option>
																						<option value="3">3</option>
																						<option value="5">5</option>
																						<option value="15">15</option> -->
																					</select>
																				</div>
																			</div>
																			<div class="col-lg-8" style = "text-align:left;" >
																				<label for="">Referer Gainbitcoin Username</label>
																				<input type="text" value="" id="referer_user" name="referer_user" class = "form-control" style = "background:#fff;">
																				<input type="hidden" id="real_total_amount" name="real_total_amount">
																				<input type="hidden" name="buy_now" value="sha">
																			</div>
																			 <div class="col-lg-12" >
																				 <div style = "text-align:left; color:red; text-decoration:italics;padding:10px;margin-top:20px;" >
																					 <span>**Please Note:</span>
																					<ul style ="margin-left:15px;">
																						<li>
																							LIFETIME CONTRACT means till the time your hashrate is profitable. Once the mining output is less than cost, the contract will expire
																						</li>
																						<li>
																							A referral bonus of 2% MCAP goes to referring ID
																						</li>
																						<li>
																							There is No RSI & DSI paid on these contracts
																						</li>
																					</ul>
																					 <div style = "margin-top:20px;">
																						 <label style = "font-weight:normal;">
																				 <input type = "checkbox" value = "1" id = "agree" name = "agree" style = "margin: 6px 6px 0px 0; vertical-align: text-bottom;">I have Read and Agree ! </label>
																					 </div>																	 
																				 </div>
																				<div class="btn_container purchase" id = "pay_now" style ="display:none;margin-top:10px;">
																					<input type="button" value="PAY NOW" class="btn btn-inverse btn-md" id="purchase1" name="action">
																				
																			</div>		
																		
																			</div>
																			<div class="col-lg-12">

																				<div id="preloader" class=""
																					 style="width:100px;  margin: 0 auto; padding-top: 10px; width: 100px; display:none;">
																					<img src="<?php echo BASEPATH; ?>/images/ajax-loader.gif">
																				</div>

																			</div>
																			<div class="clearfix"></div>
																			<div class="clearfix"></div>
																	
															</div>
																	</div>
																</div>
															<?php
																	}
																?>	

															</div>
														</div>

													</form>

												</div>
											</div>
										</div> 
                              
                            <div class="panel  panel-primary"> 
                                <div class="panel-heading"> 
                                    <h4 class="panel-title"> 
                                        <a data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseTwo-2" class="collapsed" aria-expanded="false">
                                            Make Payment
                                        </a> 
                                    </h4> 
                                </div> 
                            
								 <div id="collapseTwo-2" > 
                                   <div id="payment_details"  style="display:none;">					
										<div class="pay-container" id="pay-container" style ="">
											<div class="pay-note">
												<div class="pay-n note" style = "margin:5px;">
													**Please Note: Kits will get active after 3 confirmations on blockchain.
												</div>

											</div>
											<div class="wait-info">
												<div class="wait-msg">Waiting for your payment<span>04m 35s</span></div>
												<div class="wait-btn"><input type="button" value="CANCEL" class="btn_ cancel-btn"></div>
											</div>
										</div>
									</div>
                                </div> 
                            </div> 
                            <div class="panel  panel-primary"> 
                                <div class="panel-heading"> 
                                    <h4 class="panel-title"> 
                                        <a data-toggle="collapse" onclick="show('list_of_contracts');" data-parent="#accordion-test-2" href="#collapseThree-2" class="collapsed" aria-expanded="false">
                                            Buy Contract
                                        </a> 
                                    </h4> 
                                </div> 
                                <div id="collapseThree-2" class="panel-collapse collapse" aria-expanded="false"> 
									<div id = "contractlist">
										<div style="font-weight:bold; text-align: center;padding:10px 0;">Mining Contracts</div>
										
										<div class="panel-body">
										  <?php if (!empty($flag) && $flag != 'hw') { ?>
												<div class="con-container">
													<?php
														$i = 0;
														foreach ($this->sha_contract as $getCotracts) {
															$type = "ROI";
															
														if ($i % 3 == 0) { 
													?>
													<div class="con-content">
													<?php } ?>
														<form method="POST" action="" id="mining<?php echo $i ?>">
															<div class="col-lg-4" style ="padding:15px;">
																<div class="c-con"  style = "background: #fff;text-align: center;padding:10px;">
																	<h4><?php echo($getCotracts['contract_name']." (  ".$getCotracts['contract_qty']." MH/s)") ?></h4>
																<!--
																	<span style ="display:block;"><?php echo $getCotracts['contract_qty'] ?> <?php if ($getCotracts['total_price'] <= 0.5) { ?>GHS <?php } else { ?> THS <?php } ?></span>
																	-->
																	<span  style ="display:block;"><?php
															
																		?>
																		</span>
																	<input type="hidden" name="sha_hashrate_qty" id="sha_hashrate_qty"
																		   value="<?php echo $getCotracts['contract_id']; ?>"/>
																	<input type="hidden" value="<?php echo($getCotracts['total_price']); ?>"
																		   id="hid_btc_value" name="hid_btc_value"/>
																	<input type="hidden" value="<?php echo($getCotracts['contract_type']); ?>"
																		   id="k_type" name="k_type"/>
																	<input type="hidden" value="<?php echo $authUserNamespace->token; ?>"
																		   name="token">
																	<input type="hidden" value="<?php echo $type ?>" id="contract_type"
																		   name="contract_type"/>
																	<div class="btn_container" style = "margin:25px;">
																		<!--<input type="button" value="BUY NOW" class="btn_"
																									  onclick="purchase('mining<?php echo $i ?>');">-->
																			<a class="btn btn-inverse btn-md" onclick="purchase('mining<?php echo $i ?>');">BUY NOW</a>
																	
																	</div>
																</div>
															</div>
														</form>
														<?php 
															if ($i == 2 || $i == 5 || $i == 8 || $i == 11 || $i == 14 || $i == (sizeof($this->sha_contract) - 1)) { 
																 if ($i != 0) { 
														?>
																<div class="clearfix"></div>
														</div>
														<?php
																 } 
																} 
																$i++;
															}
														?>
												</div>
												<div class="err" style="text-align:center;color:red;display:none;"></div>

											<?php } ?>
										
										</div> 
									</div> 	
								</div> 
							</div> 
							<div class="panel  panel-primary"> 
                                <div class="panel-heading"> 
                                    <h4 class="panel-title"> 
                                        <a data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseFour-2" class="collapsed" aria-expanded="false">
                                            Enter active Kit Number
                                        </a> 
                                    </h4> 
                                </div> 
                               										 
               
									<div id="buycontract" style = "display:none;">
										 <div id="buycontractid" class = "c-con" >
										<div class="con-content" style="text-align:center;">
											<div class="clearfix"></div>
											<form action="" method="post" id="purchase_kit">
												<div class="form-group"
													 style="color:red; display:none; padding-left:18px"
													 id="err_purch"></div>

												<div class="col-lg-11 col-lg-offset-1">
													<div class="form-group sizecls">
														<label for="" class="lblTxt" style="font-size:14px;font-weight: bold;">Hashrate</label>
														<label for="" class="lblTxt"  style="display:block;">
															<span id="contractamount"></span></label>
													</div>
													<div class="form-group sizecls">
														<label for="" class="lblTxt"  style="font-size:14px;font-weight: bold;">Kit No.</label>
														<input type="text" class="form-control CommonInputBox" name="kit_number" id="kit_number" value="">
													</div>
												</div>
											
                                                <div class="clearfix"></div>
												<div class="col-lg-6 col-lg-offset-6">
													<input type="hidden" value="" class="form-control" name="total_amount"
														   id="total_amount1">
													<input type="hidden" value="" class="form-control" name="type" id="type">
													<input type="hidden" value="" class="form-control" name="kt_type" id="kt_type">
													<input type="hidden" value="" id="contract_type1" name="contract_type"/>
													<input type="hidden" value="" class="form-control" name="hiddencontractId"
														   id="hiddencontractId">
													<input type="hidden" value="sha" name="buy_now" style="height:30px; width:220px;"/>
													<div class="clearfix" style = "padding-top:7px;margin-bottom:3px;">&nbsp;</div>
													
													<button type="button" onclick="ValidationEvent()" class="btn btn-inverse btn-md btn-float">
														Purchase
													</button>
													<span id="preloader2" class=""
														 style="width:100px;  margin: 0 auto; padding-top: 10px; display:none;">
														<img src="<?php echo BASEPATH; ?>/images/ajax-loader.gif">
													</span>
												</div>
											</form>

											<div class="clearfix"></div>
										</div>

									</div>
										
                                </div> 
                            </div> 
			
							<div class="panel  panel-primary"> 
                                <div class="panel-heading"> 
                                    <h4 class="panel-title"> 
                                        <a data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseFive-2" class="collapsed" aria-expanded="false">
                                            Confirmation
                                        </a> 
                                    </h4> 
                                </div> 
                               
                                    <div id="confirmid"  class="panel-body" style = "display:none;">
                                        
										<div class =  "col-lg-6 col-lg-offset-3 c-con">
											<div id="confirmation">
												<h4><strong>Congratulations!</strong></h4>
												<div class="confirm-content" style = "text-align:center;" >
													
													<p>Your contract has been activated.</p>
													<p class="n-content">You wil be able to see your contract details under the Order History
														section of your user dashboard.</p>
													<p>Contract Invoice is sent to your registered e-mail id.</p>
													<!-- <div class="btn_container"><input type="button" value="VIEW INVOICE" class="btn_"></div>  -->
												</div>
											</div>
											<div id="confirmationPartial" style = "text-align:justify;display:none;">
												<div class="confirm-content">
													<h2></h2>
													<p>The amount paid (<span id="amntpaid"></span>) is not the same as the amount due (<span
																id="amntdue"></span>). </p>
													<p> This invoice is not activated automatically. Please manually activate this invoice from the
														admin panel.</p>
													<p>Please contact us for further assistance.</p>
													<!-- <div class="btn_container"><input type="button" value="VIEW INVOICE" class="btn_"></div>  -->
												</div>
											</div>
           							 </div>
										
										
                                   
                                </div> 
                            </div> 
			
			
                        </div> 
                    </div>
				</div>
			
		
        </div>
    </div>
</div>

<script data-cfasync='false' src="<?php echo BASEPATH; ?>/js/jquery.validate.min.js"></script>
<script data-cfasync='false'>
	
    $(document).ready(function () {
      
        $('input[type=radio][name=kit_type]').change(function () {
                $("#no_of_kits").html('<option selected="selected" value="">Select No of Kits</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="5">5</option><option value="15">15</option>');
			$("#total_amount").val('');
			$("#real_total_amount").val('');
        });
		
		$('#agree').click(function(){
			if (this.checked) {
				$("#pay_now").show();
			}else{
				$("#pay_now").hide();
			}
		}); 

        $('#kit_form').validate({
            // Rules for form validation
            rules: {
                kit_type: {
                    required: true
                },
                no_of_kits: {
                    required: true,
                },

            },

            // Messages for form validation
            messages: {
                kit_type: {
                    required: 'Please Select Kit type',
                },

                no_of_kits: {
                    required: " select  number of kits."
                }
            },

            // Do not change code below
            errorPlacement: function (error, element) {
                error.insertAfter(element.parent());
            }
        });
				 
    
		 $("#purchase1").click(function () {
			
            $('#preloader').show();
            if ($('#no_of_kits').val() == '') {
                $('#preloader').hide();
                $('#selectkits').empty();
                $('#selectkits').append('<em for="no_of_kits" class="invalid" style="font-style:normal;">Please select number of kits.</em>');
                return false;
            }
            
            else {
                $.ajax({
                    url: "<?php echo BASEPATH; ?>/Invoice/miningkits",
                    type: 'POST',
                    data: $("#kit_form").serialize(),
                    dataType: "json",
                    success: function (data) {
						//alert(data);
                        if (data.success != '') {
                            $('#preloader').hide();
                            var innerhtml = '<div class="pay-note"  style = "margin:5px;">' +
                                '<div class="pay-n note">**Please Note: ' +
								'<span style = "display:block;">- After making payment wait for 10-15 seconds for page to reload</span>'+
								'<span style = "display:block;">- Amount shown in invoice is excluding of transaction fee. Please include fee while making transaction to allow auto activation of kit</span>'+
								'<span style = "display:block;">- Each address is unique for each invoice, please do not make another transaction on same address.</span>'+
                                                                
                                '</div>'+
							'<div id ="result" class = "count center" style = "padding:10px;color:#ffa900;" > </div>';
                       		if (data.payment_url && data.payment_url != null && data.payment_url != '') {
                                if (data.payment_gateway == 3) {
                                    var millis = data.remaining;
                                    function displaytimer() {
                                        var hours = Math.floor(millis / 36e2),
                                            mins = Math.floor((millis % 36e2) / 60),
                                            secs = Math.floor((millis % 6e1));
                                        //Here, the DOM that the timer will appear using jQuery
                                        hours = hours < 10 ? '0' + hours : hours;
                                        mins = mins < 10 ? '0' + mins : mins;
                                        secs = secs < 10 ? '0' + secs : secs;
                                        if (millis > 0) {
                                            $('.count').html('<div style ="text-align:center;"><span style ="display:inline;margin-left:10px;font-size:16px;font-weight:bold;">Waiting for your payment    </span>  <span style = "display:inline;margin-left:50px;">  ' + hours + ':' + mins + ':' + secs + '  </span><hr/></div>');
                                        } else {
                                            $('#payment_block').html('<div style = "padding:40px 20px;"><h4 class = "center">Timeout</h4><p>This invoice has expired. Do not pay to the address of this invoice. Please purchase new kit and make payment</p></div>');
                                        }
                                    }

                                    setInterval(function () {
                                        millis -= 1;
                                        displaytimer();
                                    }, 1000);

                                    innerhtml += '</div><div class = "panel-body"><div id = "payment_block" style = "text-align:center;background-color:#fff;padding:10px;" >' +
                                        '<h4 style = "font-weight:bold;">Order #' + data.invoiceId + '</h4>' +
										 '<div style = "text-align:center;">' +
                                        '<img src="' + data.payment_url + '">' +
                                        '</div>' +
                                        '<div style = "padding:20px;"><p>Please send <span style = "font-size:18px;font-weight:bold;display:inline;" >' + data.price_in_btc + '</span> MCAP to below address</p>' +
                                        '<p style = "font-size:18px;font-weight:bold;text-decoration:underline dashed grey">' + data.input_address + '</p>' +
                                        '</div>' +
                                        '</div>' +
                                       '</div>';
								
									 setInterval(function () {
									//	 millis -= 10;
										 if (millis > 0) {
										$.ajax({
											url: "<?php echo BASEPATH; ?>/Invoicestatusapi/gb2",
											type: 'POST',
											data: {"address":data.input_address,"amount":data.price_in_btc, "type":"mcap"},
											dataType: "json",
											success: function (data) {
												//data = "success";
												//alert(data);
												if(data.success == "success"){
													millis  = 0;
													$('#pay-container').empty();
													$('#pay-container').append('<div class = "panel-body" style = "text-align:center;"><iframe height = "600px" width = "700px" src = "<?php echo BASEPATH; ?>/thankyou?status='+data.success+'"></iframe></div>');
												}
											}
										});
									 }
                                    }, 2000);
                                } else {
                                    innerhtml += '<div id = "payment_block">' +
                                        '<iframe id="if1" style="visibility:visible;border:0px;min-height:740px;width:100%;" src="' + data.payment_url + '"></iframe>' +
                                        '</div>';
                                }
                            }
                            else {
                                innerhtml += '<div class = "center" style="text-align: center;">' +
                                    '<img src = "<?php echo BASEPATH; ?>/images/oops.png">' +
                                    '</div>';
                            }

                            $("#select_kit").css("display", "none");
                          //  $("#contractlist").css("display", "none");
                            $("#contractlist1").css("display", "none");
                            $("#buycontract").css("display", "none");
                            $("#confirmation").css("display", "none");
                            $("#confirmid").css("display", "none");
                            $("#payment_details").css("display", "block");

                            $('#pay-container').empty();
                            $('#pay-container').append(innerhtml);
                            $('#kitselectid').removeClass('active');
                            $('#detailpaymentid').addClass('active');
                        }
                        else {
                            $('#preloader').hide();
                            $('#selectkits').empty();
                            $('#selectkits').append('<em for="no_of_kits" class="invalid">' + data.failure + '</em>');
                            return false;
                        }
                    }
                });
                return false;
            }
        });
		
		
        $("#err_msg").hide();
		/*
        $('#no_of_kits').on('change', function () {
            var kitNo = $('#no_of_kits option:selected').val();
            var cont_id = $('input:radio[name=kit_type]:checked').val();
						
            $("#err_msg").hide();
            $("#tot_amnt").hide();
            $(".purchase").hide();
          
			if(cont_id){
				var price = $("#price"+cont_id).val();
				var total_price = kitNo * price;
				$(".purchase").show();
				$("#tot_amnt").show();
				$("#total_amount").val(total_price);
				$("#real_total_amount").val(total_price);
			}else{
				alert("Please select kit type");
			}
        });
		*/
    });
	
	
</script>

<script data-cfasync='false'>
    function purchase(formid) {
        $('.err').hide();
        $.ajax({
            url: "<?php echo BASEPATH; ?>/Addkit/buycontract",
            type: 'POST',
            data: $("#" + formid).serialize(),
            dataType: "json",
            success: function (data) {
                if (data.failure && data.failure != '') {
                    $('.err').show();
                    $('.err').empty();
                    $('.err').append(data.failure);
                }
                else {
                    if (data && data.amount != null && data.amount != '') {
                        $("#contractlist").css("display", "none");
                        $("#contractlist1").css("display", "none");
                        $("#select_kit").css("display", "none");
                        $("#err_purch").css("display", "none");
                        $('#kit_number').val('');
                        $("#payment_details").css("display", "none");
                        $("#confirmation").css("display", "none");
                        $("#confirmid").css("display", "none");
                        $("#buycontract").css("display", "block");

                        $("#contractamount").text(data.amount+" MH/s");
                        $("#total_amount1").val(data.value);
                        $("#type").val(data.type);
                        $("#kt_type").val(data.k_type);
                        $("#contract_type1").val(data.contract_type);
                        $("#hiddencontractId").val(data.contract_id);
                        $('#kitselectid').removeClass('active');
                        $('#contractid').removeClass('active');
                        $('#buycontractid').addClass('active');
                        var flag = '<?php echo $flag; ?>';
                        if (data.k_type == 'hardware' || ((flag) && flag != '' && flag == 'hw')) {
                            $('#ship_addr').addClass('openpop');
                        }
                        else {
                            $('#ship_addr').removeClass('openpop');
                        }

                    }
                }
            }

        });

    }
	
    function show(id) {
	  if ($('#contractlist').css('display') == 'none') {
            $('#contractlist').slideToggle('swing');
            $('#contractid').addClass('active');
        }
		 if ($('#select_kit').css('display') == 'none') {
            $('#select_kit').slideToggle('swing');
            $('#select_kit').addClass('active');
        }
        if ($('#contractlist1').css('display') == 'block') {
            $('#contractlist1').slideToggle('swing');
            $('#contractid').removeClass('active');
        }
        if ($('#contractlist1').css('display') == 'none') {
            $('#contractlist1').slideToggle('swing');
            $('#contractid').addClass('active');
        }

        //$("#select_kit").css("display", "none");
        $("#payment_details").css("display", "none");
        $("#confirmation").css("display", "none");
        $("#confirmid").css("display", "none");
        $("#buycontract").css("display", "none");
        $('#kitselectid').removeClass('active');
        $('#detailpaymentid').removeClass('active');
        //$('#contractid').addClass('active');
    }


</script>