  
  <?php 
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); $misc_obj->generateToken();
	//echo "<pre>";
	//print_r($this->resultinvoice['invoice_id']);exit;
	//print_r($this->invoiceid);exit;
    //print_r($this->invoiceid."".$this->username);exit;

  ?>
  <style>
	 .form-group {
	display: inline-block;
	width: 300px;
	padding:15px;
	margin-top:-30px;
	float:left;
}

 </style>
  
  
  <div id="innerpage-wrapper">
	<div class="row lightgraybg">
		<div class="col-lg-12">
			<h1 class="page-header gain-bit-Titletxt"></h1>
		</div>
	</div>
	<div class="row">
	  <ol class="breadcrumb">
		  <li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a> > </li>
		  <li class="active"><a href="<?php echo BASEPATH?>/Paidsupportinvoice">Paid support invoice</a> > </li>
		  <li >Change invoice status</li>
	  </ol>
	  <div class="col-lg-12 ">
         <div class="clearfix lightgraybg">
            <div class="bs-example table-responsive" data-example-id="bordered-table"> 
                <table id="data-table-simple"  class="table table-bordered innertbl display" cellspacing="0">
                  <thead>
                    <tr>
                       <th class="sortdesc">Sr.<br>No </th>
                       <th class="sortboth">Username</th> 
                       <th class="sortboth">Invoice ID</th>
                       <th class="sortboth">Status</th> 
                       <th class="sortboth">Created On</th> 
             		</tr> 
                   </thead>
                   <tbody>
						<?php
							$j=1;
							for($i=0;$i<sizeof($this->resultinvoice);$i++){
						?> 
							<tr>
								 <td scope="row"><?php echo $j;?></td> 
								 <td><?php echo $this->resultinvoice[$i]['username']; ?></td> 
								 <td><?php echo $this->resultinvoice[$i]['invoice_id'];?></td>
								 <td><?php echo $this->resultinvoice[$i]['status'];?></td> 
								 <td><?php echo $this->resultinvoice[$i]['created_on'];?></td> 
							</tr> 
						<?php  $j++;} ?>
                   </tbody>
                 </table> 
             </div>
         </div>
      </div>
      <div class="panel panel-primary buynowbox col-lg-12">
         <div class="panel-heading buynowbox Titleheading faqtitlebg">
           Change Invoice status
         </div>
         <div class="panel-body revenuebg">  
   			<div class="err1">
   			  <?php
				$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
				 if(!empty($authUserNamespace->msg) && $authUserNamespace->msg!=""){?>
				<label style="color:red;"><?php echo $authUserNamespace->msg; ?></label>
				<?php $authUserNamespace->msg=""; }?> 
					  <label style="color:red" for="" class="lblTxt"> </label>
					  <?php 
					  $authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
					  if(!empty($authUserNamespace->errormsg) && $authUserNamespace->errormsg!=""){?>
				<label style="color:red;"><?php echo $authUserNamespace->errormsg; ?></label>
				<?php $authUserNamespace->errormsg=""; }?> 
         	 </div>
    	 <div>
  	 </div>
	  <div class="form-group">
		<label for="" class="lblTxt">Password</label>
		 <input type="password" name="password" id="password" class="form-control CommonInputBox" placeholder="password" value="">
	  </div>
	  <div class="form-group">
		<label for="" class="lblTxt">Comments*</label>
			<textarea style="height:35px"  class="form-control CommonInputBox" id="comment" name="comment" rows="15" cols="80" placeholder="" value=""> </textarea>
	  </div>
  	  <div class="form-group" style="width:100%;">
		  <input type="hidden" name="id" id="id" value="<?php echo $this->invoiceid; ?>"/>
          <input type="hidden" name="user" id="user" value="<?php echo $this->username; ?>"/>	
  		  <button type="button" class="btn btn-default Commonbtn" onclick="return validateForm()" >SUBMIT</button>
	  </div>
  </div>
		</div>
	</div>
  </div>
  
  <script>
    function validateForm(){
		
        var password=$("#password").val();
        var comment=$("#comment").val();
		var id=$("#id").val();
		var user=$("#user").val();
		
		if(password.trim()=="")
		{
			$(".err1").html('<label for="" class="lblTxt" style="color:red;">Please enter Password.</label>');
			return false;
		}
		else if(comment.trim()=="")
		{
			$(".err1").html('<label for="" class="lblTxt" style="color:red;">Please enter Comments.</label>');
			return false;
		}
		
		
		else{
   		var dataString ='password='+password+'&comment='+comment+'&id='+id+'&user='+user;
		$.ajax({
			url:"<?php echo BASEPATH;?>/Paidsupportinvoice/updatestatus", 
			type: "POST",    
		    data: dataString,
	  		success:function(response)
	  		{
				 var data=eval('('+response+')');
				 if(data.success!='')
				 {
				      $(".err1").html('<label class="lblTxt" for="" style="color:green;">'+data.success+'</label>');
					  window.location = "<?php echo BASEPATH;?>/Paidsupportinvoice";
				 }
				 else
				 {
					  $(".err1").html('<label class="lblTxt" for="" style="color:red;">'+data.failure+'</label>');
				 }
			}
		 });
		return true;
       }
    }
	


    
    </script>
