<?php
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>
<div id="innerpage-wrapper">
<div class="row lightgraybg">
<div class="col-lg-12 offset-1">
<h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
</div>
<!-- /.col-lg-12 --></div>
<!-- /.row -->
<div class="row">
<ol class="breadcrumb">
		<li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a>
		></li>
		<li>Kits ></li>
		<li>Kit Invoices</li>
</ol>
<div class="form-group"><?php 
$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
if(!empty($authUserNamespace->msg) && $authUserNamespace->msg!="")
{
	?> <label for="" class="lblTxt" style="color: green; padding: 12px;"><?php echo $authUserNamespace->msg; ?></label>
	<?php $authUserNamespace->msg=""; }?> <?php
	if(!empty($this->msg) && $this->msg!="")
	{
		?> <label for="" class="lblTxt" style="color: red;"><?php echo $this->msg; ?></label>
		<?php $authUserNamespace->msg=""; }?></div>
<div class="clearfix">&nbsp;</div>
 <form method = "POST" style="padding:12px;">
 <label for="" class="lblTxt">Search</label>
      <input type="search" class="form-control CommonInputBox"  name="search" id = "search"   placeholder="search" style="width:250px;">
		<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">			
					</form><br>
<div class="clearfix lightgraybg">
<div class="bs-example table-responsive"
		data-example-id="bordered-table">
<table style="width: 100%;" id="data-table-simple"
		class="table table-bordered innertbl display" cellspacing="0">
		<thead>
				<tr>
						<th class="sortdesc">SR. NO</th>
						<th class="sortboth">USERNAME</th>
						<th class="sortboth">INVOICE ID</th>
						<th class="sortboth">AMOUNT PAID</th>
						<th class="sortboth">WALLET ADDRESS</th>
						<th class="sortboth">STATUS</th>
						<th class="sortboth">COMMENTS</th>
						<th class="sortboth">CREATED</th>
						<th class="sortboth">ACTIONS</th>
				</tr>
		</thead>
		<tbody>
		<?php
		$DB = Zend_Db_Table_Abstract::getDefaultAdapter();
		$j=1;
		for($i=0;$i<sizeof($this->result);$i++){
			$invoiceId = $this->result[$i]['invoice_id'];
			$Kit_Data = ("select comment,locked,kit_number from kits where invoice_id = '$invoiceId'");
			$RowResult = $DB->query($Kit_Data);
			$Kits_Data = $RowResult->fetch();

			$Kits_comment = $Kits_Data['comment'];
			$Kits_Lock = $Kits_Data['locked'];
			$kit_number = $Kits_Data['kit_number'];
			
			$payment_mode_query = ("select payment_mode from kits_payments where kits_payments.invoice_id = '$invoiceId'");			
			$paymentResult = $DB->query($payment_mode_query);
			$payment_mode_result = $paymentResult->fetch();

			$payment_mode = $payment_mode_result['payment_mode'];
			?>
				<tr>
						<td scope="row"><?php echo $j; ?></td>
						<td><?php echo $this->result[$i]['username']; ?></td>
						<td><?php echo $this->result[$i]['invoice_id']; ?></td>
						<td><?php echo $this->result[$i]["amount"];?></td>
						<td><?php echo $this->result[$i]["wallet_addr"];?></td>
						<td><?php echo $this->result[$i]["status"];?></td>
						<td><?php echo $this->result[$i]["comment"];?></td>
						<td><?php echo $this->result[$i]["created_on"];?></td>
						
						<td>
							  <form method="post" action="<?php echo BASEPATH; ?>/Paidsupportinvoice/changestatus" name="form" id="form<?php echo $this->result[$i]['invoice_id']; ?>">
									<?php if($this->result[$i]["status"]=='Inactive'){ ?> <a
										href='#'
										onclick="changeStatus('<?php echo $this->result[$i]['invoice_id']; ?>')">Activate</a>
										<?php } else{ ""; ?> <?php }?>

								 <input type="hidden" value="<?php echo $this->result[$i]['username']; ?>" id="user_name" name="user_name">

								 <input type="hidden" value="<?php echo $this->result[$i]['invoice_id']; ?>" id="invoiceid" name="invoiceid">



							 </form>
						</td> 

				</tr>
				<?php $j++; } ?>
		</tbody>
</table>
         <ul class="pagination">
		 <?php 
		 $StartPage = !empty($_GET['page'])?$_GET['page']:1;
		 if(!empty($StartPage))
		 {
		 	$StartPage=$_GET['page'];
		 }
		 else 
		 {
		 	$StartPage=1;
		 }
		 if($this->pages <= 5){
			  $StartPage = 1;
		 }else if(!empty($_GET['page']) && $_GET['page'] < $this->pages-6){
			 // $pageDiff = $pages - $_GET['page'];
			// $StartPage = $pages - $pageDiff;
			 $StartPage = $_GET['page'];
		 }else if(!empty($_GET['page']) && $_GET['page'] >= $this->pages-6){
			 $StartPage = $this->pages - 5;
		 }
			
		 if($this->pages > 5){
			 $limitPage = $StartPage + 4;
		 }else{
			 $limitPage = $this->pages;
		 }
		 
			
		 if(!empty($_GET['page']) && $_GET['page'] > 1){
		 
		 ?>
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Paidsupportinvoice?page=1"></a></li>
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Paidsupportinvoice?page=<?php echo $_GET['page']-1; ?>"><i class="mdi-navigation-chevron-left"></i></a></li>
			 <?php 
				}
			 ?>
			
			<?php 
			
			for($j=$StartPage;$j<=$limitPage;$j++){
                    ?>
			<li class="active"><a href="<?php echo BASEPATH;?>/Paidsupportinvoice?page=<?php echo $j; ?>"><?php echo $j; ?></a></li>
			<?php }
			
			 if( $_GET['page'] < $this->pages-1){
				 
                    ?>
			
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Paidsupportinvoice?page=<?php echo $_GET['page']+1; ?>"><i class="mdi-navigation-chevron-right"></i></a></li>
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Paidsupportinvoice?page=<?php echo $this->pages-1; ?>"></a></li>
			<?php }
			
                    ?>
		 </ul>
</div>
</div>
</div>
</div>

<script data-cfasync="false"  type="text/javascript">
	
	
  function changeStatus(invoiceid)
     {
		 document.getElementById('form'+invoiceid).submit();
 	 }	
	
	
    
    </script>
