 <?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
	
	//print_r();exit;
?>

 
 <style>
	 .padd10{
	 	padding:10px 0px;
	 }
	 .mleft{
	 	margin-left:25%;
	 }
	 @media (max-width:480px){
		 .mleft{
		 margin-left:0%;
		 }
	 }
</style>
<div class="content">
	<!-- Page-Title -->
	<div class="page-title-group">
		<h4 class="page-title">Help & Support</h4>
		<h5 class="text-muted page-title-alt">My Requests</h5>
	</div>
	<div class="cb-page-content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="card-box">
						<div class="card-box-head  border-b m-t-0">
							<h4 class="header-title"><b>My Service Requests</b></h4>
						</div>
						<div class="card-box-content form-compoenent">
								<form class="form-inline" method="POST"	action="<?php echo BASEPATH; ?>/Servicerequestlist">
									<div class="form-group">
										<label>Start Date</label>
										<input id="datetimepicker" class="datepick form-control"  type="text" name="startdate"  value="<?php  if(!empty($this->datearr) && ($this->datearr['startdate']!='')){ echo $this->datearr['startdate']; } else { } ?>" class="form-control calculateSearchbox" placeholder="Start Date" />   
									</div>
									<div class="form-group ">
										<label>End Date</label>
									   <input id="datetimepicker" class="datepick form-control"  type="text" name="enddate"  value="<?php  if(!empty($this->datearr) && ($this->datearr['enddate']!='')){ echo $this->datearr['enddate']; } else { } ?>" class="form-control calculateSearchbox" placeholder="End Date" />     
									</div>

									<button class="btn btn-primary btn-md" name="search" type="submit">Search</button>
								</form>							
							
						     <div class="bs-example table-responsive">
								   <table id="data-table-simple"  class="table table-bordered innertbl display" cellspacing="0">
										 <thead>
										<tr>
										   <th class="sortdesc">S.No.   </th>
										   <th class="sortboth">Service Request No.</th>
									  <!--     <th class="sortboth">SR TYPE</th> --> 
										   <th class="sortboth">SR Category</th>
										   <th class="sortboth">Description</th> 
										   <th class="sortboth">Date</th> 
										   <th class="sortboth">Status</th>   
											<th class="sortboth"></th>                    
										 </tr> 
									 </thead>
									  <tbody id="memberdetails"> 
									   <?php 
									   if(!empty($this->result) && sizeof($this->result)>0)
									   {
									   $j=1;

									   for($i=0;$i<sizeof($this->result);$i++){                  	
									   $requeststatus = $this->result[$i]['status'];
									   $descri=$this->result[$i]['query'];
									   $limit=20;
									  ?>
									   <tr>
										 <td scope="row"><?php echo $j; ?></td> 
										 <td><a	id="<?php echo $this->result[$i]['ticket_id'];?>"
									data-toggle="modal"
									href="#req-admin"
									name="myname"
									onclick="getrequestdata('<?php echo $this->result[$i]['ticket_id']; ?>');"
									class="myclass"
								><?php echo $this->result[$i]['ticket_id'];?></a></td>
										<!-- <td><?php echo $this->result[$i]['req_type']; ?></td> --> 
										 <td style="text-align:left;"><?php echo $this->result[$i]['req_category']; ?></td>             
										 <td style="text-align:left;">
										  <?php if (strlen($descri) > $limit)
											  $descri = substr($descri, 0, strrpos(substr($descri, 0, $limit), ' ')) . '...';
											  echo $descri; ?> 
										</td>
										 <td><?php
											 echo date("d-m-Y H:i:s",strtotime($this->result[$i]['created_on']));
										// $this->result[$i]['created_on']; ?></td>
										 <td id="main<?php echo $this->result[$i]['ticket_id']; ?>"><?php  if($requeststatus=='1'){$st='Open';}else if($requeststatus=='2'){$st='Assigned';}else if($requeststatus=='3'){$st='Resolved';}else if($requeststatus=='4'){$st='Reopen';}else if($requeststatus=='5'){$st='Pending';}else if($requeststatus=='6'){$st='Response Sent';}else if($requeststatus=='7'){$st='Sent to Technical Team';}else if($requeststatus=='8'){$st='Input Required from User';}else if($requeststatus=='9'){$st='Sent to Senior Support';}else if($requeststatus=='10'){$st='Sent to Admin';}else if($requeststatus=='11'){$st='Pending Kit Activation';}else if($requeststatus=='12'){$st='Pending Refund Related';}else if($requeststatus=='13'){$st='Pending Others';} else {$st='Closed';}echo $st; ?></td>
										<td id="child<?php echo $this->result[$i]['ticket_id']; ?>"><?php if($requeststatus==3) { ?><a 	data-toggle="modal"
									href="#"
									onclick="changeStatus('<?php echo $this->result[$i]['ticket_id']; ?>','Reopen');"

									class="myclass" id="reopen<?php echo $this->result[$i]['ticket_id']; ?>">Reopen</a>&nbsp;&nbsp;

									<a href="#" id="close<?php echo $this->result[$i]['ticket_id']; ?>" onclick="changeStatus('<?php echo $this->result[$i]['ticket_id']; ?>','Close');">Close</a><?php } ?></td>

									  </tr> 

								 <?php $j++;
									   }
									   } ?>  

									 </tbody>
									  </table> 
              </div>

        </div>

    </div>
    
    <!-- for lightbox in bootstrap -->
	<div class="modal bg-popup" id="req-admin">
			<div class="modal-dialog  height-popup big-pop-center1">
				<div class="modal-content no-padding">
					<div class="bg-pop-header"><span class="text-pop-header">SERVICE REQUEST DETAIL</span>
					<button	type="button" class="close"	data-dismiss="modal" aria-hidden="true"><i class="fa fa-close" style="color:#fff;"></i></button>
				</div>
				<div class="pop-body">
					<div class="col-md-8 col-md-offset-2 col-xs-11 col-xs-offset-1">
						<div class="row padd10">
							<div class="col-lg-6 col-xs-6"><b>SR No:</b></div>
							<div class="col-lg-6 col-xs-6" id="service_no"></div>
						</div>
						<div class="row padd10">
							<div class="col-lg-6 col-xs-6"><b>SR Category:</b></div>
							<div class="col-lg-6 col-xs-6" id="sr_category"></div>
						</div>
						<div class="row padd10">
							<div class="col-lg-6 col-xs-6"><b>Date:</b></div>
							<div class="col-lg-6 col-xs-6" id="date"></div>
						</div>
						<div class="row padd10">
							<div class="col-lg-6 col-xs-6"><b>Status:</b></div>
							<div class="col-lg-6 col-xs-6" id="status1"></div>
						</div>
						<div class="row padd10">
							<div class="col-lg-6 col-xs-6"><b>Description:</b></div>
							<div class="col-lg-6 col-xs-6" id="description"></div>
						</div>
					</div>
					
					<div style="padding:15px;">
						<table class="table table-bordered innertbl display" style="width:100%; font-size: 82%;">
						<thead>
						  <tr>
							<th style="width:10%;">Sr No.</th>
							<th style="width:19%;">Date</th>
							<th style="">Comments</th>
							<th style="width:19%;">Comments By</th>
						  </tr>

						</thead>
						  <tbody id="helpquerycommnt">
							</tbody>

						</table>
					</div>	
				</div>
			</div>
		<!-- /.modal-content -->
		</div>
		<!-- /.modal-dialog -->
	</div>
					
					
	<div class="modal bg-popup"	id="changestatus">	
		<div class="modal-dialog popup pop-center-sl" >
				<div class="modal-content no-padding">
				<div class="bg-pop-header"><span class="text-pop-header">CHANGE STATUS</span>
					<button type="button" class="close"	data-dismiss="modal" aria-hidden="true" onclick="closeStatusPop();"	><i class="fa fa-close" style="color:#fff;"></i></button>
				</div>
				<div class="pop-body-status" >
					<form name="formkit" id=""formkit"" action='' method="post" class="form-basic">
						<div class="inputhodler" id="kit_err" style="display:none;">

						</div>
						<div class="err1"></div>	          
						<div class="main_div form-group mleft">
							<div class="sub_div"><p> Status:</p></div>
							<div class="sub_div3">
								<input readonly type="text" name="status" id="status" class="form-control " placeholder=""  Value="">
							</div>

						</div>
						<input type="hidden" id="ticket" name="ticket" value="">
						<div class="main_div form-group mleft">
							<div class="sub_div">
								  Comment:
							</div>
							<div class="sub_div3">
								<textarea type="textarea" name="comment" id="comment" class="form-control " placeholder="" value="" ></textarea>
							</div>

						</div>	
						<div class="main_div form-group mleft" >
							<input type="button" value="Submit" name="sharekt" onclick="submitStatus()" class="btn btn-primary btn-md">
						</div>	
					</form>	
				</div>
				</div>
		
		
		<!-- /.modal-content --></div>
		<!-- /.modal-dialog --></div>



    
    </div>
              
          </div>
<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">      
            <!-- /.row -->
            
            <!-- /.row -->
            
 <script>        
 function getrequestdata(id)
 {
	
 	var reqId=id;
 	//alert("hi"+reqId);
 			 $.ajax({
 				
 				url:"<?php echo BASEPATH; ?>/Servicerequestlist/requset", 
 				type: "POST",    
 			    data: 'request='+reqId,
 				
 		  		success:function(response)
 		  		{
 		  
 				var data=JSON.parse(response);
 			
 				//alert(response);
 				//var innerhtml='';		
 				for(var k=0;k<(data['data'].length);k++)
 				{															
 					/*innerhtml+='<tr>'+
 					 '<td>'+ data['data'][k]['ticket_id']+'</td>'+
 					 '<td>'+data['data'][k]['req_type']+'</td>'+ 	
 					 '<td>'+ data['data'][k]['req_category']+'</td>'+
 					 '<td>'+ data['data'][k]['created_on']+'</td>'+
 					 '<td>'+data['data'][k]['status']+'</td>'+ 	
 					 '<td>'+data['data'][k]['query']+'</td>'+ 						   
 				  '</tr>';*/
 				 $('#service_no').empty();
				  $('#service_no').append('<div>'+ data['data'][k]['ticket_id']+'</div>');
				  
	//			  $('#sr_type').empty();
	//			  $('#sr_type').append('<div>'+data['data'][k]['req_type']+'</div>');
				  
				  $('#sr_category').empty();
				  $('#sr_category').append('<div>'+ data['data'][k]['req_category']+'</div>');
				  
				  $('#date').empty();
				  $('#date').append('<div>'+ data['data'][k]['created_on']+'</div>');
				  
				  $('#status1').empty();
				  $('#status1').append('<div>'+data['data'][k]['status']+'</div>');

				  $('#description').empty();
				  $('#description').append('<div>'+data['data'][k]['query']+'</div>');
 				 
				  var innerhtml='';

					
				   for(var k=0;k<(data['helpdata'].length);++k)
					{
						
		        	 innerhtml+='<tr>'+
		        	 '<td>'+[k+1]+'</td>'+ 
		        	 
					 '<td>'+data['helpdata'][k]['Date']+'</td>'+ 
					 '<td>'+ data['helpdata'][k]['Comments']+'</td>'+
					 '<td>'+ data['helpdata'][k]['CommentsBy']+'</td>'+
				  '</tr>';	
					}
				
				   $('#helpquerycommnt').empty();
				   $('#helpquerycommnt').append(innerhtml); 
 				}

			}
 			 });
 }
 function changeStatus(ticket,status)
 {
	 
	$('#status').val(status);
	$('#ticket').val(ticket);
	$('#changestatus').addClass('openpop');
 }
 function closeStatusPop()
 {
	 $('#changestatus').removeClass('openpop');
 }
 function submitStatus()
 {
	var token = $('#token').val();
	var ticket = $('#ticket').val();
	var status = $('#status').val();
	var comment = $('#comment').val();

	 $.ajax({			
			url:"<?php echo BASEPATH; ?>/Servicerequestlist/changestatus", 
			type: "POST",    
		    data: 'ticket='+ticket+'&status='+status+'&comment='+comment+'&token='+token,	
		    async:false,		
	  		success:function(response)
	  		{
				if(response!='failed')
				{
					$("#main"+ticket).text(status);
					$("#child"+ticket).text('');
					window.location = "<?php echo BASEPATH;?>/Servicerequestlist";
					
				}
				else{
					//$('#kit_err').empty();
					//$('#kit_err').append('Invalid Request Found');
					$(".err1").html('<label for="" class="lblTxt" style="color:red;">Invalid Request Found</label>');
				}
	  		}
	 });
 }
          
 </script>
<link rel="stylesheet" type="text/css" href="<?php echo BASEPATH; ?>/datetimepicker/jquery.datetimepicker.css"/ >
<script  data-cfasync='false' src="<?php echo BASEPATH; ?>/datetimepicker/jquery.datetimepicker.js"></script>

		<script  data-cfasync='false' type="text/javascript">
			jQuery('.datepick').datetimepicker({
			 format:'Y-m-d',
			});
		</script>   
