<?php
$misc_obj = new Gbc_Model_Custom_Miscellaneous();
$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); $misc_obj->generateToken();
?>
<style>
	table {

		border-collapse: collapse;
		width: 100%;
	}
	td, th {
		border: 1px solid #dddddd;
		text-align: left;
		padding: 8px;
	}

	ul.unorder {
		list-style-type: circle;
	}


</style>
<div class="content">
			<div class="page-title-group">
				<h4 class="page-title">Help & Support</h4>
				<h5 class="text-muted page-title-alt">FAQ's</h5>
			</div>
			<div class="cb-page-content">
				<div class="container">
                    <div class="col-lg-12"> 
		<div class="panel-group" id="accordion-test-2">
				<div class="panel panel-primary">
					<div class="panel-heading highlight">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse"  href="#collapseOne" data-parent="#accordion-test-2">
								What is Gainbitcoin?
							</a>
						</h4>
					</div>
					<div id="collapseOne" class="panel-collapse collapse in">
						<div class="panel-body revenuebg">
							<p>We are a Bitcoin mining company with a customer base in over 25 countries. Online accessibility combined with ease of usage and detailed features of the website are the reasons why we are pioneers in the cloud mining space and have a rapidly growing list of users. We have been researching and have been associated with crypto currencies since their inception. Take a look at our bitcoin mining farm here <a href = "https://www.youtube.com/watch?v=ASSIq4ZDpos" target= "_blank">https://www.youtube.com/watch?v=ASSIq4ZDpos</a></p>
							<p>The strength of our team is their expertise in each of their domain. A robust and experienced technology team combined with a prompt and helpful customer service team has enabled to put our combined efforts in the development, establishment and acceptance of Bitcoin as a currency as well as an indispensable part of the changing economy.</p>
							<p>Gainbitcoin is owned and operated by VARIABLETECH PTE LTD, a company incorporated in Singapore in 2013. Our Registered Address is :</p>
							<address><strong>VARIABLETECH PTE LTD.</strong><br>
								THE FRANKLIN,<br>
								3 SCIENCE PARK DRIVE, <br>
								SINGAPORE-118223 <br>
								<br>

							</address>
						</div>
					</div>
				</div>
				<div class="panel panel-primary ">
					<div class="panel-heading  ">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseTwo">
								Why should I join Gainbitcoin? 
							</a>
						</h4>
					</div>
					<div id="collapseTwo" class="panel-collapse collapse">
						<div class="panel-body revenuebg">With our extensive experience in mining digital currency, we have realized the need for safe, effective and prompt mining servers for best outputs. Consequently, we came up with advanced technology to make mining accessible to all regardless of their age, location, budget or technical knowledge.  <br />
							<br />

							We offer an easy and safe way to purchase hashpower without having to deal with complex hardware and software requirements. All pool, electricity and maintenance fees are included in the price. We offer you an opportunity to start mining Bitcoin and avoid all the usual problems you can face when buying mining equipment, like the usual delays in delivery, breakage losses, the need for a sufficient power supply or cooling devices. We are a team of mining experts with thorough knowledge of crypto currency space. We specialize in building the most efficient and reliable mining rigs that you can rent. The cloud mining contracts we offer are transparent, convenient and cost-effective.<br />
							<br />

							Become a part of the billion dollar industry of cloud mining now and collect Bitcoins as your reward!</div>
					</div>
				</div>
				<div class="panel panel-primary ">
					<div class="panel-heading  faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseThree">
								How can I join Gainbitcoin? 
							</a>
						</h4>
					</div>
					<div id="collapseThree" class="panel-collapse collapse">
						<div class="panel-body revenuebg">Gainbitcoin adds members only through referrals from existing members. You can register on the website using the sponsor id of the member who has referred you. Just enter your email id and contact number and your registration is completed within minutes.</div>
					</div>
				</div>


				<div class="panel panel-primary ">
					<div class="panel-heading  faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle"  data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseFour">
								What are the cloud mining plans available? 
							</a>
						</h4>
					</div>
					<div id="collapseFour" class="panel-collapse collapse">
						<div class="panel-body revenuebg">
							<div class="bs-example table-responsive">
								<table class="table table-bordered innertbl display">
									<thead>
								<tr>
									<th>Mining Plan Name</th>
									<th>Contract Amount BTC</th>
									<th>Payable Amount (BTC)</th>
									<th>Mine Space Allocation</th>
									<th>Monthly Output  (BTC)</th>
									<th>Direct Sales Incentive</th>
									<th>Referral Sales Incentive</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>Amaze Nano</td>
									<td>0.1 </td>
									<td>0.1 </td>
									<td>150 GHS</td>
									<td>.01</td>
									<td>5%</td>
									<td>2% (binary)</td>
								</tr>
								<tr>
									<td>Amaze Micro</td>
									<td>0.2</td>
									<td>0.2</td>
									<td>300 GHS</td>
									<td>.02</td>
									<td>5%</td>
									<td>2% (binary)</td>
								</tr>
								<tr>
									<td>Amaze Mini</td>
									<td>0.5</td>
									<td>0.5</td>
									<td>750 GHS</td>
									<td>.05</td>
									<td>5%</td>
									<td>8% (binary)</td>
								</tr>
								<tr>
									<td>Amaze Solo</td>
									<td>1 </td>
									<td>1</td>
									<td>1.5 THS</td>
									<td>.1</td>
									<td>5%</td>
									<td>8% (binary)</td>
								</tr>
								<tr>
									<td>Amaze A3</td>
									<td>5</td>
									<td>4.85</td>
									<td>7.5 THS</td>
									<td>0.5</td>
									<td>5%</td>
									<td>8% (binary)</td>
								</tr>
								<tr>
									<td>Amaze A4</td>
									<td>15</td>
									<td>13.75</td>
									<td>25 THS</td>
									<td>1.5</td>
									<td>5%</td>
									<td>8% (binary)</td>
								</tr>
								<tr>
									<td>Amaze A5</td>
									<td>25</td>
									<td>22.75</td>
									<td>40 THS</td>
									<td>2.5</td>
									<td>5%</td>
									<td>8% (binary)</td>
								</tr>
								<tr>
									<td>Amaze Q1</td>
									<td>50</td>
									<td>44.5</td>
									<td>75 THS</td>
									<td>5</td>
									<td>5%</td>
									<td>8% (binary)</td>
								</tr>
								<tr>
									<td>Amaze Q2</td>
									<td>75</td>
									<td>64</td>
									<td>115 THS</td>
									<td>7.5</td>
									<td>5%</td>
									<td>8% (binary)</td>
								</tr>
								<tr>
									<td>Amaze Q3</td>
									<td>100</td>
									<td>86</td>
									<td>150 GHS</td>
									<td>10</td>
									<td>5%</td>
									<td>8% (binary)</td>
								</tr>

								</tbody>

							</table>
							</div>	
							<div class="panel-body revenuebg">To explain the above table, let's understand the mining output of the table highlighted in blue color above. In the Amaze Solo plan:
								<br/>
								<ol>
									<li>You buy an 18 month contract of 15 bitcoins by investing 13.75 bitcoins.</li>
									<li>You are allocated a mining power of 25 THS (Tera hash rate) against your account.</li>
									<li>You get 10% of your investment (1.5 bitcoins) in your wallet every month for 18 months.</li>
									<li>his contract is valid for 18 months from the date of purchase. Once the contract is expired, there are no more payouts. You can buy new contracts as well before your contract expires.</li>
								</ol><br>
								<div class="panel-body revenuebg">
									Below table depicts the assured return on investments in cloud mining contract:
								</div>
								<div class="panel-body revenuebg">
								<div class="bs-example table-responsive">
									<table class="table table-bordered innertbl display">
										<thead>
										<tr>
											<th>Contract Plan</th>
											<th>Your Investment @ discounted price (BTC)</th>
											<th>Monthly Return @ 10% (BTC)</th>
											<td>18 months return (BTC)</td>
											<th>Return on mining in 18 months (BTC)</th>
										</tr>
										</thead>
										<tbody>
										<tr>
											<td>Amaze A4</td>
											<td>13.75  </td>
											<td>13.75  </td>
											<td>27</td>
											<td>90% plus</td>
										</tr>
										</tbody>
									</table>
									</div>	
							</div>
						</div>
					</div>
				</div>
						</div>	
				<div class="panel panel-primary">
					<div class="panel-heading ">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseFive">
								How do I earn commission on referral sales? 
							</a>
						</h4>
					</div>
						<div id="collapseFive" class="panel-collapse collapse">
							<div class="panel-body revenuebg">In addition to the cloud mining contract returns, the company also offers direct sales incentives (DSI) and referral sales incentives (RSI) for users who buy gainbitcoin mining contract through your sponsor id. </div>
							<div class="panel-body revenuebg">
								Below is the explanation of the incentives.<br/>

								<ul class="unorder">
									<li style="margin-left:17px;">If you refer someone to purchase a cloud mining contract your sponsor id, you get 5% DSI (Direct Sales Incentive) in the form of bitcoins. </li>
									<li style="margin-left:17px;">The company also offers an 8% RSI (Referral sales incentive) on multi level referrals who join the mining pool in your downline. </li>
								</ul>
							</div>
							<div class="panel-body revenuebg">
								An example of DSI and RSI working is given below. Please refer to the below image for reference. </br>
								<br>
								<br>
								<div class="col-md-4 col-xs-12 col-md-offset-4">
									<img src="<?php echo BASEPATH; ?>/images/tree.png" class="img-responsive center-block"  style="margin-bottom:35px;">
								</div>
								<div class="col-md-12">
									<ul class="unorder"><br>
										<li>A invests 1 BTC in amaze solo plan. </li>
										<li>A refers B to join the pool mining. B invests 1 BTC in amaze solo plan. A places B on the left side.</li>
										<li>A refers C to join the pool mining. C invests 1 BTC in amaze solo plan. A places C on the right side.</li>
										<li>B refers D to join the pool mining. D invests 1 BTC in amaze solo plan. B places D on the left side.</li>
										<li>B refers E to join the pool mining. E invests 1 BTC in amaze solo plan. B places E on the right side.</li>
										<li>C refers F to join the pool mining. F invests 1 BTC in amaze solo plan. C places F on the left side.</li>
										<li>C refers G to join the pool mining. G invests 1 BTC in amaze solo plan. C places G on the right side.</li>
									</ul>
							</div>
							</div>
							<div class="panel-body revenuebg">
								In this scenario, below are the incentive earnings of 'A' from DSI and RSI
						<br/>
							<strong>INCENTIVE EARNINGS OF 'A'</strong><br/><br>
								<div class="bs-example table-responsive">
									<table class="table table-bordered innertbl display">
								<thead>
								<tr>
									<th></th>
									<th>DSI @ 5% (BTC)</th>
									<th>Contracts in Left side (BTC)</th>
									<th>Contracts in Right side (BTC)</th>
									<th>Binary Pair Contracts (BTC)</th>
									<th>RSI @ 8% (BTC)</th>
									<th>Total Earning</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>A refers B and C</td>
									<td>0.05 + 0.05 = 0.10 </td>
									<td>1</td>
									<td>1</td>
									<td>1</td>
									<td>0.08</td>
									<td>0.18</td>
								</tr>
								<tr>
									<td>B refers D & E. C refers F & G</td>
									<td>0</td>
									<td>2</td>
									<td>2</td>
									<td>2</td>
									<td>0.16</td>
									<td>0.16</td>
								</tr>
								</tbody>
							</table>
								</div>	<br/>
							Please note the following important points:<br/>
							<ul class="unorder">
								<li style="margin-left:17px;">You get DSI only for those people who register using your sponsor id.</li>
								<li style="margin-left:17px;">You get RSI only for binary contracts which means for common contracts (of lower value) on the left and right side of your id. </li>
								<li style="margin-left:17px;">For example, if you have 3 BTC contracts on the left side and 3 BTC contracts on the right side then you get binary commission of 8% on 3 BTC which is equal to 0.24 BTC  </li>
								<li style="margin-left:17px;">If you have 5 BTC contracts on the left side and 3 BTC contracts on the right side then you get binary commission of 8% on 3 BTC which is equal to 0.24 BTC. The balance of 2 BTC on the left side is carried forward to the next payout cycle. </li>
								<li style="margin-left:17px;">If you have 5 BTC contracts on the left side and no contracts on the right side then you do not get any RSI. The left side contracts are carried forward to the next payout. Whenever you add contracts on the right side, you will start getting the RSI payouts.</li>
								<li style="margin-left:17px;">You will keep on earning RSI for all new contracts that are bought by users referred by users in your network. Maximum RSI which can be earned in one payout is 15x (15 times your contract value) or 150 BTC whichever is higher. </li>
								<li style="margin-left:17px;">DSI/RSI is an optional scheme. You may or may not wish to participate depending on your nature of business and understanding of Direct Sales.</li>
							</ul>
						</div>
					</div>
				</div>


				<div class="panel panel-primary">
					<div class="panel-heading buynowbox faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseSix">
								How can I buy a cloud mining contract?
							</a>
						</h4>
					</div>
					<div id="collapseSix" class="panel-collapse collapse">
						<div class="panel-body revenuebg">Steps to buy a contract: <br />
							<ol>
								<li>Click on Contract > Buy Contract</li>
								<li>Select the Kit you want to purchase > Enter the number of kits you want to purchase</li>
								<li>Complete the kit purchase by making the payment from your bitcoin wallet</li>
								<li>Wait for the kit to get activated. It normally takes 30 minutes however in some cases it may take upto 24 hours depending on the payment gateway response. You can check the status of your kit in order history section. You will also get an email confirmation from our side once the kit is 'Active'. Thereafter, follow the below steps.</li>
								<li>Click on 'List of Contracts' and choose the contract you wish to purchase</li>
								<li>Enter the kit number and click on purchase</li>
								<li>Your contract is activated and valid for 18 months from the date of purchase. You will receive an E-Mail confirmation with contract details and invoice.</li>
							</ol>
						</div>
					</div>
				</div>


				<div class="panel panel-primary">
					<div class="panel-heading buynowbox faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseSeven">
								What is the mining output (MO) I will receive?
							</a>
						</h4>
					</div>
					<div id="collapseSeven" class="panel-collapse collapse">
						<div class="panel-body revenuebg">It depends on Bitcoin's network difficulty however, we are currently paying fixed 10% monthly mining output against the value of the contract you purchase. For example : If you purchased a contract of 1.5 TH/s worth 1 BTC, with a difficulty level of 59,102,372,780, your monthly mining output will be 0.1 BTC per month for 18 months (duration of the contract)</div>
					</div>
				</div>


				<!--  <div class="panel panel-primary buynowbox">
                <div class="panel-heading buynowbox faqtitlebg">
                <h4 class="panel-title"><a class="accordion-toggle"
                    data-toggle="collapse" data-parent="#accordion" href="#collapseEight">
                What is my mining payout? </a><i
                    class="indicator glyphicon glyphicon-chevron-up pull-right"></i></h4>
                </div>
                <div id="collapseEight" class="panel-collapse collapse">
                <div class="panel-body revenuebg">Though it depend on the Bitcoin
                network's difficulty, but we are currently paying fixed 0.1 BTC with
                your current contract of 400GH/s, example you are buying 400 GH/s and
                with the difficulty level of <strong> 59,102,372,780. Your mining reward
                is 0.1 BTC for next 18 months.</strong></div>
                </div>
                </div> -->


				<div class="panel panel-primary">
					<div class="panel-heading buynowbox faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseNine">
								What are the Payout dates?
							</a>
						</h4>
					</div>
					<div id="collapseNine" class="panel-collapse collapse">
						<div class="panel-body revenuebg">
							<ul class="unorder">
								<li style="margin-left:17px;">Updated payout balance starts reflecting tentatively on 1st and 16th of each month.</li>
								<li style="margin-left:17px;">Once the updated balances are shown system will provide feature to buy kits from GB Wallet for next 3-4 days.</li>
								<li style="margin-left:17px;">Payout disbursement starts from 6th till 15th of each month, similarly for next cycle it starts from 21st till 30th.During this time kits activation via GB Wallet will be disabled.</li>
								<li style="margin-left:17px;">First payout is released post completion of cooling off period (30 days).</li>
							</ul>
					<br/><br/>
							<div class="bs-example table-responsive">

							<table class="table table-bordered innertbl display">
								<thead>
								<tr>
									<th>Contract Purchase Date</th>
									<th>Cooling off period end date</th>
									<th>Mining output period considered</th>
									<th>First MO Payout Date</th>
									<th>RSI and DSI Payout dates</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>1st December</td>
									<td>30th December</td>
									<td>1st to 15th Dec</td>
									<td>16th January</td>
									<td>16th January</td>
								</tr>
								<tr>
									<td>7th October	</td>
									<td>6th November</td>
									<td>7th to 15th Oct</td>
									<td>16th November</td>
									<td>16th November</td>
								</tr>
								<tr>
									<td>17th April</td>
									<td>16th May/td>
									<td>17th April to 30th April</td>
									<td>1st June </td>
									<td>1st June</td>
								</tr>
								<tr>
									<td>24th June</td>
									<td>23rd July</td>
									<td>24th June to 30th June</td>
									<td>16th August</td>
									<td>16th August</td>
								</tr>
								</tbody>
							</table>
							</div>	</br>
						</div>
					</div>
				</div>

				<div class="panel panel-primary">
					<div class="panel-heading buynowbox faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseTen">
								How do I update my Bitcoin wallet address?
							</a>
						</h4>
					</div>
					<div id="collapseTen" class="panel-collapse collapse">
						<div class="panel-body revenuebg">Wallet updation is a one-time activity. Steps to update wallet address :<br/>
							<ol>
								<li>Click on 'Withdrawals' > 'Request' in the menu</li>
								<li>Scroll down to 'My Withdrawal Details'. Enter your wallet address.</li>
								<li>Click on 'Save' button.</li>
								<li>Addition/Updation of wallet address is subjected to E-mail verification.  </li>
							</ol><br/>
							Please note wallet updation feature is disabled 3 days prior to the payout date to avoid hacking/security issues. For example, for the payout due on 16th of the month, wallet updation feature will be disabled on 13th of the same month. The feature will be reactivated on 17th once the payout is released.
						</div>
					</div>
				</div>


				<div class="panel panel-primary">
					<div class="panel-heading buynowbox faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseEleven">
								I did not update my bitcoin wallet address. What happens to my payout? 
							</a>
						</h4>
					</div>
					<div id="collapseEleven" class="panel-collapse collapse">
						<div class="panel-body revenuebg">Need not to worry, your payout stays in the system in that case and is mapped against your username. Please ensure to update your wallet address asap. The pending payout will be processed in the next payout cycle and you will receive it in the wallet address provided by you. </div>
					</div>
				</div>


				<div class="panel panel-primary">
					<div class="panel-heading buynowbox faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseTwelve">
								Where can I see my Mining Output?
							</a>
						</h4>
					</div>
					<div id="collapseTwelve" class="panel-collapse collapse">
						<div class="panel-body revenuebg">Click on 'Outputs' > 'Mining Outputs' in the menu <br>
							Here you will be able to see your mining output calculation against each contract you hold.
							<br>

						</div>
					</div>
				</div>

				<div class="panel panel-primary">
					<div class="panel-heading buynowbox faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2"	href="#collapseThirteen">
								Where can I see my Direct Sales Incentive?
							</a>
						</h4>
					</div>
					<div id="collapseThirteen" class="panel-collapse collapse">
						<div class="panel-body revenuebg">Click on 'Outputs' > 'DSI' in the menu.
							<br><br>
							Here you will be able to see your Direct Sales Incentive earning.
						</div>
					</div>
				</div>



				<div class="panel panel-primary">
					<div class="panel-heading buynowbox faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2"	href="#collapseFourteen"> 
								Where can I see my Referral Sales Incentive?
							</a>
						</h4>
					</div>
					<div id="collapseFourteen" class="panel-collapse collapse">
						<div class="panel-body revenuebg">Click on 'Outputs' > 'RSI' in the menu.
							<br><br>
							Here you will be able to see your Referral Sales Incentive earning.
						</div>
					</div>
				</div>


				<div class="panel panel-primary">
					<div class="panel-heading buynowbox faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseFifteen">
								Can I change my username?
							</a>
						</h4>
					</div>
					<div id="collapseFifteen" class="panel-collapse collapse">
						<div class="panel-body revenuebg">Sorry, user name once registered cannot be changed.</div>
					</div>
				</div>


				<div class="panel panel-primary">
					<div class="panel-heading buynowbox faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseTwentytwo">
								Can I change my E-Mail Address?
							</a>
						</h4>
					</div>
					<div id="collapseTwentytwo" class="panel-collapse collapse">
						<div class="panel-body revenuebg">You can change the communication e-mail address through 'My Profile' section of the website. Updating new E-Mail address is subjected to E-Mail verification from the old address.
							<br />
							However, the primary e-mail address used at the time of registration cannot be changed. </div>
					</div>
				</div>


				<div class="panel panel-primary">
					<div class="panel-heading buynowbox faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseSixteen">
								Can I change my Mobile Number?</a></h4>
					</div>
					<div id="collapseSixteen" class="panel-collapse collapse">
						<div class="panel-body revenuebg">Yes, you can change your mobile number through 'My Profile' section of the website. Changing Mobile number is subjected to E-Mail verification.</div>
					</div>
				</div>


				<div class="panel panel-primary">
					<div class="panel-heading buynowbox faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2"	href="#collapseSeventeen">
								How can I enable 2 factor Authentication?
							</a>
						</h4>
					</div>
					<div id="collapseSeventeen" class="panel-collapse collapse">
						<div class="panel-body revenuebg">Steps to enable 2FA :
							<ol>
								<li>Download Google authenticator app from Google playstore or App store. </li>
								<li>Go to 'My Profile' page on gainbitcoin.com </li>
								<li>Click on 'Enable 2FA'. You will see a QR code on the screen.</li>
								<li>Open google authenticator app on your phone and scan that QR code. A code will be generated in the app.</li>
								<li>Enter that code below the QR code on the screen and click on 'Confirm'</li>
								<li>2FA is now enabled on your account. You will need to enter your password and authenticator code each time you login. </li>
							</ol>
							<br>
							Please note your account is now secure against hacking attacks as long as your password or phone is not compromised with.
						</div>
					</div>
				</div>

				<div class="panel panel-primary">
					<div class="panel-heading buynowbox faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2"	href="#collapseEighteen">
								Can I change my wallet address?
							</a>
						</h4>
					</div>
					<div id="collapseEighteen" class="panel-collapse collapse">
						<div class="panel-body revenuebg">Yes you can change the wallet address as per your wish. However, wallet change is subjected to 2FA or E-Mail verification.
							<br>
						<!--	As a security measure, wallet changes are disabled between 13th to 15th and 28th to 30th of the month. -->
						</div>
					</div>
				</div>


	<!--			<div class="panel panel-primary">
					<div class="panel-heading buynowbox faqtitlebg">
						<h4 class="panel-title" data-toggle="collapse" data-parent="#accordion-test-2"
							href="#collapseNineteen"><a style="cursor:context-menu;" class="accordion-toggle"
							> How can I purchase Ledger Nano Wallet?</a></h4>
					</div>
					<div id="collapseNineteen" class="panel-collapse collapse">
						<div class="panel-body revenuebg">Below are the steps to purchase a Ledger Wallet :
							<ol>
								<li>Click on Contract > Buy Ledger Wallet</li>
								<li>Select the Kit you want to purchase > Enter the number of kits you want to purchase	</li>
								<li>Complete the kit purchase by making the payment from your bitcoin wallet</li>
								<li>Wait for the kit to get activated. It normally takes 30 minutes however in some cases it may take upto 24 hours depending on the payment gateway response. You can check the status of your kit in order history section. You will also get an email confirmation from our side once the kit is 'Active'. Thereafter, follow the below steps.</li>
								<li>Click on 'Buy Ledger Wallet' > List of Wallets and choose the wallet you wish to purchase</li>
								<li>Enter the kit number, enter your shipping address and click on purchase.</li>
								<li>Your order is compete. The ledger wallet will be delivered within 2-3 weeks. You will receive an E-Mail confirmation with invoice.</li>
							</ol>
						</div>
					</div>
				</div>
-->

				<div class="panel panel-primary" id="more">
					<div class="panel-heading buynowbox faqtitlebg">
						<h4 class="panel-title">
							<a style="cursor:context-menu;" class="accordion-toggle" data-toggle="collapse" data-parent="#accordion-test-2" href="#collapseTwenty">
								What is the support TAT for resolution?
							</a>
						</h4>
					</div>
					<div id="collapseTwenty" class="panel-collapse collapse">
						<div class="panel-body revenuebg">To raise a service request, follow the below steps :
							<br>
							<ol>
								<li>Click on 'Help & Support' > 'Log Request' from the menu bar</li>
								<li>Select the query type and mention your comments. </li>
								<li>Customer support team will contact you to provide resolution as per below timelines.
								</li>
							</ol><br>
							<div class="bs-example table-responsive">

							<table class="table table-bordered innertbl display">
								<thead>
								<tr>
									<th>S. No.</th>
									<th>Query Type</th>
									<th>Response time</th>
									<th>Resolution Time</th>
								</tr>
								</thead>
								<tbody>
								<tr>
									<td>1.</td>
									<td>Profile Changes (E-Mail/mobile etc)</td>
									<td>24 hours</td>
									<td>24 hours</td>
								</tr>
								<tr>
									<td>2.</td>
									<td>Payout Calculations</td>
									<td>48 hours</td>
									<td>Upto 7 working days</td>
								</tr>
								<!--	<tr>
									<td>3.</td>
									<td>Refund related</td>
									<td>24 hours</td>
									<td>Upto 7 working days</td>
								</tr> -->
								<tr>
									<td>3.</td>
									<td>Kit Activation</td>
									<td>24 hours</td>
									<td>Upto 5 working days</td>
								</tr>
							<!--	<tr>
									<td>5.</td>
									<td>Reward related</td>
									<td>48 hours</td>
									<td>Upto 7 working days</td>
								</tr> -->
								<tr>
									<td>4.</td>
									<td>Others</td>
									<td>24 hours</td>
									<td>48 hours</td>
								</tr>
								</tbody>
							</table>

							</div>
							</div>
					</div>
				</div>



			</div>











		</div>

	</div>





	<!-- /.row --> <!-- /.row --></div>
</div>


<script>
	$(document).ready(function(){

		$('.panel-title').click(function(){
			//alert("hi in");
			if($(this).find('i').hasClass('glyphicon-chevron-down'))
			{
				//alert("yes");
				$('.indicator').removeClass('glyphicon-chevron-down');
				$(this).find('i').addClass('glyphicon-chevron-up');


			}
			else if($(this).find('i').hasClass('glyphicon-chevron-up'))
			{
				//alert("no");
				$('.indicator').removeClass('glyphicon-chevron-down');
				$(this).find('i').addClass('glyphicon-chevron-down');

				if(!$(this).hasClass('glyphicon-chevron-up') || !$(this).hasClass('glyphicon-chevron-down'))
				{
					// alert("nothing");
					$('.indicator').addClass('glyphicon-chevron-up');
				}
			}



		})
	})


</script>