 <?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>
 
 
 
 
 <style>
	 .form-group {
	    width: 300px;
	}

 </style>
 
<div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12">
                    <h1 class="page-header gain-bit-Titletxt"></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
            
              <ol class="breadcrumb">
                  <li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a> > </li>
                  <li >Send Message</li>
  
            </ol>
           

         

         <div class="col-lg-12">
         
         

<div class="clearfix">&nbsp;</div>

           <div class="panel panel-primary buynowbox col-lg-12">

              <div class="panel-heading buynowbox Titleheading faqtitlebg">
             Send Message
              </div>

              <div class="panel-body revenuebg">
          <form action="" method="post" enctype="multipart/form-data">
<div class="form-group err1" style="width:100%;margin-bottom: 0px;">
		<label for="" class="lblTxt" style="color:red;"></label>
		</div>

 <div id="msg1">
<?php if(!empty($this->msg) && $this->msg!='')
{
?>
   
    <?php echo $this->msg; ?>
 
 
 <?php } ?>
 </div>
 <div id="msg2">
 <?php 
 	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
 
 if(!empty($authUserNamespace->errormessage) && $authUserNamespace->errormessage!="" ){?>
     <label for="" class="lblTxt" style="color:red;"><?php echo $authUserNamespace->errormessage; ?></label>
 
 
 <?php $authUserNamespace->errormessage="";}?>
  </div>
   <div class="form-group">
    <label for="inputCName" class="lblTxt">Enter Text</label>

     <textarea  type="text" rows="4" cols="50" class="form-control CommonInputBox" name="text" id="text" value="<?php ?>" placeholder="Enter Text"></textarea>


      
  </div>

   <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">       
  
    
  <button type="submit" class="btn btn-default Commonbtn" id="send_message" name="send_message" onclick="return validateForm()">SUBMIT</button>

  
</form>
  </div>
          </div>



         </div>

            <!-- /.row -->
            
            <!-- /.row -->
        </div>
        
        
        <!-- /#page-wrapper -->

    </div>
    
    
    <script>
   function validateForm(){
	   $("#msg1").empty();
	   $("#msg2").empty();
  	 var text=$("#text").val();
       
  

		if((text).trim()==''){
			$(".succes").hide();
			$(".err1").html('<label for="" class="lblTxt" style="color:red;">Please enter Message Text.</label>');
			return false;
		}
		else{
				return true;
		}
		}
   </script>