<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>

<style>
.card-box-content {
    padding:0px 20px;
}	
	
</style>
 <!-- Start right Content here --> 
	<!-- ============================================================== -->
	<!-- Start content -->
 <div class="content">
	<div class="page-title-group">
		<h4 class="page-title">Mining Output</h4>
		<h5 class="text-muted page-title-alt">Contractwise</h5>
	</div>
	<div class="cb-page-content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="card-box">
						<div class="card-box-head  border-b m-t-0">
							<h4 class="header-title"><b>Mining Output Contractwise</b></h4>
						</div>
						<div class="card-box-content form-compoenent">
							<div class="col-lg-12 " style = "width:100%; overflow:auto;">	
								<table id="data-table-simple" class="table-bordered table-responsive display" cellspacing="0">
									 <thead>
										<tr>
										   <th class="sortdesc">S.No.</th>
										   <th class="sortboth">Time</th> 
										   <th class="sortboth">Net BTC Earned</th> 
										</tr> 
									  </thead>
									  <tbody> 
											  <?php 
												if(!empty($this->result) && sizeof($this->result)>0)
												{
												$j=1;
												foreach($this->result['data'] as $result1){?>
													<tr>
 														 <td><?php echo $j;?></td> 
														 <td><?php echo date("d-m-Y H:m:s", strtotime($result1['timestamp'])); ?></td>
	     												 <td><?php echo number_format((double) $result1['total_amt'], 8, '.', '') . " BTC"; ?></td>
     												 </tr> 

											  <?php $j++; }	} ?>
									 </tbody>
								 </table> 
							</div>		
              			</div>
        			</div>
			    </div>
		    </div>    
        </div>
     </div>
 </div>
