<?php 
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); $misc_obj->generateToken();
?>
<style>
.card-box-content {
    padding:0px 20px;
}	
	
</style>
 <!-- Start right Content here --> 
	<!-- ============================================================== -->
	<!-- Start content -->
<div class="content">
	<!-- Page-Title -->
	<div class="page-title-group">
		<h4 class="page-title">Output</h4>
		<h5 class="text-muted page-title-alt">Direct Sales Incentive</h5>
	</div>
	<div class="cb-page-content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="card-box">
						<div class="card-box-head  border-b m-t-0">
							<h4 class="header-title"><b>Direct Sales Incentive</b></h4>
						</div>
						<div class="card-box-content">
							<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
             <div class="col-lg-12 " style = "width:100%; overflow:auto;">
                <table id="data-table-simple" class="table-bordered display" cellspacing="0">
                     <thead>
                    <tr>
                       <th class="sortdesc">S.No.</th>
                        <th class="sortboth">Time</th> 
                        <th class="sortboth">Output From</th>
                         <th class="sortboth">Net BTC Earned</th> 
                         
                          
                           
                     </tr> 
                 </thead>
                  <tbody> 
				          <?php 
        		$j=1;
        foreach($this->result1 as $result1){?>
                    <tr>

                    
                     <td scope="row"><?php echo $j;?></td> 
                     <td><?php echo date("jS F, Y  h:i A", strtotime($result1['created_on']));?></td>
                      <td><?php echo $result1['from_username'];?></td> 
                      <td><?php echo number_format((double) $result1['amount'], 8, '.', '') . " BTC"; ?></td>
                     

                     
                  </tr> 

               <?php $j++;} ?>

                

                  

               
             
             
             
                 </tbody>
                  </table> 
				  <div class="clearfix">&nbsp;</div>
              </div>
             </div>

        </div>
		
    </div>

       

    
       <!--  <div class="col-lg-6 col-lg-offset-3 col-xs-offset-1 center-text ">
           <ul class="pagination pagination-sm">
              <li><a href="#"><img src="images/leftarw.png" alt=""></a></li>
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#"><img src="images/rightarw.png" alt=""></a> </li> 
      </ul>
    </div>-->

        
      
    </div>
         
      
    

   

 
     




               
             
                
          
          </div>
      
            <!-- /.row -->
            
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



    </div>
