<?php 
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); $misc_obj->generateToken();
?>
  
  <div id="innerpage-wrapper">
    <div class="row lightgraybg">
      <div class="col-lg-12 offset-1">
        <h1 class="page-header gain-bit-Titletxt innpercontentPad">My Contracts</h1>
      </div>
      <!-- /.col-lg-12 --> 
    </div>
    <!-- /.row -->
    <div class="row">
      <ol class="breadcrumb">
        <li class="active"> <a href="<?php echo BASEPATH; ?>/Dashboard">Dashboard ></a></li>
        <li><a href="#">My Contracts</a></li>
      </ol>

      
    <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">  

      <div class="clearfix">

        <div class="clearfix">&nbsp;</div>
        <div class="col-lg-12 ">
          <div class="clearfix lightgraybg">
            <div class="bs-example table-responsive" data-example-id="bordered-table">
          <table id="data-table-simple"  class="table table-bordered innertbl display" cellspacing="0">
                <thead>
                  <tr>
                    <th class="sortdesc">Sr.<br>
                      No </th>
                    <th class="sortboth">Date/Time </th>
                    <th class="sortboth">Invoice <br>
                      Id</th>
                    <th class="sortboth">Qty</th>
                    <th class="sortboth">Rate</th>
                    <th class="sortboth">Paid <br>
                      Amount</th>
                    <th class="sortboth">Status</th>
                    <th class="sortboth">PDF</th>
                    
                  </tr>
                </thead>
                <tbody>
				<?php
				if(isset($this->result['data']) && sizeof($this->result['data']) > 0){ 
				$sn=1;
				foreach($this->result['data'] as $invoiceDetails)
				{

				$date =isset($invoiceDetails['created_on']) ? date("D jS M, y h:i A", strtotime($invoiceDetails['created_on'])) : '';
							
																	$invoiceId = isset($invoiceDetails['invoice_id']) ? $invoiceDetails['invoice_id'] : '';
							
																	$qty = isset($invoiceDetails['contract_qty']) ? $invoiceDetails['contract_qty'] : '';
							
																	$rate = isset($invoiceDetails['contract_rate']) ? $invoiceDetails['contract_rate'] : '';
							
																	$amtpaid = isset($invoiceDetails['amtPaid']) ? $invoiceDetails['amtPaid'] : '';
							
																	$status = isset($invoiceDetails['invoice_status']) ? $invoiceDetails['invoice_status'] : '';
				?>
                  <tr>
                    <td scope="row"><?php echo $sn; ?></td>
                    <td><?php echo $date; ?></td>
                    <td><?php echo $invoiceId; ?></td>
                    <td><?php echo $qty; ?></td>
                    <td><?php echo $rate; ?></td>
                    <td><?php echo $amtpaid; ?></td>
                    <td><?php if($status=='1'){$st='Active';}else {$st='Inactive';}echo $st; ?></td>
                    <td><a href="<?php echo BASEPATH; ?>/Generateinvoice?invoiceid=<?php echo $invoiceId; ?>">Generate PDF</a></td>
                    
                  </tr>
                  <?php $sn++; }
					}				 
					?>
                </tbody>
              </table>
            </div>
          </div>
        </div>


      </div>
    </div>
    
    <!-- /.row --> 
    
    <!-- /.row --> 
  </div>