<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
	//echo"<pre>";
	//print_r($this->result['status']);exit;
?>


<style>

table.dataTable tbody th, table.dataTable tbody td {
    text-align: left;
}

.clearfix {
  margin-top:-7px;
}
 
</style>
<div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12 offset-1">
                    <h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
              <ol class="breadcrumb">
                  <li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a> > </li>
                  <li>CMS Settings > </li>
                  <li>News</li>
  
            </ol>
<div class="clearfix">&nbsp;</div>           

<a href="<?php echo BASEPATH; ?>/Addnews"><button style="float:right;margin-right:34px;" class="btn btn-default Commonbtn" type="submit">ADD NEWS</button></a>

    <div class="clearfix">&nbsp;</div>      
     <div class="clearfix">&nbsp;</div>   

        <div class="col-lg-12 ">
     
            <div class="clearfix lightgraybg">

                <div class="bs-example table-responsive" data-example-id="bordered-table"> 

             
                     <table id="data-table-simple"  class="table table-bordered innertbl display" cellspacing="0">
                     <thead>
                    <tr>
                       <th class="sortdesc">Sr.<br>No </th>
                        <th class="sortboth">Headline</th> 
                        <th class="sortboth">Details</th>
                         <th class="sortboth">Link</th> 
                         <th class="sortboth">Created</th> 
                         <th class="sortboth">Updated</th> 
                          <th class="sortboth">Status</th> 
                          <th class="sortboth">ACTION</th> 
                         
                         
                          
                           
                     </tr> 
                 </thead>
                  <tbody> 
                     <?php 
        		$j=1;
        foreach($this->result as $result){
		$headline= isset($result['headline']) ? $result['headline'] : '';
									$detail = isset($result['news_details']) ? $result['news_details'] : '';
									$link = isset($result['link']) ? $result['link'] : '';
									$create_date= isset($result['created_on']) ? $result['created_on'] : '';
									$update_date= isset($result['updated_on']) ? $result['updated_on'] : '';
									$status = isset($result['status']) ? $result['status'] : '';
		
		?>
                   <!--   <tr>
                     <td scope="row">1</td> 
                     <td>&nbsp;</td>
                      <td>No data available in table</td> 
                      <td>&nbsp;</td>-->
                   <tr style="text-align:center;">
                     <td scope="row"><?php echo $j;?></td> 
                     <td><?php echo $headline;?></td>
                      <td><?php echo $detail;?></td> 
					  <td><?php echo $link;?></td>
                      <td><?php echo date("d-m-y H:m:s",strtotime($create_date));?></td>
                       <td><?php echo date("d-m-Y H:m:s",strtotime($update_date));?></td>
                        
                      
                         <td><?php //echo $result['status'];
        					if($status==1){?><!--
                   
                    <a href="#" onclick="return changeNewsStatus(<?php echo $result["id"];?>,<?php echo $result['status'];?>)">Inactive</a>
                     		
							-->
							Active
        					<?php }else{?>
        					Inactive
        					<!--
                     	
                   <a href="#" onclick="return changeNewsStatus(<?php echo $result["id"];?>,<?php echo $result["status"];?>)">Active</a>
                     	--></td>
                     	<?php }?>
                     	
                  <td>
                  
                  	<form method="post" action="<?php echo BASEPATH; ?>/Editnew" name="form" id="form<?php echo $result['id'];?>">
			
			
					<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
			
					<input type="hidden" value="<?php echo $result['id'];?>" id="<?php echo $result['id'];?>" name="newsid">
			
					<a href="#" onclick="document.getElementById('form<?php echo $result['id'];?>').submit()">Edit</a>
			
					</form>
					
				</td>
	   	
                     	
          <!--   <td style="text-align:center;"><a href='<?php echo BASEPATH; ?>/Editnew?id=<?php echo $result['id'];?>'>Edit</a></td>-->
                     	
                  </tr> 

               

                

                  

               
             <?php $j++;} ?>
             
             
                 </tbody>
                  </table> 
              </div>

        </div>
		
    </div>

       

    
       <!--  <div class="col-lg-6 col-lg-offset-3 col-xs-offset-1 center-text ">
           <ul class="pagination pagination-sm">
              <li><a href="#"><img src="images/leftarw.png" alt=""></a></li>
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#"><img src="images/rightarw.png" alt=""></a> </li> 
      </ul>
    </div>-->
    <?php  // echo "<div align='center'>".$this->pagination($this->pagination_config)."</div>";
			//	echo "<div>&nbsp;</div>";?>
				

        
      
    </div>
         
      
    

   

 
     




               
             
                
          
          </div>
          
 
<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">         
      
            <!-- /.row -->
            
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



    </div>
    
    <script  data-cfasync='false' type="text/javascript">
			
			function changeStatus(user_name,kit,status)
			{
				$.ajax({
                type: 'POST',
                url: "<?php echo $rootURL; ?>/controller/adminChangeStatus.php?m=changeNewstatus" ,
		data:{'user_name':user_name,'kit_number':kit,'status':status},
                success: function (data) {
                   //alert(data);return false;
				   if(data=='true')
				   {
						location.reload();
				   }
                   
                }

               
               
            	});
			}
		</script>
