<?php $authUserNamespace = new Zend_Session_Namespace("Aranca_Auth"); ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Aranca: Research.Analyze.Communicate</title>
<link href="<?php echo BASEPATH;?>/shared/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/jquery-1.4.2.min.js"></script>
<script src="<?php echo BASEPATH;?>/js/jquery.alerts.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASEPATH;?>/css/jquery.alerts.css" />
<script language="JavaScript" src="<?php echo BASEPATH;?>/shared/htmlDatePicker1.js" type="text/javascript"></script>
<link href="<?php echo BASEPATH;?>/shared/htmlDatePicker.css" rel="stylesheet"/>
<script type="text/javascript">
<?php 
	      if(isset($authUserNamespace->status_message)){
	      	
	?>
	   jAlert("<?php echo $authUserNamespace->status_message; ?>");
	   //alert('hiee');
	      
	<?php
	  unset($authUserNamespace->status_message);
	}
	?>

	function submitForm()
	{
		//alert('inside search');
		var getValue = '6';
		//alert(getValue);exit;
		var assigntitle = document.getElementById("assigntitle").value;
		var projectid = document.getElementById("projectid").value;
		var practice = document.getElementById("practice").value;
		var status = document.getElementById("status").value;
		var clientname = document.getElementById("clientname").value;
		var teammember = document.getElementById("teammember").value;
		var SelectedDate1 = document.getElementById("SelectedDate1").value;
	
		if (SelectedDate1 != "")
		  {
			var positionval  = SelectedDate1.split('/');
			var date = positionval[2]+"-"+positionval[0]+"-"+positionval[1];
		  }
		else
		{
			var date= "";
		}
		
		var SelectedDate2 = document.getElementById("SelectedDate2").value;
		if (SelectedDate2 != "")
		  {
			var positionval1  = SelectedDate2.split('/');
			var date1 = positionval1[2]+"-"+positionval1[0]+"-"+positionval1[1];
		  }
		else
		{
			var date1= "";
		}
		window.location="<?php echo BASEPATH; ?>/subproject/annuallisting/assigntl/"+assigntitle+"/pid/"+projectid+"/pract/"+practice+"/stat/"+status+"/cname/"+clientname+"/tmember/"+teammember+"/dt1/"+date+"/dt2/"+date1+"/sortby/<?php echo $this->sortBy;?>/ord/<?php echo $this->ordVal;?>/getPageValue/"+getValue;
		
	}
</script>
</head>
<body>
<div id="subheader">
	<div class="wrapper">
	    <div id="holder">
        	<label style="margin-left:-23px;">Assignment Title</label>
            <input type="text" style="width:367px;" class="field" name="project" id="assigntitle">
        </div>
        <div id="holder">
        	<label>Project ID</label>
            <input type="text" class="field" name="projectid" id="projectid">
        </div>
  		<div style="margin:0;" id="holder">
        	<label>Practice</label>
            <select class="field" name="practice" id="practice">
              <option selected="selected" value="">Please Select</option>
              <?php	foreach ($this->practice_list as $practice_list){?>
			  <option value="<?php  if(isset($practice_list->id) && $practice_list->id !=""){ echo $practice_list->id;}?>"<?php if($this->practice==$practice_list->id) echo "selected";?>><?php echo $practice_list->value;?></option>
			  <?php } ?> 
<!--              <option>Option1</option>-->
<!--              <option>Option2</option>-->
<!--              <option>Option3</option>-->
            </select>
        </div>
        <br class="clear">
        <div id="holder">
        	<label>Date</label>
            <input type="text" onclick="GetDate(this);" readonly="" id="SelectedDate1" value="" class="field calendar" name="project" onClick="GetDate(this);">
            <input type="text" onclick="GetDate(this);" readonly="" id="SelectedDate2" value="" class="field calendar" name="project" onClick="GetDate(this);">
      </div>
      <div id="holder">
        	<label>Status</label>
            <select class="field" name="status" id="status">
              <option selected="selected" value="">Please Select</option>
              <?php	foreach ($this->status_list as $status_list){?>
			  <option value="<?php  if(isset($status_list->id) && $status_list->id !=""){ echo $status_list->id;}?>"<?php if($this->status==$status_list->id) echo "selected";?>><?php echo $status_list->value;?></option>
			  <?php } ?>
<!--              <option>Open</option>-->
<!--              <option>Completed</option>-->
            </select>
        </div>
        <div style="margin:0" id="holder">
        	<label>Client Name</label>
            <select name="clientname" id="clientname" type="text" class="field">
	            <option selected="selected" value="" >Please Select</option>
	            <?php	foreach ($this->clientname_list as $clientname_list){?>
				<option value="<?php  if(isset($clientname_list->id) && $clientname_list->id !=""){ echo $clientname_list->id;}?>" <?php if($this->clientid==$clientname_list->id) echo "selected";?>><?php echo $clientname_list->name;?></option>
				<?php } ?>
            </select>
        </div>
      <br class="clear">
        <div id="holder">
        	<label style="margin-left:-8px;">Team Member</label>
            <select class="field" name="teammember" id="teammember">
              <option selected="selected" value="">Please Select</option>
              <?php	foreach ($this->teammember_list as $teammember_list){?>
			  <option value="<?php  if(isset($teammember_list->e_id) && $teammember_list->e_id !=""){ echo $teammember_list->e_id;}?>"<?php if($this->teammember==$teammember_list->e_id) echo "selected";?>><?php echo $teammember_list->teammembername;?></option>
			  <?php } ?>
<!--              <option>Option1</option>-->
<!--              <option>Option2</option>-->
            </select>
        </div>
  		<div class="flow_right"><a class="searchbg" href="#" onclick="javascript:submitForm();">Search</a></div>
  	</div>
    <br class="clear">
  
</div>
<div id="contentbg">
	<div class="frame">
    	<br class="clear">
    	<!--Starts Here -->
   	  <div class="wrapper">
   	    <div class="flow_right"><a class="createbg" href="<?php echo BASEPATH; ?>/subproject/addsubproject">Create Sub Project</a></div>
        <br>
        <br class="clear">
        <div id="tablebg">
        	<div style="width:395px;" class="col-first">Project Title</div>
            <div class="col">&nbsp;</div>
            <div class="col">&nbsp;</div>
            <div class="col">Practice</div>
          	<div class="col _m">Project Manager</div>
            <div class="col">Start Date</div>
            <div class="col">End Date</div>
        </div>
            <?php  if(isset($this->listing) && sizeof($this->listing)>0){
					
        		foreach($this->listing as $view_list){
       		 ?>
          <div id="rowbg">
   	  	  <div class="col-first"><a href="#"><?php echo $view_list->title ;?></a> (<?php echo $view_list->project_id ;?>)<br>Budgeted Hrs: <?php echo $view_list->budgeted_hrs;?>  |      Status: <?php echo $view_list->statusvalue;?></div>
            <div class="col _sp"><a href="#"><img border="0" src="<?php echo BASEPATH;?>/images/common/edit.gif"></a> &nbsp; <a href="#"><img border="0" src="<?php echo BASEPATH;?>/images/common/view.gif"></a> 
<!--            <a class="viewbg" href="#">View Sub Projects</a>-->
            </div>
          <div class="col"><?php echo $view_list->practice;?></div>
          	<div class="col _m"><?php echo $view_list->firstname;?>&nbsp;<?php echo $view_list->lastname;?></div>
            <div class="col"><?php echo $view_list->st_date;?></div>
            <div class="col"><?php echo $view_list->end_date;?></div>
         </div> <?php }
        
      
        echo "<div class='pagination'>".$this->pagination($this->pagination_config)."</div>";
				//echo "<div>&nbsp;</div>";
        }
        else{
		?>
		
		<div class='grid-row2'>
			<div align='center' style="width:95%;font-weight:bold;">No Records Found</div>
		</div>
		
		<?php } ?>
      </div>
      <!--Ends Here -->
    </div>
</div>
</body>
</html>