<?php $authUserNamespace = new Zend_Session_Namespace("Aranca_Auth"); 
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Aranca: Research.Analyze.Communicate</title>
<link href="<?php echo BASEPATH;?>/shared/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/jquery-1.4.2.min.js"></script>
<script src="<?php echo BASEPATH;?>/js/jquery.alerts.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASEPATH;?>/css/jquery.alerts.css" />
<script language="JavaScript" src="<?php echo BASEPATH;?>/shared/htmlDatePicker1.js" type="text/javascript"></script>
<link href="<?php echo BASEPATH;?>/shared/htmlDatePicker.css" rel="stylesheet"/>
<script type="text/javascript">

<?php if(isset($this->project_id)) {?>
var id='<?php echo $this->project_id; ?>';
<?php }   ?>


	function ed(cmd,annprid)
	{
		    	window.location.href = '<?php echo BASEPATH;?>/subproject/addsubproject/id/'+cmd+'/annualprojectid/'+annprid;
		
	}

	function view(cmd,view,annprid)
	{			
				//var status=document.getElementById("status_" + cmd).innerHTML ;
				//if(status=="Completed")
				//{
		    	window.location.href = '<?php echo BASEPATH;?>/subproject/addsubproject/id/'+cmd+'/annualprojectid/'+annprid+'/view/'+view;
				//}
				//else
				//{
					//window.location.href = '<?php echo BASEPATH;?>/subproject/addsubproject/id/'+cmd+'/annualprojectid/'+annprid;
				//}
				
		    	}



	function submitForm()
	{
		//alert('inside search');
		var getValue = '6';
		//alert(getValue);exit;
		var assigntitle = document.getElementById("assigntitle").value;
		var projectid = document.getElementById("projectid").value;
		var practice = document.getElementById("practice").value;
		var status = document.getElementById("status").value;
		var clientname = document.getElementById("clientname").value;
		var teammember = document.getElementById("teammember").value;
		<?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id==14 || $authUserNamespace->designation_id== 57){ ?>
		var projectname = document.getElementById("projectname").value;
		<?php } ?>
		var SelectedDate1 = document.getElementById("SelectedDate1").value;
	
		if (SelectedDate1 != "")
		  {
			var positionval  = SelectedDate1.split('/');
			var date = positionval[2]+"-"+positionval[0]+"-"+positionval[1];
		  }
		else
		{
			var date= "";
		}
		
		var SelectedDate2 = document.getElementById("SelectedDate2").value;
		if (SelectedDate2 != "")
		  {
			var positionval1  = SelectedDate2.split('/');
			var date1 = positionval1[2]+"-"+positionval1[0]+"-"+positionval1[1];
		  }
		else
		{
			var date1= "";
		}
		<?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id==14 || $authUserNamespace->designation_id== 57){ ?>
	
		window.location="<?php echo BASEPATH; ?>/subproject/index/id/"+id+"/assigntl/"+assigntitle+"/pid/"+projectid+"/pract/"+practice+"/stat/"+status+"/cname/"+clientname+"/tmember/"+teammember+"/dt1/"+date+"/dt2/"+date1+"/projectname/"+projectname+"/sortby/<?php echo $this->sortBy;?>/ord/<?php echo $this->ordVal;?>/getPageValue/"+getValue;
		
		<?php } else {?>
		
		
		window.location="<?php echo BASEPATH; ?>/subproject/index/id/"+id+"/assigntl/"+assigntitle+"/pid/"+projectid+"/pract/"+practice+"/stat/"+status+"/cname/"+clientname+"/tmember/"+teammember+"/dt1/"+date+"/dt2/"+date1+"/sortby/<?php echo $this->sortBy;?>/ord/<?php echo $this->ordVal;?>/getPageValue/"+getValue;
		
		<?php } ?>
	}
		
		

	function resetForm()
	{
		
				
		$('#assigntitle').val('');
		$('#projectid').val('');
		$('#practice').val('');
		$('#status').val('');
		$('#clientname').val('');
		$('#teammember').val('');
		$('#SelectedDate1').val('');
		$('#SelectedDate2').val('');
		$('#projectname').val('');

		window.location = "<?php echo BASEPATH; ?>/subproject/index/id/"+id;
	}

	function populate_dropdown1(tasktype,check)
	{
		
		var counter="0";
		//document.getElementById('cat_loader1').style.display = 'block';
		$('#projectname').width(125);
		$.ajax({
			url:"<?php echo BASEPATH; ?>/analyst/subprojectnamevalue",
			type: "POST",    
		    data: "tasktype="+tasktype,
		    success: function(response)
		    { 
				j=0;
				if((response!="") && (response!=null))
					 { 
					 var jsonObject = JSON.parse(response);
						
							var option_ele=document.getElementById('projectname');
							 
							for(k=option_ele.length;k>0;k--)
							{
								option_ele.remove(k);
							}

							for(m=0;m<jsonObject.length;m++)
							{
							
								var option_element= new Option(jsonObject[m]['name'],jsonObject[m]['id']);
								document.getElementById('projectname').options[++j]=option_element;
								if(check=="1"){
								<?php if(isset($this->projectname) && $this->projectname!="")
								{?>
								var pro_ID = '<?php echo $this->projectname;?>';
								
								if(jsonObject[m]['id']==pro_ID)
								{
									document.getElementById('projectname').options[j].selected = "selected";
								}
								<?php
								 }?>
								}
							}
						
//							for(key in jsonObject)
//								{
//									var option_element= new Option(jsonObject[key]['name'],jsonObject[key]['id']);
//									document.getElementById('projectname').options[j++]=option_element;
//									
//								}
							
					}
				
				//document.getElementById('cat_loader1').style.display = 'none';
				$('#projectname').width(141);
			}
		});
		
		
	}

	function Sortbydate(sortby)
	{
			document.getElementById('Sort').value = sortby;
			var datesort =  document.getElementById('Sort').value ;
			
			var getValue = '6';
			//alert(getValue);exit;
			var assigntitle = document.getElementById("assigntitle").value;
			var projectid = document.getElementById("projectid").value;
			var practice = document.getElementById("practice").value;
			var status = document.getElementById("status").value;
			var clientname = document.getElementById("clientname").value;
			var teammember = document.getElementById("teammember").value;
			<?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id==14 || $authUserNamespace->designation_id== 57){ ?>
			var projectname = document.getElementById("projectname").value;
			<?php } ?>
			var SelectedDate1 = document.getElementById("SelectedDate1").value;
		
			if (SelectedDate1 != "")
			  {
				var positionval  = SelectedDate1.split('/');
				var date = positionval[2]+"-"+positionval[0]+"-"+positionval[1];
			  }
			else
			{
				var date= "";
			}
			
			var SelectedDate2 = document.getElementById("SelectedDate2").value;
			if (SelectedDate2 != "")
			  {
				var positionval1  = SelectedDate2.split('/');
				var date1 = positionval1[2]+"-"+positionval1[0]+"-"+positionval1[1];
			  }
			else
			{
				var date1= "";
			}
			<?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id==14 || $authUserNamespace->designation_id== 57){ ?>
		
			window.location="<?php echo BASEPATH; ?>/subproject/index/id/"+id+"/datesort/"+datesort+"/assigntl/"+assigntitle+"/pid/"+projectid+"/pract/"+practice+"/stat/"+status+"/cname/"+clientname+"/tmember/"+teammember+"/dt1/"+date+"/dt2/"+date1+"/projectname/"+projectname+"/sortby/<?php echo $this->sortBy;?>/ord/<?php echo $this->ordVal;?>/getPageValue/"+getValue;
			
			<?php } else {?>
			
			window.location="<?php echo BASEPATH; ?>/subproject/index/id/"+id+"/datesort/"+datesort+"/assigntl/"+assigntitle+"/pid/"+projectid+"/pract/"+practice+"/stat/"+status+"/cname/"+clientname+"/tmember/"+teammember+"/dt1/"+date+"/dt2/"+date1+"/sortby/<?php echo $this->sortBy;?>/ord/<?php echo $this->ordVal;?>/getPageValue/"+getValue;
			
			<?php } ?>


	}


	function del(cmd,annprid)
	{

		var annual = "annual";
		
		jConfirm('Are you sure you want to delete?', 'Delete Box', function(r) {
		   if(r){
		    	window.location.href = "<?php echo BASEPATH;?>/project/deleteact/subprid/"+cmd+"/projecttype/"+annual+"/projectid/"+annprid;
		     return true;
		    }
		    else
		    
		      return false;
		  }
		 );
		
	}


	
</script>
</head>
<body>
<div id="subheader">
	<div class="wrapper">
		<input type="hidden" name="Sort" id="Sort">
	    <div id="holder" <?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id==14 || $authUserNamespace->designation_id== 57){?>style="display:none;"<?php }?>>
        	<label style="margin-left:-23px;">Assignment Title</label>       	
            <input type="text" style="width:367px;" class="field" name="project" id="assigntitle" value="<?php if(isset($this->assigntl)) echo $this->assigntl;?>"/>
        </div>
        <div id="holder" <?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id==14 || $authUserNamespace->designation_id== 57){?>style="display:none;"<?php }?>>
        	<label>Project ID</label>
            <input type="text" class="field" name="projectid" id="projectid" value="<?php if(isset($this->pid)) echo $this->pid;?>">
        </div>
  		<div style="margin:0;<?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id==14 || $authUserNamespace->designation_id== 57){?>display:none;"<?php }?>" id="holder">
        	<label>Practice</label>
            <select class="field" name="practice" id="practice">
              <option selected="selected" value="">Please Select</option>
              <?php	foreach ($this->practice_list as $practice_list){?>
			  <option value="<?php  if(isset($practice_list->practiceid) && $practice_list->practiceid !=""){ echo $practice_list->practiceid;}?>"<?php if($this->practice==$practice_list->practiceid){echo "selected";}elseif($authUserNamespace->designation_id=="57"){echo "selected";}elseif($authUserNamespace->designation_id=="14"){echo "selected";}?>><?php echo $practice_list->value;?></option>
			  <?php } ?> 
<!--              <option>Option1</option>-->
<!--              <option>Option2</option>-->
<!--              <option>Option3</option>-->
            </select>
        </div>
        <br class="clear" <?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id==14 || $authUserNamespace->designation_id== 57){?>style="display:none;"<?php }?>>
        <div id="holder" <?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id==14 || $authUserNamespace->designation_id== 57){?>style="display:none;"<?php }?>>
        	<label>Date</label>
            <input type="text" onclick="GetDate(this);" readonly="" id="SelectedDate1"  class="field calendar" name="project" onClick="GetDate(this);" value="<?php if(isset($this->startdate)) echo $this->startdate;?>">
            <input type="text" onclick="GetDate(this);" readonly="" id="SelectedDate2"  class="field calendar" name="project" onClick="GetDate(this);" value="<?php if(isset($this->enddate)) echo $this->enddate;?>">
      </div>
      <div id="holder" <?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id==14 || $authUserNamespace->designation_id== 57){?>style="display:none;"<?php }?>>
        	<label>Status</label>
            <select class="field" name="status" id="status">
              <option selected="selected" value="">Please Select</option>
              <?php	foreach ($this->status_list as $status_list){?>
			  <option value="<?php  if(isset($status_list->id) && $status_list->id !=""){ echo $status_list->id;}?>"<?php if($this->status==$status_list->id) echo "selected";?>><?php echo $status_list->value;?></option>
			  <?php } ?>
<!--              <option>Open</option>-->
<!--              <option>Completed</option>-->
            </select>
        </div>
        <div <?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id==14 || $authUserNamespace->designation_id== 57){?>style="margin-left:17px;"<?php }else {?>style="margin:0"<?php }?> id="holder">
        	<label>Client Name</label>
            <select name="clientname" id="clientname" type="text" class="field">
	            <option selected="selected" value="" >Please Select</option>
	            <?php	foreach ($this->clientname_list as $clientname_list){?>
				<option value="<?php  if(isset($clientname_list->id) && $clientname_list->id !=""){ echo $clientname_list->id;}?>" <?php if($this->clientid==$clientname_list->id) echo "selected";?>><?php echo $clientname_list->name;?></option>
				<?php } ?>
            </select>
        </div>
      <br class="clear" <?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id==14 || $authUserNamespace->designation_id== 57){?>style="display:none;"<?php }?>>
         <div id="holder" <?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id==14 || $authUserNamespace->designation_id== 57){?>style="margin-left:17px;"<?php }else{?>style="display:none;"<?php }?>>
        	<label style="margin-left:-8px;">Project Type</label>
            <select class="field" name="projecttype" id="projecttype" onchange="populate_dropdown1(this.value,'0');">
             	<option value="contract" <?php if($this->projecttype=='contract') echo "selected";?>>Sub Project</option>
<!--              <option>Option1</option>-->
<!--              <option>Option2</option>-->
            </select>
        </div>
         <div id="holder" <?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id==14 || $authUserNamespace->designation_id== 57){?>style="margin-left:17px;"<?php }else{?>style="display:none;"<?php }?>>
        	<label style="margin-left:-8px;">Project Name</label>
            <select class="field" name="projectname" id="projectname">
              <option selected="selected" value="">Please Select</option>
              <?php	foreach ($this->teammember_list as $teammember_list){?>
			  <option value="<?php  if(isset($teammember_list->e_id) && $teammember_list->e_id !=""){ echo $teammember_list->e_id;}?>"<?php if($this->teammember==$teammember_list->e_id) echo "selected";?>><?php echo $teammember_list->teammembername;?></option>
			  <?php } ?>
<!--              <option>Option1</option>-->
<!--              <option>Option2</option>-->
            </select>
        </div>
        
        
        <div id="holder" <?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id==14 || $authUserNamespace->designation_id== 57){?>style="margin-left:17px;"<?php }?>>
        	<label style="margin-left:-8px;">Team Member</label>
            <select class="field" name="teammember" id="teammember">
              <option selected="selected" value="">Please Select</option>
              <?php	foreach ($this->teammember_list as $teammember_list){?>
			  <option value="<?php  if(isset($teammember_list->e_id) && $teammember_list->e_id !=""){ echo $teammember_list->e_id;}?>"<?php if($this->teammember==$teammember_list->e_id) echo "selected";?>><?php echo $teammember_list->teammembername;?></option>
			  <?php } ?>
<!--              <option>Option1</option>-->
<!--              <option>Option2</option>-->
            </select>
        </div>
  		<div class="flow_right"><a class="searchbg" href="#" onclick="javascript:submitForm();">Search</a></div>
  		<div class="flow_right"><a class="searchbg" href="#" onclick="javascript:resetForm();" style=" margin-right:22px;">Reset</a></div>
  	</div>
    <br class="clear">
  
</div>
<div id="contentbg">
	<div class="frame">
    	<br class="clear">
    	<!--Starts Here -->
   	  <div class="wrapper">
   	    <div class="flow_right"><a class="createbg" href="<?php echo BASEPATH; ?>/subproject/addsubproject/annualprojectid/<?php if(isset($authUserNamespace->projectid) && $authUserNamespace->projectid !=""){echo $authUserNamespace->projectid;}?>">Create Sub Project</a></div>
        <br>
        <br class="clear">
        <div id="tablebg">
        	<div <?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id =='56'){?>style="width:345px;"<?php }?> class="col-first">Project Title</div>
        	<?php if(isset($authUserNamespace->designation_id) && $authUserNamespace->designation_id =='56'){?>
            <div class="col">&nbsp;</div>
            <?php }else{?><?php }?>
            <div class="col">&nbsp;</div>
            <div class="col">Practice</div>
          	<div class="col _m" style="width:101px;">Project Manager</div>
			<div class="col" style="width:64px;margin-left:10px">Start Date<div style="float:left; margin-left: 64px;margin-top: -13px; cursor:pointer; width:30px;"><img  src="<?php echo BASEPATH;?>/images/common/sorting_date1.gif" border="1" onclick="Sortbydate(2);" title="Sort" /><div style="float:left; margin-left: 0px; cursor:pointer;"><img  src="<?php echo BASEPATH;?>/images/common/sorting_date.gif" border="1" onclick="Sortbydate(1);" title="Sort" /></div></div></div>
            <div class="col" style="width:64px;margin-left:9px"">End Date<div style="float:left;margin-left: 64px;margin-top: -13px; cursor:pointer; width:30px;"><img  src="<?php echo BASEPATH;?>/images/common/sorting_date1.gif" border="1" onclick="Sortbydate(3);" title="Sort"  /><div style="float:left; margin-left: 0px; cursor:pointer;"><img  src="<?php echo BASEPATH;?>/images/common/sorting_date.gif" border="1" onclick="Sortbydate(0);" title="Sort" /></div></div></div>
        </div>
            <?php  if(isset($this->listing) && sizeof($this->listing)>0){
					
        		foreach($this->listing as $view_list){
        			
        		
        			$subpr_id=$view_list->editid;
        			$annsubObj= new Aranca_Model_DbTable_Annsubteam();
					$empObj=new Aranca_Model_DbTable_Emp();
					$scoresObj=new Aranca_Model_DbTable_Scores();
					$emplist_id=$annsubObj->fetchRow($annsubObj->select()
											 ->from(array('ad'=>DATABASE_PREFIX."annsubteam"))
											 ->where("annsubproject_id='$subpr_id'"));
											
				$i=0;
				$empidStr="";
				$emp_ids=array();
				
				if(isset($emplist_id) && $emplist_id!="")
				{
					if(isset($emplist_id->employee_id1) && $emplist_id->employee_id1!='0')
					{
						//$emp_ids[$i]=$emplist_id->employee_id1;
						//$i++;
						$empidStr=$emplist_id->employee_id1;
					}
					
				}
				
				//------by tushar 12 march--2014
        		if (strpos($empidStr,',') !== false)
				{
					$emp_ids = explode(',', $empidStr);
					
				}
				else
				{
					$emp_ids=$empidStr;
				}
				//print_r($emp_ids);
				$no_of_tm="";
				$no_of_tm=sizeof($emp_ids);
				$counter=0;
				//echo "size of sizeof(emp_ids)".sizeof($emp_ids);
				if(isset($emp_ids))
				{
					for($j=0;sizeof($emp_ids)>$j;$j++)
					{
						
						$scorelist=$scoresObj->fetchAll($scoresObj->select()
					    	                                 ->setIntegrityCheck(false)
			 	    										 ->from(array('s'=>DATABASE_PREFIX."scores"))
															 ->where("s.emp_id='$emp_ids[$j]' && s.project_id=$subpr_id && s.project_type='contract'"));
						
						if(isset($scorelist) && sizeof($scorelist)>0)
						{
							$counter++;
						}
						
					}
				}
				$enable_close="false";
				//echo "value of counter=".$counter."\n";
				//echo "value of no_of_tm=".$no_of_tm."\n";
				if($counter==$no_of_tm)
				{
					$enable_close="true";
				}
        			
       		 ?>
       		
          <div id="rowbg">
   	  	  <a href="#" >
   	  	  <div class="col-first" 
   	  	  <?php if(($authUserNamespace->designation_id) == "56" )
   	  	  {?>style="width: 286px;" onclick="ed(<?php echo $view_list->editid;?>,<?php echo $view_list->annproject_id;?>)"<?php } 
   	  	  else if( ($authUserNamespace->designation_id == "14" || $authUserNamespace->designation_id == "57")&& ($view_list['statusvalue']=="Completed"))
   	  	  {?>style="width: 270px;" onclick="view(<?php echo $view_list->editid;?>,'view',<?php echo $view_list->annproject_id;?>)" href="#"<?php }
   	  	  else {?> style="width: 286px;" onclick="ed(<?php echo $view_list->editid;?>,<?php echo $view_list->annproject_id;?>)"  <?php } ?> >
   	  	  <?php echo $view_list->title ;?> (S)  <?php if (isset($view_list->name) &&  $view_list->name !=""){?> | </a><span style="color:black;font-weight:normal;text-decoration:none;display:inline;"><?php echo $view_list->name ;?><?php }?></span> <br>Budgeted Hrs: <?php echo $view_list->budgeted_hrs;?>  |      Status: <span id="status_<?php echo $view_list->editid;?>"><?php echo $view_list->statusvalue;?></span>
   	  	  </div>
   	  	  </a>
            
            
            <!--<div class="col _sp" <?php if($authUserNamespace->designation_id == "56") { ?>style="width: 200px;"<?php }else {?>style="width:200px;"<?php }?>><a href="#"><img border="0" src="<?php echo BASEPATH;?>/images/common/edit.gif" style="float:left; margin-left:10px;" onclick="ed(<?php echo $view_list->editid;?>,<?php echo $view_list->annproject_id;?>)"></a> &nbsp; <a href="#"><img border="0" src="<?php echo BASEPATH;?>/images/common/view.gif" style="float:left; margin-left:10px;" onclick="view(<?php echo $view_list->editid;?>,'view',<?php echo $view_list->annproject_id;?>)"></a> -->            
            
            <div class="col _sp" <?php if ((($view_list['statusvalue']!="Completed") && ($authUserNamespace->designation_id !="56"))){?>style="width: 200px; "<?php }else {?>style="width:194px;margin-right: 43px;"<?php }?>>
            <a href="#"><img border="0" src="<?php echo BASEPATH;?>/images/common/edit.gif" style="float:left; margin-left:10px;<?php if ((($view_list['statusvalue']=="Completed") && ($authUserNamespace->designation_id !="56"))){?>visibility:hidden;<?php }?>" onclick="ed(<?php echo $view_list->editid;?>,
            <?php echo $view_list->annproject_id;?>)"></a> &nbsp; <a href="#"><img border="0" src="<?php echo BASEPATH;?>/images/common/view.gif" style="float:left; margin-left:10px;" onclick="view(<?php echo $view_list->editid;?>,'view',<?php echo $view_list->annproject_id;?>)"></a>
            <a href="#"><img border="0" src="<?php echo BASEPATH;?>/images/cross.png" style="float:left; margin-left:10px;<?php if ((($view_list['statusvalue']=="Completed") && ($authUserNamespace->designation_id !="56"))){?>visibility:hidden;<?php }?>"  onclick="del(<?php echo $view_list->editid;?>,<?php echo $view_list->annproject_id;?>)"></a>
            
             </a> &nbsp;  
	         <?php ?>
            
             <?php              
           if($enable_close=="true"){ 
          if(isset($view_list['file_path']) && $view_list['file_path']!=""){?> 
          <a class="viewbg icons" target="_blank" href="<?php echo BASEPATH;?><?php echo $view_list['file_path'];?>"><img src="<?php echo BASEPATH?>/images/common/down.gif" style="background-color:white"; title="Final Download Deliverable"></a> 
         <?php }} else{?>
         	<div style="float:right;width:25px;height:25px;">&nbsp;</div>
         <?php }  ?>
             
             <?php
                 $mystring = $view_list->title;
				$findme   = 'feedback';
				$pos = strpos($mystring, $findme);
              if($enable_close=="true") {
              	if($pos === false){
             ?>
             <?php if ($view_list['statusvalue']!="Completed") {?>
             <a class="viewbg icons" href="<?php echo BASEPATH;?>/project/plpmclosure/id/<?php echo $view_list->editid;?>/type/subproject"><img title="Close Project" src="<?php echo BASEPATH; ?>/images/common/close25.gif" /></a> <?php }?><?php }}?>
             	
             	
          	<?php if(isset($authUserNamespace->designation_id) && ($authUserNamespace->designation_id=="56")) {?><a class="viewbg icons" href="<?php echo BASEPATH;?>/project/plscoreinsert/id/<?php echo $view_list->editid;?>/type/subproject"><img title="Score Project" src="<?php echo BASEPATH; ?>/images/common/score25.gif"/></a> <?php } else if(isset($authUserNamespace->designation_id) && ($authUserNamespace->designation_id=="14" || $authUserNamespace->designation_id=="57")) {?><a class="viewbg icons" href="<?php echo BASEPATH;?>/project/plscoreinsert/id/<?php echo $view_list->editid;?>/type/subproject"><img title="Score Project" src="<?php echo BASEPATH; ?>/images/common/score25.gif"/></a> <?php } ?>
            
              <?php if($authUserNamespace->designation_id == "57" ||$authUserNamespace->designation_id == "14") {?> 
             <?php if(isset($view_list->statusvalue) && $view_list->statusvalue !="" && $view_list->statusvalue != 'Completed'){?>
           	 <a href="<?php echo BASEPATH?>/taskpl/allocatetask/pid/<?php echo $view_list->editid;?>/type/contract" <?php if(isset($view_list) &&($authUserNamespace->id == $view_list['pr_manager'] || $view_list['practive_leader'] == $authUserNamespace->id) &&  sizeof($view_list)>0){?>style="visibility:visible;" <?php }else{?>style="visibility:hidden;"<?php }?> class="viewbg icons"><img title="Allocate Task" src="<?php echo BASEPATH; ?>/images/common/allocatetask25.gif"/></a>
            <?php }
             }
              elseif ($authUserNamespace->designation_id == "56"){?>
               <?php if(isset($view_list->statusvalue) && $view_list->statusvalue !="" && $view_list->statusvalue != 'Completed'){?>
            	 <a href="<?php echo BASEPATH?>/taskpl/allocatetask/pid/<?php echo $view_list->editid;?>/type/contract" class="viewbg icons"><img title="Allocate Task" src="<?php echo BASEPATH; ?>/images/common/allocatetask25.gif"/></a>
            <?php } }  ?>
            </div>
          <div class="col"><?php echo $view_list->practice;?></div>
          	<div class="col _m" style="width:105px;"><?php echo $view_list->firstname;?>&nbsp;<?php echo $view_list->lastname;?></div>
            <div class="col" style="width:70px;"><?php echo $view_list->st_date;?></div>
            <div class="col" style="width:70px;"><?php echo $view_list->end_date;?></div>
            
         </div> <?php }
        
      
        echo "<div class='pagination'>".$this->pagination($this->pagination_config)."</div>";
				//echo "<div>&nbsp;</div>";
        }
        else{
		?>
		
		<div class='grid-row2'>
			<div align='center' style="width:95%;font-weight:bold;">No Records Found</div>
		</div>
		
		<?php } ?>
      </div>
      <!--Ends Here -->
    </div>
</div>
</body>
<script>

$( document ).ready(function() {
	
	populate_dropdown1('contract','1');
	});
<?php 
	      if(isset($authUserNamespace->status_message)){
	      	
	?>
	   jAlert("<?php echo $authUserNamespace->status_message; ?>");
	      
	<?php
	  unset($authUserNamespace->status_message);
	}
	?>
</script>
</html>