<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>

<div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12 offset-1">
                    <h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
              <ol class="breadcrumb">
                  <li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a> > </li>
                  <li>Contract Invoices</li>
  
            </ol>
    <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
    
<div class="clearfix">&nbsp;</div>

<div>
<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');

if(!empty($authUserNamespace->msg) && $authUserNamespace->msg!=""){?>
    <label for="" class="lblTxt" style="color:red;"><?php echo $authUserNamespace->msg;?></label>

<?php $authUserNamespace->msg="";}?>
</div>
        <div class="col-lg-12 ">
       
            <div class="clearfix lightgraybg">

                <div class="bs-example table-responsive" data-example-id="bordered-table"> 

             
                     <table id="data-table-simple"  class="table table-bordered innertbl display" cellspacing="0"> 
                     <thead>
                    <tr>
                       <th class="sortdesc">Name </th>
                        <th class="sortboth">Username</th> 
                        <th class="sortboth">Type</th>
                         <th class="sortboth">Quantity</th> 
                          <th class="sortboth">Rate</th> 
                          <th class="sortboth">Status</th> 
                          <th class="sortboth">Change Status</th> 
                          <th class="sortboth">Invoice Id</th> 
                         
                         
                          
                           
                     </tr> 
                 </thead>
                  <tbody> 
                  
                   <?php 
                   $j=1;
                   foreach($this->result as $result){
                   ?>
                   <!--   <tr>
                     <td scope="row">1</td> 
                     <td>&nbsp;</td>
                      <td>No data available in table</td> 
                      <td>&nbsp;</td>-->
                    <tr>
                     <td scope="row"><?php echo $result['contract_name'];?></td> 
                     <td><?php echo $result['username'];?></td>
                      <td><?php echo $result['contract_type'];?></td> 
                      <td><?php echo $result['contract_qty'];?></td>
                      <td><?php echo $result['contract_rate'];?></td>
                      <td>
					  <?php 
						$contract_status = $result['invoice_status'];
							if($contract_status==0){
								echo "Inactive";
							}else if($contract_status==1){
								echo "Active";
							}
							else{
								echo "Cancelled";
								}
					  ?>
					  </td>
					  <td>
					  <form method="post" action="<?php echo BASEPATH; ?>/Pendcontracts/Changecontract" name="form1" id="form1<?php echo $result['invoice_id'];?>">
			
			
									<?php $contract_status = $result['invoice_status'];
							if($contract_status==0){?>
					<a href="#" onclick="changecontract1('<?php echo $result['invoice_id'];?>')">Active</a>
							<?php }else if($contract_status==1){?>
					<a href="#" onclick="changecontract1('<?php echo $result['invoice_id'];?>')">Deactivate</a>
							
							<?php }else{?>
							<?php echo "";
								}?>
								
					<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
					<input type="hidden" value="<?php echo $result['invoice_status'];?>" id="token" name="invoice_status">
					
			
					<input type="hidden" value="<?php echo $result['invoice_id'];?>" id="<?php echo $result['invoice_id'];?>" name="invoice_id">
			
					</form>
				</td>
	
                        <!--  <td><div class="button"> <a class="confirmation" href="#" onclick="changecontract('<?php
						  echo $result['invoice_id']?>','<?php
							  echo $result['invoice_status'];
							   ?>');">
							                      <?php 
								$contract_status = $result['invoice_status'];
								if($contract_status==0){
									echo "Activate";
								}else if($contract_status==1){
									echo "Deactivate";
								}
								else{
									echo "";
									}
								?>
                      </a>
						</td>-->
                        <td><?php echo $result['invoice_id'];?></td>
                     

                     
                  </tr> 

               

                

                  

               
             
             <?php $j++;} ?>
             
                 </tbody>
                  </table> 
                  
       <ul class="pagination">
		 <?php 
		 $StartPage = !empty($_GET['page'])?$_GET['page']:1;
		 if(!empty($StartPage))
		 {
		 	$StartPage=$_GET['page'];
		 }
		 else 
		 {
		 	$StartPage=1;
		 }
		 if($this->pages <= 5){
			  $StartPage = 1;
		 }else if(!empty($_GET['page']) && $_GET['page'] < $this->pages-6){
			 // $pageDiff = $pages - $_GET['page'];
			// $StartPage = $pages - $pageDiff;
			 $StartPage = $_GET['page'];
		 }else if(!empty($_GET['page']) && $_GET['page'] >= $this->pages-6){
			 $StartPage = $this->pages - 5;
		 }
			
		 if($this->pages > 5){
			 $limitPage = $StartPage + 4;
		 }else{
			 $limitPage = $this->pages;
		 }
		 
			
		 if(!empty($_GET['page']) && $_GET['page'] > 1){
		 
		 ?>
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Pendcontracts?page=1"></a></li>
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Pendcontracts?page=<?php echo $_GET['page']-1; ?>"><i class="mdi-navigation-chevron-left"></i></a></li>
			 <?php 
				}
			 ?>
			
			<?php 
			
			for($j=$StartPage;$j<=$limitPage;$j++){
                    ?>
			<li class="active"><a href="<?php echo BASEPATH;?>/Pendcontracts?page=<?php echo $j; ?>"><?php echo $j; ?></a></li>
			<?php }
			
			 if( $_GET['page'] < $this->pages-1){
				 
                    ?>
			
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Pendcontracts?page=<?php echo $_GET['page']+1; ?>"><i class="mdi-navigation-chevron-right"></i></a></li>
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Pendcontracts?page=<?php echo $this->pages-1; ?>"></a></li>
			<?php }
			
                    ?>
		 </ul>
              </div>

        </div>
		
    </div>

       

    
       <!--  <div class="col-lg-6 col-lg-offset-3 col-xs-offset-1 center-text ">
           <ul class="pagination pagination-sm">
              <li><a href="#"><img src="images/leftarw.png" alt=""></a></li>
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#"><img src="images/rightarw.png" alt=""></a> </li> 
      </ul>
    </div>-->
    <?php  // echo "<div align='center'>".$this->pagination($this->pagination_config)."</div>";
				//echo "<div>&nbsp;</div>";?>
				
 
        
      
    </div>
         
      
    

   

 
     




               
             
                
          
</div>
         <!-- /.row -->
            
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



    </div>
    
    <script>

	
    function changecontract1(invoiceid)
    {
		
		var token = $('#token').val();
        var invoiceid=invoiceid;
		var invoicestatus=invoicestatus;
       // alert("/Changecontract?invoiceid="+invoiceid+"&invoicestatus="+invoicestatus);
       
       var r = confirm("Are you sure?");
		if (r == true) {
			//window.location ="<?php echo BASEPATH;?>/Changecontract?invoiceid="+invoiceid+"&invoicestatus="+invoicestatus+"&token="+token;
     	   document.getElementById('form1'+invoiceid).submit();
			
		} else {
   
			}
       
       }
    </script>
