<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
?>


  <style>

.clearfix {
  margin-top:-7px;
}
</style>
 
 
 <div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12 offset-1">
                    <h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
              <ol class="breadcrumb">
                  <li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a> > </li>
                  <li class="active"><a href="<?php echo BASEPATH?>/Binaryuser">Users</a> > </li>
                  <li >User Logs</li>
  
            </ol>
 
       
        <div class="col-lg-12">

      
	<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	if(!empty($authUserNamespace->msg) && $authUserNamespace->msg!="")
		{
		?>
	<div class="form-group">
    <label for="" class="lblTxt" style="color:green; margin-left:16px;"><?php echo $authUserNamespace->msg; ?></label>
    </div>
     <?php $authUserNamespace->msg=""; 
	 
	 }
	 
     if(!empty($authUserNamespace->message) && $authUserNamespace->message!=""){
     ?> 
     <div class="form-group">
    <label for="" class="lblTxt" style="color:red; margin-left:16px;"><?php echo $authUserNamespace->message; ?></label>
    </div>
      <?php  $authUserNamespace->message=""; }?> 
   
<div class="clearfix">&nbsp;</div>

        <div class="col-lg-12 ">
   
            <div class="clearfix lightgraybg">

                <div class="bs-example table-responsive" data-example-id="bordered-table"> 

             
                    <table id="data-table-simple"  class="table table-bordered innertbl display" cellspacing="0">
                     <thead>
                    <tr>
                       <th class="sortdesc">SR.<br>NO </th>
                        <th class="sortboth">DESCRIPTION</th> 
                        <th class="sortboth">DATE/TIME</th>
                         <th class="sortboth">IP ADDRESS</th> 
                           
                     </tr> 
                 </thead>

                  <tbody> 
                        <?php 
        			$j=1;
     		foreach($this->result as $result)
       					{ ?>
                   <tr>
                  <td scope="row"><?php echo $j;?></td> 
                     <td><?php echo $result['description']; ?></td>
                      <td><?php echo $result['created_on']; ?></td> 
                      <td><?php echo $result['ip_address']; ?></td> 

                     
                  </tr> 
  <?php $j++;}  ?>  
             
                 </tbody>
                  </table> 
              </div>

        </div>

    </div>

    

   
      
    </div>
         
      
    

   

 
     




               
             
                
          
          </div>
      
            <!-- /.row -->
            
            <!-- /.row -->
        </div>
       <!-- /#page-wrapper -->



    </div>
    

