  <?php 
  
 	//echo $this->url;exit;
  ?>
<style>
.offersnewcls table tr th{
	text-align:center !important;
}
.offersnewcls  td, th {
    border-radius: 2px;
    display: table-cell;
    padding: 15px 5px;
    text-align: center;
    vertical-align: middle;
}
.offersnewcls th {
	padding: 5px;
}
.offersnewcls table{
	width:100%;
	border-collapse:collapse;
	text-align:center;
}
table.bordered > thead > tr, table.bordered > tbody > tr {
    border-bottom: 1px solid #d0d0d0;
}
</style>  
  
   <div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12">
                    <h1 class="page-header gain-bit-Titletxt">Special Offer</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
            
              <ol class="breadcrumb">
                  <li class="active"><a href="<?php echo BASEPATH; ?>/Dashboard">Dashboard ></a></li>
                  <li>Special Offer</li>
  
            </ol>
           

         

         <div class="col-lg-12 offersnewcls">
         

		<?php if(!empty($this->html) && $this->html!='') { ?>
           <?php echo $this->html; ?>
		   
		<?php }else { ?>
			 <img src="<?php echo $this->url;?>" alt="" class="img-responsive" />
		<?php } ?>



        


















         </div>

       

       

       

            <!-- /.row -->
            
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
	    