
<div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12 offset-1">
                    <h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
              <ol class="breadcrumb">
                  <li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a> > </li>
                  <li>Error404  </li>
                 
  
            </ol>
           </div>

          <div class="clearfix">&nbsp;</div>

     
         <div class="panel-heading faqtitlebg text-center  text-uppercase Title brdright">

             Server Error
             </div>
              <div class="panel-body revenuebg">
			  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
 </div>
</div>
</div>

    </div>
    