<?php
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>

<div id="innerpage-wrapper">
<div class="row lightgraybg">
<div class="col-lg-12 offset-1">
<h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
</div>
<!-- /.col-lg-12 --></div>
<!-- /.row -->
<div class="row">
<ol class="breadcrumb">
		<li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a>
		></li>
		<li>Withdrawals ></li>
		<li>>Daily Withdrawals</li>
</ol>
<div class="form-group"><?php 
$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
if(!empty($authUserNamespace->msg) && $authUserNamespace->msg!="")
{
	?> <label for="" class="lblTxt" style="color: green; padding: 12px;"><?php echo $authUserNamespace->msg; ?></label>
	<?php $authUserNamespace->msg=""; }?> <?php
	if(!empty($this->msg) && $this->msg!="")
	{
		?> <label for="" class="lblTxt" style="color: red;"><?php echo $this->msg; ?></label>
		<?php $authUserNamespace->msg=""; }?></div>
<div class="clearfix">&nbsp;</div>
 <form method = "POST" style="padding:12px;">
 <label for="" class="lblTxt">Search</label>
      <input type="search" class="form-control CommonInputBox"  name="search" id = "search"   placeholder="search" style="width:250px;">
		<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">			
					</form><br>
	
	
<div class="clearfix lightgraybg">
<div class="bs-example table-responsive"
		data-example-id="bordered-table">
<table style="width: 100%;" id="data-table-simple"
		class="table table-bordered innertbl display" cellspacing="0">
		<thead>
				<tr>
						<th class="sortdesc">SR. NO</th>
						<th class="sortboth">WALLET ADDRESS</th>
						<th class="sortboth">MCAP ADDRESS</th>
						<th class="sortboth">AMOUNT</th>
						<th class="sortboth">MCAP VALUE</th>
						<th class="sortboth">Transaction id</th>
						<th class="sortboth">REQUEST DATE</th>
						<th class="sortboth">COMMENTS</th>
						<th class="sortboth">STATUS</th>
						<th class="sortboth"></th>
					
				</tr>
		</thead>
		<tbody>
		<?php
		$DB = Zend_Db_Table_Abstract::getDefaultAdapter();
		$j=1;
		for($i=0;$i<sizeof($this->result);$i++){
			
			?>
				<tr>
					
						<td scope="row"><?php echo $j; ?></td>
						<td><?php echo $this->result[$i]['wallet_address']; ?></td>
						<td><?php echo $this->result[$i]['mcap_address']; ?></td>
						<td><?php echo $this->result[$i]['amount']; ?></td>
						<td><?php echo $this->result[$i]["mcap_calue"];?></td>
						<td><?php echo $this->result[$i]["txid"];?></td>
						<td><?php echo $this->result[$i]["request_date"];?></td>
						<td><?php echo $this->result[$i]["comment"];?></td>
						<td><?php echo $this->result[$i]["status"];?></td>
						
						<td style="max-width:60px;">
								<?php

								if($this->result[$i]['status'] == 1){
							?>
								<div id = "reject_button<?php echo $i; ?>">
									<form method = "POST" action = "Dailywithdrawals/changestatus">
										<input type =  "textbox" name = "comment" >
										<input type =  "hidden" name = "wallet_addr" value ="<?php echo $this->result[$i]['wallet_address']; ?>">
										<input type =  "hidden" name = "amount" value = "<?php echo $this->result[$i]['amount']; ?>">
										<input type =  "submit" name = "submit"  class = "btn Commonbtn" value = "Reject">
									</form>
								</div>
						
							<?php
								}
							?>
						</td>
					
				</tr>
				<?php $j++; } ?>
		</tbody>
</table>
         <ul class="pagination">
		 <?php 
		 $StartPage = !empty($_GET['page'])?$_GET['page']:1;
		 if(!empty($StartPage))
		 {
		 	$StartPage=$_GET['page'];
		 }
		 else 
		 {
		 	$StartPage=1;
		 }
		 if($this->pages <= 5){
			  $StartPage = 1;
		 }else if(!empty($_GET['page']) && $_GET['page'] < $this->pages-6){
			 // $pageDiff = $pages - $_GET['page'];
			// $StartPage = $pages - $pageDiff;
			 $StartPage = $_GET['page'];
		 }else if(!empty($_GET['page']) && $_GET['page'] >= $this->pages-6){
			 $StartPage = $this->pages - 5;
		 }
			
		 if($this->pages > 5){
			 $limitPage = $StartPage + 4;
		 }else{
			 $limitPage = $this->pages;
		 }
		 
			
		 if(!empty($_GET['page']) && $_GET['page'] > 1){
		 
		 ?>
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Dailywithdrawals?page=1"></a></li>
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Dailywithdrawals?page=<?php echo $_GET['page']-1; ?>"><i class="mdi-navigation-chevron-left"></i></a></li>
			 <?php 
				}
			 ?>
			
			<?php 
			
			for($j=$StartPage;$j<=$limitPage;$j++){
                    ?>
			<li class="active"><a href="<?php echo BASEPATH;?>/Dailywithdrawals?page=<?php echo $j; ?>"><?php echo $j; ?></a></li>
			<?php }
			
			 if( $_GET['page'] < $this->pages-1){
				 
                    ?>
			
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Dailywithdrawals?page=<?php echo $_GET['page']+1; ?>"><i class="mdi-navigation-chevron-right"></i></a></li>
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Dailywithdrawals?page=<?php echo $this->pages-1; ?>"></a></li>
			<?php }
			
                    ?>
		 </ul>
</div>

</div>
<input
		type="hidden" value="<?php echo $authUserNamespace->token;?>"
		id="token" name="token">
<!-- /.row -->
<!-- /.row -->
</div>
<!-- /#page-wrapper -->
</div>
