<?php
$misc_obj = new Gbc_Model_Custom_Miscellaneous();
$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); $misc_obj->generateToken();
?>
<div class="content">
	<!-- Page-Title -->
	<div class="page-title-group">
		<h4 class="page-title">Contracts</h4>
		<h5 class="text-muted page-title-alt">Payment Status</h5>
	</div>
	<div class="cb-page-content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="card-box">
						
						<div class="card-box-content form-compoenent">
							
							<div class="clearfix"></div>
							<br>
<div class="row">
<div class="col-lg-12">
<div class="err">
<?php $authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
if(!empty($authUserNamespace->errmsg) && $authUserNamespace->errmsg!=""){?>
<label style="color: red;"><?php echo $authUserNamespace->errmsg;?></label>
<?php $authUserNamespace->errmsg="";}?>
</div>
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title"><strong>Order Details</strong></h3>
</div>
<div class="panel-body">
<div class="table-responsive">
<table class="table table-condensed">
	<thead>
		<tr>
			<td>ORDER NO. <?php echo $this->result['invoiceId']; ?></td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</thead>
	<tbody>


		<tr>
			<td class="thick-line"></td>
			<td class="thick-line"></td>
			<td class="thick-line"></td>
			<td class="thick-line text-right"><?php 
				//print_r($this->result);
			if(isset($this->result['bitcoinpay-status']) && $this->result['bitcoinpay-status']=='true')
			{
				echo 'Congratulations, your Payment is Successful. Thank you!';
			}
			else if(isset($this->result['bitcoinpay-status']) && $this->result['bitcoinpay-status']=='cancel')
			{
				echo "Cancelled";
			}
			else if(isset($this->result['status']) && $this->result['status']!='')
			{
				echo $this->result['status'];
			}
			else
			{
				echo "Pending";
			}
			?></td>
		</tr>
		<tr>
			<td class="no-line"></td>
			<td class="no-line"></td>
			<td class="no-line">&nbsp;</td>
			<td class="no-line text-right">Order Total <?php 
				if($this->result['mcap_price']){
					echo $this->result['mcap_price']." MCAP";	
				}else{
					echo $this->result['price']." BTC"; 
				}
				?>
			</td>
		</tr>

	</tbody>
</table>
</div>
</div>
</div>

</div>
</div>

<input type="hidden" value="<?php echo $authUserNamespace->token;?>"
	id="token" name="token"></div>