 <?php 
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); $misc_obj->generateToken();
 ?>
 <!-- CORE CSS-->
  
<style>
.card-box-content {
    padding:0px 20px;
}	
	
</style>
 
 <!-- Start right Content here --> 
	<!-- ============================================================== -->
	<!-- Start content -->
<div class="content">
	<!-- Page-Title -->
	<div class="page-title-group">
		<h4 class="page-title">ETH Mining</h4>
		<h5 class="text-muted page-title-alt">Output</h5>
	</div>
	<div class="cb-page-content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="card-box">
						<div class="card-box-content">
						<div class="col-lg-12 " style = "width:100%; overflow:auto;">	
					<table id="data-table-simple" class="table-bordered table-responsive display">
                    <thead>
                        <tr>
                             <th class="sortdesc">S.No. </th>
							<th class="sortboth">Date / Time</th> 
							<th class="sortboth">Invoice Id</th>
							 <th class="sortboth">Qty</th> 
							 <th class="sortboth">Rate</th> 
							  <th class="sortboth">Paid Amount</th>
							  <th class="sortboth">Status</th>
							   <th class="sortboth">Action</th> 
                        </tr>
                    </thead>
                 
                  
                    <tbody>
						
						<?php 
        	$j=1;
				foreach($this->result as $invoiceDetails)
				{ 
				   $date =isset($invoiceDetails['Date/Time']) ? date("jS F, Y", strtotime($invoiceDetails['Date/Time'])) : '';
        			$invoiceId = isset($invoiceDetails['InvoiceId']) ? $invoiceDetails['InvoiceId'] : '';
        			$qty = isset($invoiceDetails['Qty']) ? $invoiceDetails['Qty'] : '';
        			$rate = isset($invoiceDetails['Rate']) ? $invoiceDetails['Rate'] : '';
        			$amtpaid = isset($invoiceDetails['PaidAmount']) ? $invoiceDetails['PaidAmount'] : '';
        			$status = isset($invoiceDetails['Status']) ? $invoiceDetails['Status'] : '';
				?>
						
						<tr>
                     <td scope="row"><?php echo $j;?></td> 
                     <td><?php echo  $date; ?></td>
                      <td><?php echo $invoiceId; ?></td> 
                      <td><?php echo $qty; ?></td>
                      <td><?php echo $rate; ?></td> 
                      <td><?php echo $amtpaid; ?></td> 
                      <td><?php if($status=='1'){$st='Active';}else {$st='Inactive';}echo $st; ?></td> 
                      
                     <td>
                      
                      <form method="post" action="<?php echo BASEPATH; ?>/Gb2miningoutput" name="form" id="form<?php echo $invoiceId;?>">
			
			
					<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
			
					<input type="hidden" value="<?php echo $invoiceId;?>" id="<?php echo $invoiceId;?>" name="invoiceId">
					
					
					 <?php
							if($status==1){
						?>
                        <a class="btn btn-purple" onclick="CHECKMININGOUTPUTS('<?php echo $invoiceId;?>')" role="button" style="float:left;">CHECK MINING OUTPUTS</a>
						 <?php } ?>
                    
		
			
						</form>
                      </td>
                      <!-- <td>
					   <?php
							if($status==1){
						?>
                        <a class="btn btn-default Commonbtn text-uppercase" href="<?php echo BASEPATH; ?>/Miningoutput?invoiceId=<?php echo $invoiceId; ?>" role="button">CHECK MINING OUTPUTS</a>
						 <?php } ?>
                      </td>-->

                     
                  </tr> 
				<?php $j++;}  ?> 
               

                

                  

               
                        
                    </tbody>
                  </table>
				</div>		
							 <br><br>
            <div class="divider"></div> 
							
							
						</div>
					</div>
				</div>
			</div>
			<!-- Table Ends -->
		
		</div>
	</div>
</div>

  
    <script>
    function CHECKMININGOUTPUTS(id)
    {
        
   	   document.getElementById('form'+id).submit();
   		 
    }

       
    </script>
    


  