 <?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>
 
 <style>
 	.clearfix {
		 margin-top:-1px;
		}
 
 </style>
 
 <div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12 offset-1">
                    <h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
              <ol class="breadcrumb">
                  <li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a> > </li>
                  <li>Manage Membership</li>
  
            </ol>
     
<div class="clearfix">&nbsp;</div>
	<div class="col-lg-12" align="right" >
     <a href="<?php echo BASEPATH; ?>/Newmembershipmaster"><button style="float:right; margin-right: 2%;" class="btn btn-default Commonbtn" type="submit">ADD NEW</button></a>
	</div>
<div class="clearfix">&nbsp;</div>
        <div class="col-lg-12 ">
      
            <div class="clearfix lightgraybg">

                <div class="bs-example table-responsive" data-example-id="bordered-table"> 

             
               <table id="data-table-simple"  class="table table-bordered innertbl display" cellspacing="0">
                     <thead>
                    <tr>
                       <th class="sortdesc">Sr.<br>No </th>
                       <th class="sortboth">Membership Type</th> 
                       <th class="sortboth">Investment Start</th>
                       <th class="sortboth">Investment End</th> 
                       <th class="sortboth">Level Max</th> 
                       <th class="sortboth">Binary Matching</th>
                       <th class="sortboth">Binary Matching Multiple</th>
                       <th class="sortboth">Binary Capping</th> 
					   <th class="sortboth">TRIMING</th>
                       <th class="sortboth">MINING RETURNS</th>
                        <th class="sortboth">DIRECT SALES COMISSION</th>
                       <th class="sortboth">ACTION</th>   
                       <th class="sortboth">STATUS</th> 
                     </tr> 
                 </thead>
                  <tbody id="memberdetails"> 
                   <?php 
                   $j=1;
                   
                   for($i=0;$i<sizeof($this->result);$i++){
                  ?>
                   <tr>
                     <td scope="row"><?php echo $j; ?></td> 
                     <td><?php echo $this->result[$i]['membership_type'];?></td>
                      <td><?php echo $this->result[$i]['investment_start']; ?></td> 
                      <td><?php echo $this->result[$i]['investment_end']; ?></td>
					    <td><?php echo $this->result[$i]['level_max'];?></td>
						<td><?php echo $this->result[$i]['binary_matching'];?></td>
						<td><?php echo $this->result[$i]['binary_matching_multiple'];?></td>
						<td><?php echo $this->result[$i]['binary_capping'];?></td>
						<td><?php echo $this->result[$i]['trimming'];?></td>
						<td><?php echo $this->result[$i]['mining_returns'];?></td>
						<td><?php echo $this->result[$i]['direct_sales_comission'];?></td>
						<td><form method="post" action="<?php echo BASEPATH; ?>/Editmembershipmaster" name="form" id="form<?php echo $this->result[$i]['id'];?>">
			
			
							<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
			
							<input type="hidden" value="<?php echo $this->result[$i]['id'];?>" id="edit" name="edit">
			
							<a href="#" onclick="document.getElementById('form<?php echo $this->result[$i]['id'];?>').submit()">Edit</a>
			
						</form>
						</td>
					    
                       
                      <td id="memberdata">
                         <?php if($this->result[$i]['status']=='1'){?>
			             <a href='#'
			             id="link<?php echo $this->result[$i]['id'];?>"
			             name="<?php echo  $this->result[$i]['status'];?>"
			             onclick="getmembership('<?php echo $this->result[$i]['id']; ?>','<?php echo $this->result[$i]['status'];?>');">Active</a>   
                        <?php }else{?>
                        <a href='#'
                        id="link<?php echo $this->result[$i]['id'];?>"
                        name="<?php echo $this->result[$i]['status'];?>"
                         onclick="getmembership('<?php echo $this->result[$i]['id']; ?>','<?php echo $this->result[$i]['status'];?>');">Inactive</a>
                        <?php }?>
                        </td>
					
				
                     
                     <!--  <td>
                        <a class="btn btn-default Commonbtn text-uppercase" href="#" role="button">CHECK MINING OUTPUTS</a>

                      </td>-->

                     
                  </tr> 
           
             <?php $j++;} ?>  
             
                 </tbody>
                  </table> 
              </div>

        </div>

    </div>
    
    </div>
              
          </div>
     <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token"> 
            <!-- /.row -->
            
            <!-- /.row -->
            
            <script>
function getmembership(id,status){
	

var memberid=id;
var memberstatus=status;
var token = $('#token').val();

$.ajax({
		
		url:"<?php echo BASEPATH; ?>/Membershiplist/changestatus", 
		type: "POST",    
	    data: 'memberid='+memberid+'&memberstatus='+memberstatus+'&token='+token,
	    async:false,
			success:function(response)
			{
			 var data=JSON.parse(response);
			
	
			
				 if(data['success']=='1')
				{
				//alert("Updated Successfully");
				//alert(data['success']);
				// alert("inside if");
				// alert('#link'+id);
				$('a#link'+id).attr('onclick','getmembership('+id+','+1+')').text('Active');
				// $("a#link"+id).text('active');
				
				
  
					
				}
				 else
				{
					// alert("Updated Successfully");
				//	alert(data['success']);
					// alert("inside else if");
					//alert('#link'+id);
				$('a#link'+id).attr('onclick','getmembership('+id+','+0+')').text('Inactive');
					
					// $("a#link"+id).text('inactive');
				
				}
				 
			}
		
			
			
			
	 });
	
}
            
            
          </script>
      
