<?php 
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); 
	$misc_obj->generateToken();
	//echo "<pre>";
	//print_r($this->result['data']['status']);exit;
	/*echo "<pre>";
	print_r($this->contracttype[1]['contracttype']);exit;*/
?>
<style>
.form-group {
    float:left;
    margin-right: 25px;
    width: 300px;
}
.form{
    float:right;
    width: 100%;
}

</style>
 <div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12 offset-1">
                    <h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
              <ol class="breadcrumb">
                  <li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a> > </li>
                  <li>Contract/Hardware > </li>
                  <li class="active"><a href="<?php echo BASEPATH?>/Allcontract">Contracts</a> > </li>
                  <li>Edit Contract</li>
  
            </ol>
           

          <div class="clearfix">&nbsp;</div>

        
     
 <div class="panel panel-primary buynowbox col-lg-12">

              <div class="panel-heading buynowbox Titleheading faqtitlebg">
              Edit Contract
              </div>

              <div class="panel-body revenuebg">
              
               <div class="errortext">
         
         <label for="" class="lblTxt" style="color:red;">
         		
         </div>
   
    <?php 
       $j=1;
    foreach($this->result as $result){
     	?>  
     
<form action="" method="post" action="" id="Submit" enctype="multipart/form-data">

      
<!--   <div class="err1">
 		<label class="lblTxt" for="" style="color:green;">
 </div>-->
 
	
   <div class="form-group">
   
    <label for="" class="lblTxt">Contract Name</label>

     <input type="text" name="contract_name" id="contract_name" class="form-control CommonInputBox" placeholder="Contract Name" value="<?php echo $result['contract_name'];?>">


      
  </div>
  <div class="form-group">
    <label for="" class="lblTxt">Contract QTY</label>

     <input type="text" class="form-control CommonInputBox isnumber" placeholder="" name="contract_qty" id="contract_qty" value="<?php echo $result['contract_qty'];?>">


      
  </div>

  <div class="form-group">
    <label for="" class="lblTxt">Description</label>

     <input type="text" class="form-control CommonInputBox" placeholder="" name="desc" id="desc" value="<?php echo $result['description'];?>">


      
  </div>
    <div class="form-group">
    <label for="" class="lblTxt">Contract Description</label>

     <input type="text" class="form-control CommonInputBox" placeholder="" name="Contract_description" id="Contract_description" value="<?php echo $result['contract_descr'];?>">


      
  </div>
   <div class="form-group">
   
    <label for="" class="lblTxt">Total Rate(BTC)</label>
    
		<div>
    <input type="text" class="form-control CommonInputBox isnumber" placeholder="" name="total_price" id="total_price" value="<?php echo $result['total_price']; ?>">
		</div>

      
  </div>
  <div class="form-group">
   
    <label for="" class="lblTxt">Direct Sales Incentive</label>
    
		<div>
    <input type="text" class="form-control CommonInputBox isnumber" placeholder="" name="dsi" id="dsi" value="<?php echo $result['direct_earning']; ?>">
		</div>

      
  </div>
  <div class="form-group">
   
    <label for="" class="lblTxt">Contract Type</label>
    
		
    <!--<input type="text" class="form-control CommonInputBox" placeholder="" name="Contract_type" id="Contract_type" value="<?php echo $result['total_price']; ?>">BTC
		
		 --><select id="myclass"   class="form-control CommonInputBox">
	   
	  <?php   if(!empty($this->contracttype) && sizeof($this->contracttype)>0)
		{
	for($i=0;$i<sizeof($this->contracttype);$i++)
	{?>
		
	  	<option  name='contracttype' <?php if($this->contracttype[$i]['contracttype']==$result['contract_type'])echo 'selected="selected"';?> value="<?php echo $this->contracttype[$i]['contracttype']; ?>" ><?php echo $this->contracttype[$i]['contracttype'];?></option>
	  	
	  	
	  	 <?php }
	}?>
		</select>
		

      
  </div>
   <div class="form-group">
    <label for="" class="lblTxt">Status</label>

        <div class="col-lg-4 form-group" style="float:left;padding-left:5px;">
                                            <select class="form-control CommonInputBox"  name="status" id="status" style="	border: 1px solid !important;border-radius: 5px !important; width:292px;">
                                                <option value="1" <?php if($this->result['data']['status']==1){ echo 'selected';} ?>>Active</option>
                                                <option value="0" <?php if($this->result['data']['status']==0){ echo 'selected';} ?>>Inactive</option>
                                            </select>
                                        </div>


      
  </div>
  
    <input type="hidden"  value="<?php echo $result['contract_type']; ?>" name="con_type" class="form-control" id="con_type"/>
  	<input type="hidden" name="old_contract_name" class="form-control" id="old_contract_name" value="<?php echo $result['contract_name']; ?>" >
 	 <input type="hidden"  value="<?php echo $result['contract_type']; ?>" name="con_type" class="form-control" id="con_type"/>
    <input type="hidden" value="<?php echo $result['contract_qty']; ?>" name="old_contract_qty" class="form-control" id="old_contract_qty"/>
    <input type="hidden"  value="<?php echo $result['total_price']; ?>" name="old_total_price" class="form-control" id="old_total_price"/>
    <input type="hidden" value="<?php echo $result['description']; ?>" name="old_desc" class="form-control" id="old_desc"/>
     <input type="hidden"  value="<?php echo $result['contract_id']; ?>" name="contractid" class="form-control" id="contractid"/>
     
    <br>
    <div class="form">
    
  <button type="button" class="btn btn-default Commonbtn"  onclick="geteditdata()"name="submit" id="submit" value="">SUBMIT</button>
    <button type="reset" class="btn btn-default Commonbtn" id="RESET" name="RESET">RESET</button>
  
 </div>

  <?php $j++;}?>
  <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
</form>

  </div>
          </div>
         

      
   

     

        <div class="clearfix">
       
        <div class="col-lg-12">

 

<div class="clearfix">&nbsp;</div>


              

             
              
        </div>

      

     
<div class="clearfix">&nbsp;</div>

       

  
	 
       <!--   <div class="col-lg-6 col-lg-offset-3 col-xs-offset-1 center-text ">
           <ul class="pagination pagination-sm">
              <li><a href="#"><img src="images/leftarw.png" alt=""></a></li>
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#"><img src="images/rightarw.png" alt=""></a> </li> 
      </ul>
    </div>-->
       
       <!-- pagination code -->
 <?php  // echo "<div align='center'>".$this->pagination($this->pagination_config)."</div>";
				//echo "<div>&nbsp;</div>";?>
				
  
   				<!--  <div class='grid-row2'>
			<div align='center' style="width:95%;font-weight:bold;">No Records Found</div>
		</div>-->
   
      
    </div>
         
         
          
          </div>
      
            <!-- /.row -->
            
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



    </div>
    
     <script type="text/javascript">



	



		function geteditdata(){

var contrctname=$("#contract_name").val();
var Contrctqty=$("#contract_qty").val();
var Desc=$("#desc").val();

var contrctdesc=$("#Contract_description").val();


var rte=$("#total_price").val();
var cID = document.getElementById("myclass"); 
var cVal = cID.options[cID.selectedIndex].value; 
var cid=$("#contractid").val();
var tkn=$("#token").val();
var dsi=$("#dsi").val();
var status=$("#status").val();


		 

		    	if((contrctname).trim()==''){
					$(".errortext").html('<label for="" class="lblTxt" style="color:red;">Please enter Contract Name.</label>');
					return false;
				}	

		    	//if(!namefunc(contrctname)){
				//	$(".errortext").html('<label for="" class="lblTxt" style="color:red;">Contract name should be Characters only.</label>');
				//	return false;
				//}
		    	if((Contrctqty).trim()==''){
					$(".errortext").html('<label for="" class="lblTxt" style="color:red;">Please enter Contrct QTY.</label>');
					return false;
				}		
		    	/*if(isNaN(Contrctqty)){
					$(".errortext").html('<label for="" class="lblTxt" style="color:red;"> Contrct QTY should be numbers only.</label>');
					return false;
				}*/
		    	if((Desc).trim()==''){
					$(".errortext").html('<label for="" class="lblTxt" style="color:red;">Please enter Description.</label>');
					return false;
				}	
		    	if((contrctdesc).trim()==''){
					$(".errortext").html('<label for="" class="lblTxt" style="color:red;">Please enter  Contract Description.</label>');
					return false;
				}	
		    	if((rte).trim()==''){
					$(".errortext").html('<label for="" class="lblTxt" style="color:red;">Please enter Total Rate.</label>');
					return false;
				}	
		    /*	if(isNaN(rte)){
					$(".errortext").html('<label for="" class="lblTxt" style="color:red;"> Total Rate should be Numbers only.</label>');
					return false;
				}*/
		    	if((dsi).trim()==''){
					$(".errortext").html('<label for="" class="lblTxt" style="color:red;">Please enter Direct Sales Incentive.</label>');
					return false;
				}
		    	/*if(isNaN(dsi)){
					$(".errortext").html('<label for="" class="lblTxt" style="color:red;">Direct Sales Incentive should be Numbers only.</label>');
					return false;
				}*/
		    		
						
		    	else
		    	{
			    	
		var dataString ='contrctname='+contrctname+'&Contrctqty='+Contrctqty+'&Desc='+Desc+'&rte='+rte+'&cVal='+cVal+'&cid='+cid+'&tkn='+tkn+'&contrctdesc='+contrctdesc+'&dsi='+dsi+'&status='+status;
	
			$.ajax({
	
					url:"<?php echo BASEPATH;?>/Editcontract/contractedit", 
					type: "POST",    
				    data: dataString,
				
						success:function(response)
						{
						 var data=JSON.parse(response);
					
						 if(data['success']!='')
						 {
							/*$(".err1").css("display","block");
								document.getElementById("err1").innerHTML="Data inserted successfully.";
								$('.err1').css('color','green');*/
						        $(".errortext").html('<label class="lblTxt" for="" style="color:green;">'+data['success']+'</label>');
								window.location = "<?php echo BASEPATH;?>/Allcontract";
						 }
						 else
						 {
							 $(".errortext").html('<label class="lblTxt" for="" style="color:red;">'+data['failure']+'</label>');
						 }
		
								
						}
								
							
						 });


			    	return true;
		    	}

		    
		}  
		function namefunc(name)

		{
			var pattern12 = new RegExp(/^[a-zA-Z ]+$/);
			return pattern12.test(name);
		}


		function phone_number(MobileNumber)
		{
		    var patte1 = new RegExp(/^[0-9]+$/);
			return patte1.test(MobileNumber);
		}			
		
    </script>
