<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>


<div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12 offset-1">
                    <h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
              <ol class="breadcrumb">
                  <li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a> > </li>
                  <li>CMS Settings > </li>
                  <li>Training</li>
  
            </ol>

          <div class="clearfix">&nbsp;</div>


        <div class="col-lg-12 ">
      
            <div class="clearfix lightgraybg">

                <div class="bs-example table-responsive" data-example-id="bordered-table"> 

             
                   <table id="data-table-simple"  class="table table-bordered innertbl display" cellspacing="0"> 
                     <thead>
                    <tr>
                       <th class="sortdesc">Sr.<br>No </th>
                        <th class="sortboth">Title</th> 
                        <th class="sortboth">Created Date</th>
                         <th class="sortboth">Status</th> 
                         <th class="sortboth">Action</th> 
                         
                          
                           
                     </tr> 
                 </thead>
                  <tbody> 
                  
                    <?php 
        		$j=1;
       				 foreach($this->result as $result){?>
                   <!--   <tr>
                     <td scope="row">1</td> 
                     <td>&nbsp;</td>
                      <td>No data available in table</td> 
                      <td>&nbsp;</td>-->
                    
                     <td scope="row"><?php echo $j;?></td> 
                     <td><?php echo $result['title'];?></td>
                      <td><?php echo $result['created_on'];?></td> 
                      <td><?php echo $result['status'];?></td>
                      <td>
                      <form method="post" action="<?php echo BASEPATH; ?>/Editraining" name="form" id="form<?php  echo $result['id'];?>">
			
			
						<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
			
						<input type="hidden" value="<?php echo $result['id'];?>" id="<?php echo $result['id'];?>" name="uid">
			
						<a href="#" onclick="document.getElementById('form<?php echo $result['id']?>').submit()">Edit</a>
			
					</form>
					</td>
                      
                      
					 <!--   <td><a href="<?php echo BASEPATH; ?>/Editraining?id=<?php echo $result['id'];?>">Edit</a></td>-->
                     
                  </tr> 

               

                

                  

               
             
             	<?php $j++;} ?>
             
                 </tbody>
                  </table> 
              </div>

        </div>
	
    </div>

       

    
       <!--  <div class="col-lg-6 col-lg-offset-3 col-xs-offset-1 center-text ">
           <ul class="pagination pagination-sm">
              <li><a href="#"><img src="images/leftarw.png" alt=""></a></li>
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#"><img src="images/rightarw.png" alt=""></a> </li> 
      </ul>
    </div>-->
    <?php  // echo "<div align='center'>".$this->pagination($this->pagination_config)."</div>";
				//echo "<div>&nbsp;</div>";?>
				
     
        
      
    </div>
         
      
    

   

 
     




               
             
                
          
          </div>
 <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">     
            <!-- /.row -->
            
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



    </div>
