<?php 
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); $misc_obj->generateToken();
?>
<style>
.form-group {
	width: 300px;
}
.clearfix {
  margin-top:-7px;
}
.cls{
	margin-top:-46px;
}

</style>

<div id="innerpage-wrapper">
<div class="row lightgraybg">
<div class="col-lg-12">
<h1 class="page-header gain-bit-Titletxt"></h1>
</div>
<!-- /.col-lg-12 --></div>
<!-- /.row -->
<div class="row">

<ol class="breadcrumb">
    <li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a> > </li>
	<li>Admin Payout</li>

</ol>




<div class="col-lg-12">



<div class="clearfix">&nbsp;</div>

<div class="panel panel-primary buynowbox col-lg-12">

<div class="panel-heading buynowbox Titleheading faqtitlebg">Upload CSV
File for user Payouts</div>

<div class="panel-body revenuebg">
<form action="<?php echo BASEPATH; ?>/Adminpayout" method="post" enctype="multipart/form-data">

<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
<?php $authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
if(!empty($authUserNamespace->msg) && $authUserNamespace->msg!='')
{
?>
   <div class="form-group">
    <label for="" class="lblTxt" style="color:green;"><?php echo $authUserNamespace->msg; ?></label>
 
  </div>
 <?php $authUserNamespace->msg=""; }
 if(!empty($authUserNamespace->message) && $authUserNamespace->message!=''){?>
  <div class="form-group">
    <label for="" class="lblTxt" style="color:red;"><?php echo $authUserNamespace->message; ?></label>
 
  </div>
 
 
<?php $authUserNamespace->message=""; }?>

<div class="form-group"><label for="inputCName" class="lblTxt">Upload
CSV File for Payout :</label> <input type="file" name="file" id="file" placeholder="upload file"></div>



<input type="submit" class="btn btn-default Commonbtn"
	id="submit_payout" name="submit_payout" value="SUBMIT"/>


</form>
</div>
</div>

<!-- Disable Kit Generation and Fund Transfer -->
<div class="panel panel-primary buynowbox col-lg-12">

<div class="panel-heading buynowbox Titleheading faqtitlebg">Disable Kit Generation and Fund Transfer</div>

<div class="panel-body revenuebg">
<form action="" method="post" enctype="multipart/form-data">



<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
<div class="form-group"> 						
<input type="radio" name = "radio" id = "enable_radio" class = "with-gap" <?php if(!empty($this->KitFundMode) && ($this->KitFundMode == 1)) echo "checked"; ?> value = "1"/>
<label for = "enable_radio">Enable</label>
<input type="radio" id = "disable_radio"  name = "radio" class = "with-gap" <?php if(!empty($this->KitFundMode) && ($this->KitFundMode == 2)) echo "checked"; ?> value = "2"/>
<label for = "disable_radio">Disable</label>
<br/><br/><br/>

	</div>

<div class="cls">
<input type = "submit" class="btn btn-default Commonbtn" name="dis_submit" id="dis_submit" value = "SUBMIT"/>
</div>

</form>
</div>
</div>

</div>

<!-- /.row --> <!-- /.row --></div>
<!-- /#page-wrapper --></div>
