<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>

<script>
function showRSS(str) {
  if (str.length==0) {
    document.getElementById("rssOutput").innerHTML="";
    return;
  }
  if (window.XMLHttpRequest) {
    // code for IE7+, Firefox, Chrome, Opera, Safari
    xmlhttp=new XMLHttpRequest();
  } else {  // code for IE6, IE5
    xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
  }
  xmlhttp.onreadystatechange=function() {
    if (this.readyState==4 && this.status==200) {
      document.getElementById("rssOutput").innerHTML=this.responseText;
    }
  }
  xmlhttp.open("GET","application/layouts/scripts/getrss.php?q="+str,true);
  xmlhttp.send();
}
	
jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.location = $(this).data("href");
    });
    $('#data-table-simple').DataTable( {
        order: [[ 0, 'desc' ]]
    } );	
});	
	
/*
window.onload = function() {
  document.getElementById('data-table-simple_length').style.display = 'none';
  document.getElementById('data-table-simple_filter').style.display = 'none';
};
*/	
</script>

<style>
@media only screen and (max-width: 768px) {
    #data-table-simple_length {
        display: none;
    }
    #data-table-simple_filter {
        display: none;
    }	
}	
	id
</style>	
  <div class="content">

	<div class="page-title-group">
		<h4 class="page-title">Latest Updates</h4>
			<h5 class="text-muted page-title-alt">Updates</h5>
	</div>
	<div class="cb-page-content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="card-box">
				<!--		<div class="card-box-head  border-b m-t-0">
							<h4 class="header-title"><b>Latest Updates</b></h4>
						</div> -->						
						<div class="card-box-content form-compoenent">
							<div class="bs-example table-responsive">
								<table id="data-table-simple"  class="table table-bordered innertbl display" cellspacing="0">
									<thead>
									  <tr>					
													 <th style="display:none;">id</th>
													 <th style="display:none;">Headline</th>
									  </tr>
									</thead>
									<tbody>							   
						<?php 

								//	$xml_url=("https://bitcoinmagazine.com/feed/");
						//	$xml=("https://cointelegraph.com/rss");
								//	echo $misc_obj->fetchRSSFeed($xml_url);
								   $newsData = $this->result['data'];
								   foreach($newsData as $news){
									$url = preg_replace("/[^0-9a-zA-Z ]/", "", $news['Headline']);
									$url = BASEPATH.'/Latestnews/detail/'.$news['id'].'/'.str_replace(" ", "-", strtolower($url));
									$date = date('d-m-Y h:i A', strtotime($news['Created_on']));   
						?>
							   <tr class='clickable-row' data-href='<?php echo $url; ?>'>
								   <td style="display:none;"><?php echo $news['id'];?></td>
									<td style="height:50px;text-align:left;">	
										  <span style="font-size:16px;"><?php echo $news['Headline']; ?></span>
										 <br/> <span style="font-size:11px;">Published On:&nbsp;<?php echo $date; ?></span>
										   <a href = " <?php echo $url; ?>">
												<span class="fa fa-angle-right fa-2x cb-nav-arrow" style="float:right;margin-right:30px;margin-top:-15px;"></span>
										   </a>   
								   </td>
								</tr>



						<?php } ?>	
								<tbody>
								</table>
							</div>
						</div>	
							<div id="rssOutput" class="col-lg-12"><br></div>
							<div id="rssOutput" class="col-lg-12">
						<?php 
									//	$xml_url=("http://www.newsbtc.com/feed/");
									//	echo $misc_obj->fetchRSSFeed($xml_url);
						?>

							</div>
							<div id="rssOutput" class="col-lg-12"><br></div>
								<!-- /.row -->

								<!-- /.row -->
							</div>
							<!-- /#page-wrapper -->

						</div>
						<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
						<div class="clearfix"></div>
						<br>
						<br>
					</div>
				</div>
			</div>
		</div>
					
					
					
					
					
					