<?php
$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); $misc_obj->generateToken();
?>
    <div id="wrapper" class="loginPadd">

      <div class="logincontanier lightgraybg ">

      <div class="panel-heading faqtitlebg text-center  text-uppercase loginTitleTxt brdright">
                        <a href="#">  Home </a>
                           
                        </div>
  <form class="paddAll" autocomplete="off">
  <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
					<div class="modal req-admin bg-popup" id="google-auth-verify" style="display:block;">
                        <div class="modal-dialog popup height-popup big-pop-center">
                      	  <div class="modal-content no-padding">
							<div class="bg-pop-header">
								<span class="text-pop-header">2 FACTOR AUTHENTICATION</span>
								<button	type="button" class="close"	data-dismiss="modal" aria-hidden="true"><i class="fa fa-close" style="color:#fff;"></i></button>
							</div>             
                                <div style="padding:25px;height:450px;overflow-y:auto;">
                                    <a href="javascript:void(0)"><img alt="" src="<?php echo BASEPATH; ?>/images/login-logo.png" class="img-responsive center-block"></a>
								    

                                    <div style="padding:20px;">
                                    <div class="alert alert-danger" id="err_div" style="display:none;padding:5px;"></div>
										
										<h5>Enter google authentication code</h5>										
                                        <input type="text" id="vcode" name="vcode" class="form-control">
                                    </div>
                                    <div style="text-align:center;">
                                    	<button type="button" value="SUBMIT" class="btn btn-primary btn-lg" onclick="verify();">SUBMIT</button>
									</div>
                                    <div class="row" style="margin-top:20px;">
                                        <div class="col-md-12"><p class=""  style="text-align:-webkit-center;">We recommend to use <a href="http://authy.com">Authy app</a> for backup and restore option, in case of 2FA device lost. <br/>Take screenshot or save QR Code image by right click on it for backup and restore option.</p></div>
                                        <div class="col-md-12">
										<div class="row">
                                          <div class="col-md-6 col-xs-12"><a href="https://itunes.apple.com/en/app/authy/id494168017?mt=8"><img alt="" src="<?php echo BASEPATH; ?>/images/g-store.png" class="img-responsive center-block" width="200" height="62"></a></div>
                                          <div class="col-md-6 col-xs-12"><a href="https://play.google.com/store/apps/details?id=com.authy.authy&hl=en"><img alt="" src="<?php echo BASEPATH; ?>/images/g-play.png" class="img-responsive center-block"  width="200" height="62"></a></div>
                                        </div>
										</div>
                                    </div>



                                </div>

                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div>

</form>

      <div class="panel-heading faqtitlebg text-center  text-uppercase loginTitleTxt brdright">
                         <a href="<?php echo BASEPATH; ?>/Login/register"> Register now! </a//>
                           
                        </div>
</div>
  



    </div>
    <script>
var username='<?php echo $authUserNamespace->uname; ?>';

function verify()
	{
			var code=$('#vcode').val();
		
					 $.ajax({
						url:"<?php echo BASEPATH; ?>/Deviceconfirmation/verifyauth",
						type: "POST",    
					    data: 'code='+code+"&username="+username,
						dataType: "json",
				  		success: function(response)
			      		{
							
							if(response.success=="success")
							{
								if(response.data && response.data == 'binary')
								{
									window.location.href=("<?php echo BASEPATH; ?>/Dashboard");
								}
								if(response.data && response.data == 'admin')
								{
									window.location.href=("<?php echo BASEPATH; ?>/Admindashboard");
								}
								if(response.data && response.data == 'subadmin')
								{
									window.location.href=("<?php echo BASEPATH; ?>/Admindashboard");
								}
								
								closePopup();
								
							}
							else
							{
								closePopup();
								$('#err_div').css("display","block");
								$('#err_div').empty();
								$('#err_div').append(response.failure);
								$('#err_div').css("color","red");
							}
						
			      			
			      		}
					});
	}
		function closePopup()
	{

		$('.modal ').removeClass('openpop');
	}

    </script>