<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>



<div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12 offset-1">
                    <h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
              <ol class="breadcrumb">
                  <li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a> > </li>
                  <li>Manage Navigation</li>
  
            </ol>

          <div class="clearfix">&nbsp;</div>


        <div class="col-lg-12 ">
      
            <div class="clearfix lightgraybg">

                <div class="bs-example table-responsive" data-example-id="bordered-table"> 

             
				  <table id="data-table-simple"  class="table table-bordered innertbl display">  
                     <thead>
                    <tr>
                       <th class="" style="width: 55px;">Sr. No. </th>
                        <th class="">Country</th> 
                        <th class="">Action</th>
                        
                          
                     </tr> 
                 </thead>
                  <tbody>  
                  
                    <?php 
        		$j=1;
       				 foreach($this->result as $result){?>
                   <!--   <tr>
                     <td scope="row">1</td> 
                     <td>&nbsp;</td>
                      <td>No data available in table</td> 
                      <td>&nbsp;</td>-->
                    
                     <td scope="row"><?php echo $j;?></td> 
                     <td scope="row"><?php echo $result['country'];?></td>
                     
                             
			  <td scope="row" style="display:block!important;cursor:pointer;">

			
			<form method="post" action="<?php echo BASEPATH; ?>/Menu" name="form" id="form<?php  echo $result['ccode']; ?>">
			
			
			<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
			
			<input type="hidden" value="<?php  echo $result['ccode']; ?>" id="country" name="country">
			
			<a href="#" onclick="document.getElementById('form<?php  echo $result['ccode']; ?>').submit()">Edit</a>
			
			</form></td>
                     
                      
                  </tr> 

               

                

                  

               
             
             	<?php $j++;} ?>
             
                 </tbody>
                  </table> 
              </div>

        </div>
	
    </div>

       

    
       <!--  <div class="col-lg-6 col-lg-offset-3 col-xs-offset-1 center-text ">
           <ul class="pagination pagination-sm">
              <li><a href="#"><img src="images/leftarw.png" alt=""></a></li>
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#"><img src="images/rightarw.png" alt=""></a> </li> 
      </ul>
    </div>-->
    <?php  // echo "<div align='center'>".$this->pagination($this->pagination_config)."</div>";
				//echo "<div>&nbsp;</div>";?>
				

        
      
    </div>
         
      
    

   

 
     




               
             
                
          
          </div>
  <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">    
            <!-- /.row -->
            
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



    </div>
	<script>
	function showlink(ccode)
	{
	window.location = "<?php echo BASEPATH; ?>/Menu?country="+ccode;
	}
	</script>
