<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<?php

$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); 

?>

<html>
<head>
<link rel='shortcut icon' href='<?php echo BASEPATH; ?>/images/favicon/favicon-32x32.png' type='image/x-icon' />

</head>
<style>
.error
{
color:red;
}
#preloader
{
 	float: right;
    display:none;
    margin-left: -33px;

}
</style>
<body class="revenubydaybg">
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
		<?php
		
		echo $this->headTitle("Gainbitcoin-Login");
		
		echo $this->headLink()->appendStylesheet(BASEPATH.'/css/bootstrap.css')
							 
						//	  ->appendStylesheet(BASEPATH.'/css/timeline.css')
						//	  ->appendStylesheet(BASEPATH.'/css/sb-admin-2.css')
						//	  ->appendStylesheet(BASEPATH.'/css/style.css')
							  ->appendStylesheet(BASEPATH.'/css/mystyle.css')
							  ->appendStylesheet(BASEPATH.'/assets/css/icons.css')
			
						//	  ->appendStylesheet(BASEPATH.'/css/custom-style.css')
			;
							
		
		echo $this->headScript()->appendFile(BASEPATH.'/js/jquery.min.js')
								->appendFile(BASEPATH.'/js/bootstrap.min.js')
								
							//	->appendFile(BASEPATH.'/js/raphael-min.js')
								
								->appendFile(BASEPATH.'/js/jquery.validate.min.js')
							//	->appendFile(BASEPATH.'/js/sb-admin-2.js')
								->appendFile(BASEPATH.'/js/aes.js')
								->appendFile(BASEPATH.'/js/aes-ctr.js')
								;

	?>
<?php echo $this->layout()->content; ?>

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-93894880-1', 'auto');
        ga('send', 'pageview');

    </script>

</body>

</html>
