<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<?php $authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); ?>

<html>
<head>
<style>
		html, body {
			height: auto !important;
		}
		.invalid{
		  color:red;
		}
		.error{
		  color:red;
		 display: block;
		}
		
		
		.close_pop{
			/* border: 3px solid #000;
			border-radius: 5px; */
			width: 26px;
		   /*  height: 26px;
			text-align: center;
			font-weight: bold;
			font-size: 20px;
			color: #fff; */
			/* margin-top: -21px;
			margin-left: 29px;
			margin-right: -22px; */
			float: right;
			/* z-index:99999; */
		}

.close_pop a{
	 color: #000;
	 border: 3px solid #000;
    border-radius: 5px;
	font-size:30px;
   }

.offer_pop{
	 background-color: #fff;
    /* border: 1px solid #000; 
    cursor: pointer;*/


	padding: 15px !important;
    width: 765px;
    z-index: 99999;
	top: 2%;
    left: 22%;
    position: relative;
	box-shadow:0px 0px 30px #000;
	border-radius:8px;
}

.popup{
	background-image: url(../res/images/popup-bg.png);
	display:none;
    width: 100%;
    /* height: 100%; */
    position: absolute;
    z-index: 9999;
    top: 0;
	left: 0%;
	
}
ul{
	list-style-type: disc !important;
	padding: 5px !important;
}
li{
	padding: 5px;
	list-style-type: disc !important;
}

		
		</style>
		
</head>

<body class="cyan login-layout"">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<?php
		
		echo $this->headTitle("Gainbitcoin-Login");
		
		echo $this->headLink()->appendStylesheet(BASEPATH.'/assets/css/font-awesome.min.css')
							  ->appendStylesheet("https://fonts.googleapis.com/css?family=Open+Sans:400,300")
							  ->appendStylesheet(BASEPATH.'/assets/css/ace.min.css')
							  ->appendStylesheet(BASEPATH.'/css/materialize.css')
							  ->appendStylesheet(BASEPATH.'/css/style.css')
							  ->appendStylesheet(BASEPATH.'/css/custom-style.css')
							  ->appendStylesheet(BASEPATH.'/css/page-center.css')
							  ->appendStylesheet(BASEPATH.'/css/prism.css')
							  ->appendStylesheet(BASEPATH.'/js/plugins/perfect-scrollbar/perfect-scrollbar.css')
							  ->appendStylesheet(BASEPATH.'/css/custom-style.css');
		
		echo $this->headScript()->appendFile(BASEPATH.'/js/crud.js')
								->appendFile(BASEPATH.'/js/jquery-1.11.2.min.js')
								->appendFile(BASEPATH.'/res/js/jquery.validate.min.js')
								->appendFile(BASEPATH.'/js/materialize.js')
								->appendFile(BASEPATH.'/js/prism.js')
								->appendFile(BASEPATH.'/js/plugins/perfect-scrollbar/perfect-scrollbar.min.js')
								->appendFile(BASEPATH.'/js/plugins.js');

	?>
<?php echo $this->layout()->content; ?>
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-93894880-1', 'auto');
    ga('send', 'pageview');

</script>

</body>

</html>