<!-- Overall Data Starts-->
				  
	<div class="row new-row">
        <div class="col-lg-3 offset-0">
            <div class="panel panel-default buynowbox">
                <div class="panel-heading faqtitlebg text-center  text-uppercase Title">
                    Total 
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body" style="height: 120px; background-color: #F2F2F2;">
                    <h1 class="text-center"><?php echo $this->overalldata['0']['total'];?></h1>
                </div>
                <!-- /.panel-body --></div>
            <!-- /.panel --></div>

		
		
        <div class="col-lg-3 offset-0">
            <div class="panel panel-default buynowbox">
                <div class="panel-heading faqtitlebg text-center  text-uppercase Title">
                    Open	 
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body" style="height: 120px; background-color: #F2F2F2;">
                    <h1 class="text-center"><?php echo $this->overalldata['0']['open_counts'];?></h1>
                </div>
                <!-- /.panel-body --></div>
            <!-- /.panel --></div>
		
        <div class="col-lg-3 offset-0">
            <div class="panel panel-default buynowbox">
                <div class="panel-heading faqtitlebg text-center  text-uppercase Title">
					Close
				</div>
                <!-- /.panel-heading -->
                <div class="panel-body" style="height: 120px; background-color: #F2F2F2;">
                    <h1 class="text-center"><?php echo $this->overalldata['0']['status_counts'];?></h1>
                </div>
                <!-- /.panel-body --></div>
            <!-- /.panel --></div>
        <div class="col-lg-3 offset-0">
            <div class="panel panel-default buynowbox">
                <div class="panel-heading faqtitlebg text-center  text-uppercase Title">
                    Pending
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body" style="height: 120px; background-color: #F2F2F2;">
                    <h1 class="text-center"><?php echo $this->overalldata['0']['replied_counts'];?></h1>
                </div>
                <!-- /.panel-body --></div>
            <!-- /.panel --></div>


    </div>		  
		  
<!-- Overall Data Ends -->
				  
<!-- Today Data Starts -->
	<div class="row new-row">
        <div class="col-lg-3 offset-0">
            <div class="panel panel-default buynowbox">
                <div class="panel-heading faqtitlebg text-center  text-uppercase Title">
                    Total Pending 
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body" style="height: 120px; background-color: #F2F2F2;">
                    <h1 class="text-center"><?php echo $this->todayReportData['0']['total'];?></h1>
                </div>
                <!-- /.panel-body --></div>
            <!-- /.panel --></div>

		
		
        <div class="col-lg-3 offset-0">
            <div class="panel panel-default buynowbox">
                <div class="panel-heading faqtitlebg text-center  text-uppercase Title">
                    Today Received	 
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body" style="height: 120px; background-color: #F2F2F2;">
                    <h1 class="text-center"><?php echo $this->todayReportData['0']['open_counts'];?></h1>
                </div>
                <!-- /.panel-body --></div>
            <!-- /.panel --></div>
		
        <div class="col-lg-3 offset-0">
            <div class="panel panel-default buynowbox">
                <div class="panel-heading faqtitlebg text-center  text-uppercase Title">
					Today Closed 	
				</div>
                <!-- /.panel-heading -->
                <div class="panel-body" style="height: 120px; background-color: #F2F2F2;">
                    <h1 class="text-center"><?php echo $this->todayReportData['0']['replied_counts'];?></h1>
                </div>
                <!-- /.panel-body --></div>
            <!-- /.panel --></div>

    </div>		  				  
				  
<!-- Today Data Ends -->				  
			  
<!-- Today Report Data Starts-->
			
<div class="row new-row">
        <div class="col-lg-3 offset-0">
            <div class="panel panel-default buynowbox">
                <div class="panel-heading faqtitlebg text-center  text-uppercase Title">
                    Total 
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body" style="height: 120px; background-color: #F2F2F2;">
                    <h1 class="text-center"><?php echo $this->todaydata['0']['total'];?></h1>
                </div>
                <!-- /.panel-body --></div>
            <!-- /.panel --></div>

		
		
        <div class="col-lg-3 offset-0">
            <div class="panel panel-default buynowbox">
                <div class="panel-heading faqtitlebg text-center  text-uppercase Title">
                    Open	 
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body" style="height: 120px; background-color: #F2F2F2;">
                    <h1 class="text-center"><?php echo $this->todaydata['0']['open_counts'];?></h1>
                </div>
                <!-- /.panel-body --></div>
            <!-- /.panel --></div>
		
        <div class="col-lg-3 offset-0">
            <div class="panel panel-default buynowbox">
                <div class="panel-heading faqtitlebg text-center  text-uppercase Title">
					Response Sent 	
				</div>
                <!-- /.panel-heading -->
                <div class="panel-body" style="height: 120px; background-color: #F2F2F2;">
                    <h1 class="text-center"><?php echo $this->todaydata['0']['status_counts'];?></h1>
                </div>
                <!-- /.panel-body --></div>
            <!-- /.panel --></div>
        <div class="col-lg-3 offset-0">
            <div class="panel panel-default buynowbox">
                <div class="panel-heading faqtitlebg text-center  text-uppercase Title">
                    Response Awaited
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body" style="height: 120px; background-color: #F2F2F2;">
                    <h1 class="text-center"><?php echo $this->todaydata['0']['replied_counts'];?></h1>
                </div>
                <!-- /.panel-body --></div>
            <!-- /.panel --></div>


    </div>				  
				  
<!-- Today Report Data Ends-->			