<div id="wraper">
	<nav class="navbar navbar-default navbar-static-top headerbg" role="navigation">
	<div class="navbar-header">
	<button type="button" class="navbar-toggle"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button>
	<a class="navbar-brand" href="/Login"><img src="<?php echo BASEPATH; ?>/images/logo.png" alt=""></a></div>
	<!-- /.navbar-header -->

	<div class="mob-nav" style="height: 70px;">
	<div id="google_translate_element" class="google-translate" style="display:none;">
	</div>
	</div>
	<!-- /.navbar-top-links -->
	<!-- /.navbar-static-side --> </nav>
	<div style="text-align:center;">
		<h2>Invalid request</h2>
		<h3>Verification link is invalid or has expired.</h3>
	</div>
</div>		
		
		
		