<div id="wraper">
	<nav class="navbar navbar-default navbar-static-top headerbg" role="navigation">
	<div class="navbar-header">
	<button type="button" class="navbar-toggle"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button>
	<a class="navbar-brand" href="/Login"><img src="<?php echo BASEPATH; ?>/images/logo.png" alt=""></a></div>
	<!-- /.navbar-header -->

	<!-- /.navbar-top-links -->
	<!-- /.navbar-static-side --> </nav>
	<div class ="row">
		<div style="text-align:center;">

				  <h2>Invalid URL</h2>
				 <h3>That verification link is invalid, has expired or has been used.</h3>

		</div>
	</div>
</div>		
		
		
		