<?php
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>
<div id="innerpage-wrapper">
<div class="row lightgraybg">
<div class="col-lg-12 offset-1">
<h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
</div>
<!-- /.col-lg-12 --></div>
<!-- /.row -->
<div class="row">
<ol class="breadcrumb">
		<li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a>
		></li>
		<li>Kits ></li>
		<li>Kit Invoices</li>
</ol>
<div class="form-group" id = "msg">
<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	if(!empty($authUserNamespace->msg) && $authUserNamespace->msg!="")
	{
?>
<label for="" class="lblTxt" style="color: green; padding: 12px;"><?php echo $authUserNamespace->msg; ?></label>
<?php
	 $authUserNamespace->msg=""; }?> <?php
	if(!empty($this->msg) && $this->msg!="")
	{
?>
<label for="" class="lblTxt" style="color: red;"><?php echo $this->msg; ?></label>
<?php $authUserNamespace->msg=""; }?>
</div>
<div class="clearfix">&nbsp;</div>
<form method = "POST" style="padding:12px;">
	<label for="" class="lblTxt">Search</label>
	<input type="search" class="form-control CommonInputBox"  name="search" id = "search"   placeholder="search" style="width:250px;">
	<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">			
</form><br>
<div class="clearfix lightgraybg">
<div class="bs-example table-responsive" data-example-id="bordered-table">
<table style="width: 100%;" id="data-table-simple" class="table table-bordered innertbl display" cellspacing="0">
		<thead>
			<tr>
				<th class="sortdesc">SR. NO</th>
				<th class="sortboth">USERNAME</th>
				<th class="sortboth">KITS QTY</th>
				<th class="sortboth">INVOICE ID</th>
				<th class="sortboth">TOTAL AMOUNT</th>
				<th class="sortboth">AMOUNT PAID IN MCAP</th>
				
				<th class="sortboth">PAYMENT TX ID</th>
				<!--<th class="sortboth">PAYMENT MODE</th>-->
				<th class="sortboth">WALLET ADDRESS</th>
				<th class="sortboth">Created</th>
				<th class="sortboth">KITS TYPE</th>
				<th class="sortboth">COMMENTS</th>
				<th class="sortboth">STATUS</th>
				<th class="sortboth">ACTIONS</th>
				<th class="sortboth">LOCK CONTRACT</th>
			</tr>
		</thead>
		<tbody>
		<?php
			$DB = Zend_Db_Table_Abstract::getDefaultAdapter();
			$j=1;
			for($i=0;$i<sizeof($this->result);$i++){
				$invoiceId = $this->result[$i]['invoice_id'];
			
			//	$price_in_usd = $this->result[$i]['total_price'];
				$Kits_Lock = $this->result[$i]['locked'];
		?>
				<tr>
					<td scope="row"><?php echo $j; ?></td>
					<td><?php echo $this->result[$i]['username']; ?></td>
					<td><?php echo $this->result[$i]['kits_qty']; ?></td>
					<td><?php echo $this->result[$i]['invoice_id']; ?></td>
					<td><?php echo $this->result[$i]['contract_rate']; ?></td>
					<td><?php echo $this->result[$i]["amtPaid"];?></td>
				
					<td><?php echo $this->result[$i]["transactionid"];?></td>
		<!--		<td><?php //echo $this->result[$i]["payment_mode"];?></td> -->
					<td><?php echo $this->result[$i]["middleAddr"];?></td>
					<td><?php echo $this->result[$i]["created_on"];?></td>
					<td><?php echo $this->result[$i]["comments"]?$this->result[$i]["comments"]:$Kits_comment;?></td>
					<td><?php echo $this->result[$i]["comment"];?></td>
					<td><?php echo ($this->result[$i]["invoice_status"]=='1')?"Active":"Inactive";?></td>

					<td>
                      
                      <form method="post" action="<?php echo BASEPATH; ?>/Changeinvoicestatus/gb2kits" name="form" id="form<?php echo $this->result[$i]['invoice_id']; ?>">
						<?php if($this->result[$i]["invoice_status"]=='0'){ ?>
							<a href='#' onclick="changeStatus('<?php echo $this->result[$i]['invoice_id']; ?>')">Activate</a>
						<?php } else{ ""; ?> <?php }?>

						 <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
						 <input type="hidden" value="<?php echo $this->result[$i]['username']; ?>" id="user_name" name="user_name">

						 <input type="hidden" value="<?php echo $this->result[$i]['invoice_id']; ?>" id="invoiceid" name="invoiceid">
					 </form>
						
					<?php if($this->result[$i]["invoice_status"]=='0' && $this->result[$i]["contract_rate"]  > 0){ ?>
						<a href='#' onclick="changeGb2KitStatus('<?php echo $this->result[$i]['middleAddr']; ?>','<?php echo $this->result[$i]['contract_rate']; ?>')">Auto Active</a>
					<?php } ?>
						
					 </td> 
					<td>
						<div class="button">
							<a kit="link<?php echo $kit_number;?>" name="<?php echo  $Kits_Lock;?>" class="confirmation" href="#"
								onclick="changelockStatus('<?php echo $kit_number; ?>','<?php echo $Kits_Lock; ?>')"> 
								<?php if($Kits_Lock==0){
									  	echo "Lock";
									  }else if($Kits_Lock==1){
									  	echo "Unlock";
									  }else{
									  	echo "";
									  }
									  ?>
							</a>
						</div>
						</td>
						<!--  <td>
                        <a class="btn btn-default Commonbtn text-uppercase" href="#" role="button">CHECK MINING OUTPUTS</a>

                      </td>-->
				</tr>
				<?php $j++; } ?>
		</tbody>
</table>
         <ul class="pagination">
		 <?php 
		 $StartPage = !empty($_GET['page'])?$_GET['page']:1;
		 if(!empty($StartPage))
		 {
		 	$StartPage=$_GET['page'];
		 }
		 else 
		 {
		 	$StartPage=1;
		 }
		 if($this->pages <= 5){
			  $StartPage = 1;
		 }else if(!empty($_GET['page']) && $_GET['page'] < $this->pages-6){
			 // $pageDiff = $pages - $_GET['page'];
			// $StartPage = $pages - $pageDiff;
			 $StartPage = $_GET['page'];
		 }else if(!empty($_GET['page']) && $_GET['page'] >= $this->pages-6){
			 $StartPage = $this->pages - 5;
		 }
			
		 if($this->pages > 5){
			 $limitPage = $StartPage + 4;
		 }else{
			 $limitPage = $this->pages;
		 }
		 
			
		 if(!empty($_GET['page']) && $_GET['page'] > 1){
		 
		 ?>
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Gb2kitinvoice?page=1"></a></li>
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Gb2kitinvoice?page=<?php echo $_GET['page']-1; ?>"><i class="mdi-navigation-chevron-left"></i></a></li>
			 <?php 
				}
			 ?>
			
			<?php 
			
			for($j=$StartPage;$j<=$limitPage;$j++){
                    ?>
			<li class="active"><a href="<?php echo BASEPATH;?>/Gb2kitinvoice?page=<?php echo $j; ?>"><?php echo $j; ?></a></li>
			<?php }
			
			 if( $_GET['page'] < $this->pages-1){
				 
                    ?>
			
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Gb2kitinvoice?page=<?php echo $_GET['page']+1; ?>"><i class="mdi-navigation-chevron-right"></i></a></li>
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Gb2kitinvoice?page=<?php echo $this->pages-1; ?>"></a></li>
			<?php }
			
                    ?>
		 </ul>
</div>
</div>

<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
	
<!-- /.row -->
<!-- /.row -->
</div>
<!-- /#page-wrapper -->
</div>
<script>
    
   //function changeStatus(invoiceid,user_name)
   // {
        
  //      window.location = "<?php echo BASEPATH;?>/Changeinvoicestatus?invoiceid="+invoiceid+"&user_name="+user_name;
   
 //  }

    function changelockStatus(kitno,lock)
    {
       
        window.location = "<?php echo BASEPATH;?>/Changelockstatus?kitno="+kitno+"&lock="+lock;
        
        
    }

  function changeStatus(invoiceid)
     {
        
       // window.location = "<?php echo BASEPATH;?>/Changeinvoicestatus?invoiceid="+invoiceid+"&user_name="+user_name;
	   document.getElementById('form'+invoiceid).submit();
	    
   }
    
	
	function changeGb2KitStatus(address, amount){
		    $.ajax({
            url: "<?php echo BASEPATH; ?>/Changeinvoicestatus/updategb2status",
            type: 'POST',
            data: {address: address, amount: amount},
            success: function (data) {
			//	alert(data);
			//	var data=	JSON.parse(response);
                if (data == "success") {
				
					if($("#msg").length<=0){
                    	$("#msg").append("<label style = 'display:block;color:green; margin:20px;'>Activated Successfully<label>");
					}else{
						$("#msg").html("<label style = 'display:block;color:green; margin:20px;'>Activated Successfully<label>");
					}
                }else{
					if($("#msg").length<=0){
                    	$("#msg").append("<label style = 'display:block;color:red; margin:20px;'>Not Activated<label>");
					}else{
						$("#msg").html("<label style = 'display:block;color:red; margin:20px;'>Not Activated<label>");
					}
				}
            }

        });
	}
    
</script>




