<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>

<div class="modal req-admin" id="cat_alt">
       <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"  onclick="closealt();">
                                    <i class="is close-btn"></i></button>
                                </div>
                                <div class="modal-body g-auth-body" id="mainc_container">
                                 
            
                                </div>

                            </div><!-- /.modal-content -->
       </div><!-- /.modal-dialog -->
</div>
                    
<div id="innerpage-wrapper">
<div class="row lightgraybg">
<div class="col-lg-12 offset-1">
<h1 class="page-header gain-bit-Titletxt innpercontentPad">KYC Listing</h1>
</div>
<!-- /.col-lg-12 --></div>
<!-- /.row -->

<div class="clearfix">&nbsp;</div>
<div class="col-lg-12 ">
<div class="clearfix lightgraybg">
<div
	class="bs-example table-responsive"
	data-example-id="bordered-table"
>
<table
	id="data-table-simple"
	class="table table-bordered innertbl display"
	cellspacing="0"
>
	<thead>
		<tr>
			<th class="sortdesc">Sr. No</th>
			<th class="sortboth">username</th>
			<th class="sortboth">Id</th>
		</tr>
	</thead>
	<tbody>
	<?php $j=1;
	foreach($this->result as $result){
		?>
		<tr>
			<td scope="row"><?php echo $j;?></td>
			<td><?php echo $result['username']; ?></td>
			<td style="cursor:pointer;" onclick="showid('<?php echo $result['username']; ?>')"><?php echo '<img  height="80" width="80" src="data:image/jpeg;base64,'.base64_encode( $result['id_image'] ).'"/>';  ?></td>
		</tr>
		<?php $j++;}  ?>
	</tbody>
</table>
</div>
</div>
</div>
<!--   <div class="col-lg-6 col-lg-offset-3 col-xs-offset-1 center-text ">
           <ul class="pagination pagination-sm">
              <li><a href="#"><img src="images/leftarw.png" alt=""></a></li>
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#"><img src="images/rightarw.png" alt=""></a> </li> 
      </ul>
    </div>--> <?php  // echo "<div align='center'>".$this->pagination($this->pagination_config)."</div>";
		//	echo "<div>&nbsp;</div>";?> <!--  <div class='grid-row2'>
			<div align='center' style="width:95%;font-weight:bold;">No Records Found</div>
		</div>-->
</div>
<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
<!-- /.row -->
<!-- /.row -->
</div>
<!-- /#page-wrapper -->
</div>

<script>
function showid(username)
{
	 $.ajax({
			url:"<?php echo BASEPATH; ?>/List/getcontent",
			type: "POST",    
		    data: 'username='+username,
	  		success: function(response)
   			{
				if(response!='failed')
				{
					$('#mainc_container').empty();
					$('#mainc_container').append(response);
					$('#cat_alt').addClass('openpop');
				}
   			}
	 });
}
function closealt()
{
	$('#cat_alt').removeClass('openpop');
}
</script>
