 <?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>
 
 
 
 <style>
	 .form-group {
	    width: 300px;
	}

 </style>

<div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12">
                    <h1 class="page-header gain-bit-Titletxt"></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
            
              <ol class="breadcrumb">
                  <li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a> > </li>
                  <li >Send Notification</li>
  
            </ol>
           

         

         <div class="col-lg-12">
         
         

<div class="clearfix">&nbsp;</div>

           <div class="panel panel-primary buynowbox col-lg-12">

              <div class="panel-heading buynowbox Titleheading faqtitlebg">
             Send Notification
              </div>

              <div class="panel-body revenuebg">
          <form  method="post" action="<?php echo BASEPATH; ?>/Sendnotification" id="send_notification">
		<div class="form-group err1" style="width:100%;margin-bottom: 0px;">
		<label for="" class="lblTxt" style="color:red;"></label>
		</div>
<div id="msg1">
<?php 

if(!empty($this->msg) && $this->msg!='')
{
	
?>
  
    <?php echo $this->msg; ?>
 
  
 <?php } ?>
 </div>
 <div id="msg2">
 <?php if(!empty($authUserNamespace->errormsg) && $authUserNamespace->errormsg!=""){?>
     <label for="" class="lblTxt error" style="color:red;"><?php echo $authUserNamespace->errormsg; ?></label>
 
 <?php $authUserNamespace->errormsg="";}?>
</div>
   <div class="form-group">
    <label for="inputCName" class="lblTxt">Enter Text</label>

     <textarea  rows="4" cols="50" type="text" placeholder="Enter Text" name="text" id="text" class="form-control CommonInputBox" value="<?php ?>"></textarea>


      
  </div>

 <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">   
  
    
  <button type="submit" name="send_notification" class="btn btn-default Commonbtn" onclick="return validateForm()">SUBMIT</button>

  
</form>
  </div>
          </div>



         </div>

            <!-- /.row -->
            
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    
 <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">   
   
   <script>
   function validateForm(){

	   $('#msg1').empty();
       $('#msg2').empty();
  	 var text=$("#text").val();
       
		

		if((text).trim()==''){
			$(".success").hide();
			$(".err1").html('<label for="" class="lblTxt" style="color:red;">Please enter Notification Text.</label>');
			return false;
		}
		else{
				return true;
		}
		}
   </script>