<?php
$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
$misc_obj = new Gbc_Model_Custom_Miscellaneous();
$misc_obj->generateToken();
?>

<style>
.clearfix {
	margin-top: -1px;
}

.form-group {
	background: #D3D3D3;
	padding-left: 9px;
	margin-left: 2%;
	width: 252px;
	height: 34px;
}
</style>
<div id="innerpage-wrapper">
<div class="row lightgraybg">
<div class="col-lg-12 offset-1">
<h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
</div>
<!-- /.col-lg-12 --></div>
<!-- /.row -->
<div class="row">
<ol class="breadcrumb">
	<li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a>
	></li>
	<li>Setting ></li>
	<li class="active"><a href="<?php echo BASEPATH?>/Subadmin">Sub Admin
	User</a> ></li>
	<li>Set Permission</li>

</ol>









<div class="clearfix">

<div class="col-lg-12">



<div class="clearfix">&nbsp;</div>




</div>




<div class="clearfix">&nbsp;</div>

<div class="col-lg-12 "><?php if(!empty($this->firstname) && $this->firstname!="") {?>
<span style="font-weight: bold;">User Name</span><input name="user_name"
	id="user_name" value="<?php echo $this->firstname; ?>" type="textbox"
	class="form-group CommonInputBox" readonly> <?php }?>
<div class="clearfix lightgraybg">

<div class="bs-example table-responsive"
	data-example-id="bordered-table">


<table id="data-table-simple"
	class="table table-bordered innertbl display">
	<thead>
		<tr>
			<th class="sortdesc">Sr. No.</th>
			<th class="sortboth">Modules Name</th>
			<th class="sortboth">Submodules</th>
			<th class="sortboth">Add</th>
			<th class="sortboth">Edit</th>
			<th class="sortboth">View</th>
			<th class="sortboth">Delete</th>
		</tr>
	</thead>
	<tbody>
	<?php
	$Gbc_Model_Custom_func_obj=new Gbc_Model_Custom_CommonFunc();
	$i=1;
	//	echo $this->row;exit;
	foreach($this->result as $module)
	{
		$user_id=$_POST['setpermission_id'];
		if(!empty($module["id"])){ $module_id=$module["id"];} else{ $module_id=$module["pid"];}
		$get_access=$Gbc_Model_Custom_func_obj->GetAccessRightByUserId($module_id,$user_id);
		?>
		<tr>
			<td class="sortdesc"><?php echo $i; ?></td>
			<td class="sortboth"><?php echo isset($module["module_name"]) ? $module["module_name"]:"";?></td>
			<td class="sortboth"><?php echo isset($module["subname"]) ? "".$module["subname"]:"";?></td>
			<td class="sortboth"><input type="checkbox" name="add"
				id="add<?php echo $i;?>" onchange="change_per(this,'add');"
				value="<?php if(!empty($module["id"])){ echo $module["id"];} else{ echo $module["pid"];}?>"
				<?php if($get_access->add==1){ echo "checked=checked"; }?> /> <label
				for="add<?php echo $i;?>"><label></td>
			<td class="sortboth"><input type="checkbox" name="edit"
				id="edit<?php echo $i;?>" onchange="change_per(this,'edit');"
				value="<?php if(!empty($module["id"])){ echo $module["id"];} else{ echo $module["pid"];}?>"
				<?php if($get_access->edit==1){ echo "checked=checked"; }?> /><label
				for="edit<?php echo $i;?>"><label></td>
			<td class="sortboth"><input type="checkbox" name="view"
				id="view<?php echo $i;?>" onchange="change_per(this,'view');"
				value="<?php if(!empty($module["id"])){ echo $module["id"];} else{ echo $module["pid"];}?>"
				<?php if($get_access->view==1){ echo "checked=checked"; }?> /><label
				for="view<?php echo $i;?>"><label></td>
			<td class="sortboth"><input type="checkbox" name="delete"
				id="delete<?php echo $i;?>" onchange="change_per(this,'delete');"
				value="<?php if(!empty($module["id"])){ echo $module["id"];} else{ echo $module["pid"];}?>"
				<?php if($get_access->delete==1){ echo "checked=checked"; }?> /><label
				for="delete<?php echo $i;?>"><label></td>

		</tr>

		<?php
		$i++; }
		?>






	</tbody>
</table>
<div class="clearfix">&nbsp;</div>
</div>

</div>

</div>








</div>
















</div>

<!-- /.row --> <!-- /.row --></div>

<input
	type="hidden" value="<?php echo $authUserNamespace->token;?>"
	id="token" name="token">
<script>
function change_per(obj,mode)
 {

  var check_val=0;
  var module_id=obj.value;
  var token = $('#token').val();
  if(obj.checked)
  {
   check_val=1;
  }
  else
  {
   check_val=0;
  }
  
  $.ajax({
   url: "<?php echo BASEPATH; ?>/Setpermission/changeaccessright" ,
   data:{change_val:check_val,user_type_id:<?php echo $_POST['setpermission_id']; ?>,module_id:module_id,mode:mode,token:token},
   type:'post',
   success:function(res){
	   var data=JSON.parse(res);
  		
		 if(data['success']=='success')
		   { 
				alert("Changed successfully");
		   }
		 else if(data['failure']=='failure')
		   { 
				alert("Invalid Request Found.");
		   }
	       else{
	    	   alert("Error while changing! Please try again.");
	       }
	
   }
  
  });

 }
 </script>
