<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); $misc_obj->generateToken();
	
	//print_r($this->user_info);exit;
?>

<script>
 
var isebable='<?php echo $this->userInfo['data']['authentication_type']; ?>';

function preCheck()
{
	if(isebable && isebable=='2')
	{
		$('#google-auth-verify ').addClass('openpop');
	}
	else
	{
		updateProfile();
	}
}
function closeprofile ()
{
	$('#profileid').removeClass('openpop');
	 
}

 function updateProfile()
 {
	 //alert('Here');
	$('#preloaderId').show();
	var flag=0;
	$('#vcode').val('');
	$('#err_div_auth').empty();
	var name=$('#name').val();
	var token = $('#token').val();
	var contact_phone=$('#contact_phone').val(); 
	var authenticationtype="<?php echo $this->userInfo['data']['authentication_type'];?>"
	if(!name || name=='' )
	{
		$("#err_div").css("display", "block");
		document.getElementById("err_div").innerHTML="";
		document.getElementById("err_div").innerHTML="Please provide name.";
		$('#err_div').css('color','red');
		flag ==1;
		$('#preloaderId').hide();
		return false;
	}
		
	var email_address=$('#email_address').val();
	if(email_address!='')
	{
	    var atpos = email_address.indexOf("@");
	    var dotpos = email_address.lastIndexOf(".");
	    if(atpos<1 || dotpos<atpos+2 || dotpos+2>=email_address.length){
	    	$("#err_div").css("display", "block");
			document.getElementById("err_div").innerHTML="";
			document.getElementById("err_div").innerHTML="Please provide valid email.";
			$('#err_div').css('color','red');
			flag ==1;
			$('#preloaderId').hide();
			return false;
	    }
	    
	}else{
		$("#err_div").css("display", "block");
		document.getElementById("err_div").innerHTML="";
		document.getElementById("err_div").innerHTML="Please provide email.";
		$('#err_div').css('color','red');
		flag ==1;
		$('#preloaderId').hide();
		return false;
	}
     if(!contact_phone || contact_phone=='' )
	{
		$("#err_div").css("display", "block");
		document.getElementById("err_div").innerHTML="";
		document.getElementById("err_div").innerHTML="Please provide Contact No.";
		$('#err_div').css('color','red');
		flag ==1;
		$('#preloaderId').hide();
		return false;
	}
     if(isNaN(contact_phone)){
     $("#err_div").css("display", "block");
		document.getElementById("err_div").innerHTML="";
		document.getElementById("err_div").innerHTML="Please provide valid number only.";
		$('#err_div').css('color','red');
		flag ==1;
		$('#preloaderId').hide();
		return false;
      }
	/*if(!contfunc(contact_phone))
	{
	
		$("#err_div").css("display", "block");
		document.getElementById("err_div").innerHTML="";
		document.getElementById("err_div").innerHTML="Please enter valid Contact No.";
		$('#err_div').css('display','block');
		$('#err_div').css('color','red');
		flag ==1;
		$('#preloader').hide();
		return false;
	}*/
	
	var contact_phone=$('#contact_phone').val(); 
	var country=$('#int_ph option:selected').text();
	
	
	var fuData=$('#fileChooser').val();	
	 if(fuData != '') {
		//alert("inside");
		var extdata=$('#fileChooser').val();
		//alert(extdata);
		var Extension = extdata.substring(extdata.lastIndexOf('.') + 1).toLowerCase();
		//alert(Extension);;
	    if (Extension == "gif" || Extension == "png" || Extension == "jpeg" || Extension == "jpg") {
	    
	            if (typeof($("#fileChooser")[0].files) != "undefined") {
					//alert("size");
					var size = parseFloat($("#fileChooser")[0].files[0].size / 1024).toFixed(2);
	                //alert(size + " KB.");
	               	
	                if(size > 2048.00){
		                //alert("size21");
	                	$("#err_div").css("display", "block");
	            		document.getElementById("err_div").innerHTML="";
	            		document.getElementById("err_div").innerHTML="Maximum file size exceeds";
						$('#err_div').addClass('alert');
						$('#err_div').addClass('alert-danger');
	            		flag ==1;
	            		$('#preloaderId').hide();
	            		return false;	                    
	                }else{
	                    var reader = new FileReader();
	                    //alert("else part"+reader);	             
	                    reader.onload = function (e) {
	    	                $('.profile-pic').attr('src', e.target.result);
	    	            }
	    	            reader.readAsDataURL($("#fileChooser")[0].files[0]);
	    	            $('#preloaderId').hide();
	                }
    	            $('#preloaderId').hide();
	                
	            }
	            $('#preloaderId').hide();
		            
	    } else {
		        $("#err_div").css("display", "block");
        		document.getElementById("err_div").innerHTML="";
        		document.getElementById("err_div").innerHTML="Invalid file type uploaded.";
				$('#err_div').addClass('alert');
				$('#err_div').addClass('alert-danger');
        		flag ==1;
        		$('#preloader').hide();
        		return false;	                 
		    }
        $('#preloader').hide();
	    
		}
	 if(authenticationtype == 2)
		{
		    document.getElementById('autheticate').value='changeprofile';
			$('#google-auth-verify ').addClass('openpop');
			return false;	 
			
		}
		
	if(flag == 0){
		
	//alert(fuData);
		//var imgs = document.getElementById("imgupload").src;
		
		//var fuData=$('#fileChooser').val();
		var file1 = $('#fileChooser').val();
		var fileChooser = $("#fileChooser").prop("files")[0];
	
		var form_data = new FormData();
		form_data.append("imgs", fileChooser);
		form_data.append("token", token);
		form_data.append("name", name);
		form_data.append("email_address", email_address);
		form_data.append("contact_phone", contact_phone);
		form_data.append("country", country);
	//	form_data.append("isebable", isebable);
		//form_data.append("file1", file_data2);
		
		//alert(imgs);
		//var dataString = 'name='+name+'&email_address='+email_address+"&contact_phone="+contact_phone+"&country="+country+"&imgs="+imgs;
		//alert(dataString);
		 $.ajax({
				url:"<?php echo BASEPATH; ?>/Profile/newupdateprofile",
				type: "POST",    
			    data: form_data,
			    contentType: false,
			    processData: false,
		  		success: function(response)
	     		{
				 var data=	JSON.parse(response);
				
				 if(data['success']!='' && data['success']=='success')
				 {
					 $('#preloaderId').show();
					$('#preloaderId').hide();
					$("#err_div").css("display", "block");
					document.getElementById("err_div").innerHTML="";
				//	document.getElementById("err_div").innerHTML="A Profile updation confirmation email has been sent to the registered email address. Please follow instructions within that email to update your profile.";
					$('#err_div').css('alert','green');
					$('#profileid').addClass('openpop');
				 }
				 else
				 {
						$('#preloaderId').hide();
						 if(data['failure'] && data['failure']!='')
						 {
							$('#preloaderId').hide();
							$("#err_div").css("display", "block");
							document.getElementById("err_div").innerHTML="";
							document.getElementById("err_div").innerHTML=data['failure'];
							$('#err_div').css('color','red');

							 
						 }
						 else
						 {
								$('#preloaderId').hide();
								$("#err_div").css("display", "block");
								document.getElementById("err_div").innerHTML="";
								document.getElementById("err_div").innerHTML='Something wrong. Please try again.';
								$('#err_div').css('color','red');

						 }
				 }		
	     			
	     		}
			});
			$('#preloaderId').hide();
	}
 }
 function contfunc(contact_phone){
	 	var mob = /^[1-9]{1}[0-9]{9}$/;
	 	return mob.test(contact_phone)
	 }
function changeprofileauthenticate(){
	var name=$('#name').val();
	var token = $('#token').val();
	var file1 = $('#fileChooser').val();
	var email_address=$('#email_address').val();
	var contact_phone=$('#contact_phone').val(); 
	var country=$('#int_ph option:selected').text();
	var fileChooser = $("#fileChooser").prop("files")[0];
	var form_data = new FormData();
	form_data.append("imgs", fileChooser);
	form_data.append("token", token);
	form_data.append("name", name);
	form_data.append("email_address", email_address);
	form_data.append("contact_phone", contact_phone);
	form_data.append("country", country);
//	form_data.append("isebable", isebable);
	//form_data.append("file1", file_data2);
	
	//alert(imgs);
	//var dataString = 'name='+name+'&email_address='+email_address+"&contact_phone="+contact_phone+"&country="+country+"&imgs="+imgs;
	//alert(dataString);
	 $.ajax({
			url:"<?php echo BASEPATH; ?>/Profile/newupdateprofile",
			type: "POST",    
		    data: form_data,
		    contentType: false,
		    processData: false,
	  		success: function(response)
     		{
			 var data=	JSON.parse(response);
			
			 if(data['success']!='' && data['success']=='success')
			 {
				$("#err_div").css("display", "block");
				document.getElementById("err_div").innerHTML="";
			//	document.getElementById("err_div").innerHTML="A Profile updation confirmation email has been sent to the registered email address. Please follow instructions within that email to update your profile.";
				$('#err_div').css('display','block');
				$('#err_div').css('color','green');
				$('#profileid').addClass('openpop');
				$('#preloaderId').hide();
 
			 }
			 else
			 {
					 if(data['failure'] && data['failure']!='')
					 {
						$("#err_div").css("display", "block");
						document.getElementById("err_div").innerHTML="";
						document.getElementById("err_div").innerHTML=data['failure'];
						$('#err_div').css('color','red');
						$('#preloaderId').hide();
					 }
					 else
					 {
							$("#err_div").css("display", "block");
							document.getElementById("err_div").innerHTML="";
							document.getElementById("err_div").innerHTML='Something wrong. Please try again.';
							$('#err_div').css('color','red');
							$('#preloaderId').hide();
						 
					 }
			 }		
     			
     		}
		});
}
 function change_pass()
 {  
	$('#preloader').css('display','block');
	$('#vcode').val('');
    $('#err_div_auth').empty();
	var old_pass=$('#old_pass').val();
	var new_pass=$('#new_pass').val();
	var repeat_pass=$('#repeat_pass').val();
	var token = $('#token').val();
	var authenticationtype="<?php echo $this->userInfo['data']['authentication_type'];?>"
    
	if(!old_pass || old_pass=='')
	{
		$("#err_div_pass").css("display", "block");
		document.getElementById("err_div_pass").innerHTML="";
		document.getElementById("err_div_pass").innerHTML="Please provide old password.";
		//$('#err_div_pass').addClass('alert');
		//$('#err_div_pass').addClass('alert-danger');
		$('#err_div_pass').css('color','red');

		$('#preloader').hide(); 
		return false;
		
	}
	else if(!new_pass || new_pass=='')
	{
		$("#err_div_pass").css("display", "block");
		document.getElementById("err_div_pass").innerHTML="";
		document.getElementById("err_div_pass").innerHTML="Please provide new password.";
		//$('#err_div_pass').addClass('alert');
		//$('#err_div_pass').addClass('alert-danger');
		$('#err_div_pass').css('color','red');
		$('#preloader').hide();
		return false;
	}
	else if(!passfun(new_pass)){
		$("#err_div_pass").css("display", "block");
		document.getElementById("err_div_pass").innerHTML="";
		document.getElementById("err_div_pass").innerHTML="Note: password must start with character, contain digits and only '@' is allowed as special character.";
		$('#err_div_pass').css('color','red');
		$('#preloader').hide();
		return false;
	}
	else if(!repeat_pass || repeat_pass=='')
	{
		$("#err_div_pass").css("display", "block");
		document.getElementById("err_div_pass").innerHTML="";
		document.getElementById("err_div_pass").innerHTML="Please provide repeat password.";
		$('#err_div_pass').css('color','red');
		$('#preloader').hide();
		return false;
	}else if(new_pass != repeat_pass)
	{
		$("#err_div_pass").css("display", "block");
		document.getElementById("err_div_pass").innerHTML="";
		document.getElementById("err_div_pass").innerHTML="New Password and Repeat password not Match.";
		$('#err_div_pass').css('color','red');
		$('#preloader').hide();
		return false;
	}else if(isebable && isebable=='2')
		{

		var dataString = 'old_pass='+old_pass+'&new_pass='+new_pass+"&repeat_pass="+repeat_pass+'&token='+token; 
		 $.ajax({
				url:"<?php echo BASEPATH; ?>/Checkleg/checkpassword", 
				type: "POST",    
			    data: dataString,
		  		success: function(response)
	     		{
			     	$('#preloader').hide();
					 var data=	JSON.parse(response);
					
					 if(data['success']!='' && data['success']=='success')
					 {
						 $('#preloader').show();
						$('#preloader').hide();
						 document.getElementById('autheticate').value='changepass';
							$('#google-auth-verify ').addClass('openpop');
					 }
					 else
					 {
						//$('#preloader1').hide();
						 if(data['failure'] && data['failure']!='')
						 {
							 $('#preloader').hide();
							$("#err_div_pass").css("display", "block");
							document.getElementById("err_div_pass").innerHTML="";
							document.getElementById("err_div_pass").innerHTML=data['failure'];
							$('#err_div_pass').css('color','red');
							return false;
						 }
						 else
						 {
							 $('#preloader').hide();
								$("#err_div_pass").css("display", "block");
								document.getElementById("err_div_pass").innerHTML="";
								document.getElementById("err_div_pass").innerHTML='Something wrong. Please try again.';
								$('#err_div_pass').css('color','red');
								return false;
						 }
					 }		
	     			
	     		}
			});
			$('#preloader').hide();
		}
   
	else
	{
		var dataString = 'old_pass='+old_pass+'&new_pass='+new_pass+"&repeat_pass="+repeat_pass+'&token='+token; 
		 $.ajax({
				url:"<?php echo BASEPATH; ?>/Profile/updatepassword", 
				type: "POST",    
			    data: dataString,
		  		success: function(response)
	     		{
			     	
					 var data=	JSON.parse(response);
					
					 if(data['success']!='' && data['success']=='success')
					 {
						 $('#preloader').show();
						 $('#preloader').hide();
						$("#err_div_pass").css("display", "block");
						document.getElementById("err_div_pass").innerHTML="";
						document.getElementById("err_div_pass").innerHTML="Password updated successfully.";
						$('#err_div_pass').css('color','green');
					 }
					 else
					 {
						 if(data['failure'] && data['failure']!='')
						 {
							 $('#preloader').hide();
							$("#err_div_pass").css("display", "block");
							document.getElementById("err_div_pass").innerHTML="";
							document.getElementById("err_div_pass").innerHTML=data['failure'];
							$('#err_div_pass').css('color','red');
						 }
						 else
						 {
							 	$('#preloader').hide();
								$("#err_div_pass").css("display", "block");
								document.getElementById("err_div_pass").innerHTML="";
								document.getElementById("err_div_pass").innerHTML='Something wrong. Please try again.';
								$('#err_div_pass').css('color','red');
						 }
					 }		
	     			
	     		}
			});
		 $('#preloader1').hide();
	}
 }
 function passfun(pass){
	 var passw=  /^(?=.*[a-zA-Z])(?=.*[0-9])(?=.*[@]).+$/;
 	return passw.test(pass)
 	
 }	    
function savepinautheticate(){

	var old_pass=$('#old_pass').val();
	var new_pass=$('#new_pass').val();
	var repeat_pass=$('#repeat_pass').val();
	var token = $('#token').val();
	var dataString = 'old_pass='+old_pass+'&new_pass='+new_pass+"&repeat_pass="+repeat_pass+'&token='+token; 
	 $.ajax({
			url:"<?php echo BASEPATH; ?>/Profile/updatepassword", 
			type: "POST",    
		    data: dataString,
	  		success: function(response)
    		{
		     	
				 var data=	JSON.parse(response);
				
				 if(data['success']!='' && data['success']=='success')
				 {
					$("#err_div_pass").css("display", "block");
					document.getElementById("err_div_pass").innerHTML="";
					document.getElementById("err_div_pass").innerHTML="Password updated successfully.";
					$('#err_div_pass').css('color','green');
				 }
				 else
				 {
					 if(data['failure'] && data['failure']!='')
					 {
						$("#err_div_pass").css("display", "block");
						document.getElementById("err_div_pass").innerHTML="";
						document.getElementById("err_div_pass").innerHTML=data['failure'];
						$('#err_div_pass').css('color','red');
					 }
					 else
					 {
							$("#err_div_pass").css("display", "block");
							document.getElementById("err_div_pass").innerHTML="";
							document.getElementById("err_div_pass").innerHTML='Something wrong. Please try again.';
							$('#err_div_pass').css('color','red');
					 }
				 }		
    			
    		}
		});
	
}
 function generateOtp(){
		var username = '';
		$('#generate_otp').hide();
		$.ajax({
			type: 'POST',
			url: '<?php echo BASEPATH; ?>/Profile/sendotp',
		data: {"username":$('#unm').val()},
			beforeSend:function(){
				// this is where we append a loading image
				/* if(withdrawal_type == 2){
					$('#ajax-panel2').html("Loading...").show();
				}else if(withdrawal_type == 3){ */
					$('#ajax-panel').html("Loading...").show();
				//}
				
			},
			success:function(data){
				var json_obj = $.parseJSON(data);
				if(json_obj['success']=='success')
				{
				$("#message").html("(Please wait upto 20 minutes and check OTP on mobile number, inbox folder or spam folder of your profile mail if not received click on button again.)").show();
					
					setTimeout(function() {
							$("#generate_otp").show()
						}, 1200000);
					
					$('#ajax-panel').empty();
					$('#ajax-panel').append('<h5>OTP Sent!</h5>').hide(5000);
				}
				else
				{
					$('#ajax-panel').append('<h5>Error sending OTP. Please try again later or contact us if the problem persists.</h5>').hide(15000);
				}
				
				
			}

		});
		return false;
	}
	function updateContact()
	{
		var full_name=$('#name').val();
		var contact_email=$('#contact_email').val(); 
		var contact_phone=$('#contact_phone').val(); 
		var country=$('#int_ph option:selected').text();
		var otp=$('#otp').val();
		
		//var authcode=$('#authcode').val();

		if(contact_email!='')
		{
		    var atpos = contact_email.indexOf("@");
		    var dotpos = contact_email.lastIndexOf(".");
			
		}


		if(!email_address || email_address=='')
		{

			$("#err_div_cont").css("display", "block");
			document.getElementById("err_div_cont").innerHTML="";
			document.getElementById("err_div_cont").innerHTML="Please provide email.";
			$('#err_div_cont').css('display','block');
			$('#err_div_cont').css('color','red');
			return false;
		}
		else if(atpos<1 || dotpos<atpos+2 || dotpos+2>=contact_email.length)
		{
	
			$("#err_div_cont").css("display", "block");
			document.getElementById("err_div_cont").innerHTML="";
			document.getElementById("err_div_cont").innerHTML="Please provide valid email.";
			$('#err_div_cont').css('display','block');
			$('#err_div_cont').css('color','red');
			return false;
		}
		else if(!contact_phone || contact_phone=='')
		{
		
			$("#err_div_cont").css("display", "block");
			document.getElementById("err_div_cont").innerHTML="";
			document.getElementById("err_div_cont").innerHTML="Please provide phone.";
			$('#err_div_cont').css('display','block');
			$('#err_div_cont').css('color','red');
			return false;
		}
		
		/*else if(!full_name || full_name=='')
		{
		alert("4");
			$("#err_div_cont").css("display", "block");
			document.getElementById("err_div_cont").innerHTML="";
			document.getElementById("err_div_cont").innerHTML="Please provide name.";
			$('#err_div_cont').css('display','block');
			$('#err_div_cont').css('color','red');
			return false;
		}*/
		else if(otp=='')
		{

			$("#err_div_cont").css("display", "block");
			document.getElementById("err_div_cont").innerHTML="";
			document.getElementById("err_div_cont").innerHTML="Please provide otp.";
			$('#err_div_cont').css('display','block');
			$('#err_div_cont').css('color','red');
			return false;
		}
		else
		{
			
			if(isebable==2)
			{
				$('#google-auth-verify').addClass('openpop');

			}
		else
		{
		var dataString = 'full_name='+full_name+'&contact_email='+contact_email+"&contact_phone="+contact_phone+"&country="+country+"&otp="+otp; 
		 $.ajax({
				url:"<?php echo BASEPATH; ?>/Profile/updatecontact", 
				type: "POST",    
			    data: dataString,
		  		success: function(response)
	     		{
					 var data=	JSON.parse(response);
					
					 if(data['success']!='' || data['success']=='success')
					 {
						$("#err_div_cont").css("display", "block");
						document.getElementById("err_div_cont").innerHTML="";
						document.getElementById("err_div_cont").innerHTML="Password updated successfully.";
						$('#err_div_cont').css('color','green');
					 }
					 else
					 {
						 if(data['failure'] && data['failure']!='')
						 {
							$("#err_div_cont").css("display", "block");
							document.getElementById("err_div_cont").innerHTML="";
							document.getElementById("err_div_cont").innerHTML=data['failure'];
							$('#err_div_cont').css('color','red');
						 }
						 else
						 {
								$("#err_div_cont").css("display", "block");
								document.getElementById("err_div_cont").innerHTML="";
								document.getElementById("err_div_cont").innerHTML='Something wrong. Please try again.';
								$('#err_div_cont').css('color','red');
						 }
					 }		
	     			
	     		}
			});
		}
		}
	}

 </script>
<style>
	.form-group{
		display: block;
		
	}
	.form-group1{
		display: inline-block;
		width:20%;
	}
	.form-group2{
		display: inline-block;
		width:79%;
		float: right;
	}
	.bg-pop-header-profile{
		background-color:#333;
		padding:10px;
	}
	.profile-card{
		padding:10px;
	}
	@media (max-width:480px){
	.form-group1{
		display: inline-block;
		width:100%;
	}
	.form-group2{
		display: inline-block;
		width:100%;
	}		
	}	
</style>
 <div class="modal req-admin bg-popup" id="cat_alt">
                        <div class="modal-dialog popup  pop-center-cl">
						<div class="modal-content no-padding">
						<div class="bg-pop-header">
							<span class="text-pop-header">CONFIRMATION</span>
							<button type="button" class="close"	data-dismiss="modal" aria-hidden="true" onclick="closealt();">
									<i class="fa fa-close" style="color:#fff;"></i>
							</button>

						</div>
                                <div style="padding:25px;" class="form-basic">
                                       <div id="cont_hold" class="alert alert-success"><b> Program subscription done successfully.</b></div>                                                
                                </div>

                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div>
       
 <div class="modal req-admin bg-popup" id="profileid">
                        <div class="modal-dialog popup pop-center">
						<div class="modal-content no-padding" >
						<div class="bg-pop-header">
							<span class="text-pop-header">CONFIRMATION</span>
							<button type="button" class="close"	data-dismiss="modal" aria-hidden="true" onclick="closeprofile();">
									<i class="fa fa-close" style="color:#fff;"></i>
							</button>

						</div>
                                <div style="padding:25px;" class="form-basic">
                                       <div id="cont_hold" class="alert alert-success"><b> A Profile updation confirmation email has been sent to the registered email address. Please follow instructions within that email to update your profile.</b></div>                                          
         
                                </div>

                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div>             
                    
  <div class="content">
			<div class="page-title-group">
				<h4 class="page-title">Profile</h4>
				<h5 class="text-muted page-title-alt">Profile & Settings</h5>
			</div>
			<div class="cb-page-content">
				<div class="container">
					<div class="row   "> 
						<div class="col-lg-6">
							<div class="panel panel-color panel-primary">
								<div class="panel-heading"> 
									<h3 class="panel-title">Basic info</h3> 
								</div> 
								<div class="panel-body"> 
								<div class="row">
									<div class="col-md-12">
										<div class="profile-card" style="color:#323232;">
											<h3>REGISTRATION DETAILS</h3>
										</div>
										<div class="profile-card">
											<div class="row">
												<div class="col-md-6">
													<b>Sponsor ID</b>
												</div>
												<div class="col-md-6">
													<?php echo isset($this->userInfo['data']['ref_sponsor_id'])? $this->userInfo['data']['ref_sponsor_id'] : '' ?>
												</div>
											</div>
										</div>
										<div class="profile-card">
											<div class="row">
												<div class="col-md-6">
													<b>Ref ID</b>
												</div>
												<div class="col-md-6">
													<?php echo isset($this->userInfo['data']['sponsor_id'])? $this->userInfo['data']['sponsor_id'] : '' ?>
												</div>
											</div>
										</div>                                            
										<div class="profile-card">
											<div class="row">
												<div class="col-md-6">
													<b>Email</b>
												</div>
												<div class="col-md-6">
													<?php echo isset($this->userInfo['data']['ref_sponsor_id'])? $this->userInfo['data']['email_address'] : '' ?>
												</div>
											</div>
										</div>
									</div> <!-- list-group -->
								</div>	
								<div class="row">	
									<div class="col-md-12">
										<div class="profile-card" style="color:#323232;">
											<h3>COMMUNICATION DETAILS</h3>
										</div>
										<div class="profile-card">
											<div class="row">
												<div class="col-md-6">
													<b>Full Name</b>
												</div>
												<div class="col-md-6">
													<?php echo isset($this->userInfo['data']['ref_sponsor_id'])? $this->userInfo['data']['name'] : '' ?>
												</div>
											</div>
										</div>
										<div class="profile-card">
											<div class="row">
												<div class="col-md-6">
													<b>Email</b>
												</div>
												<div class="col-md-6">
													<?php echo $this->user_cat['profile_image'][0]['comm_email']?>
												</div>
											</div>
										</div>                                            
										<div class="profile-card">
											<div class="row">
												<div class="col-md-6">
													<b>Phone</b>
												</div>
												<div class="col-md-6">
													+<?php echo $this->userInfo['data']['country']; ?>-&nbsp;<?php echo isset($this->userInfo['data']['phone'])? $this->userInfo['data']['phone'] : '' ?>
												</div>
											</div>
										</div>
                           </div> 
								</div>	
								</div> 
							</div>							
						</div>
						<div class="col-lg-6">
							<div class="panel panel-color panel-primary">
								<div class="panel-heading"> 
									<h3 class="panel-title">Edit Profile</h3> 
								</div> 
								<div class="panel-body"  style="min-height: 410px;"> 
								<div class="row">
									<div class="col-md-12">
                                         <form class="form-basic">
											  <div class="row">
												<div class="col-md-12">
													  <div id="err_div" name="err_div"></div>																				
														<div class="form-group">
															<label for="" class="lblTxt"><b>Name</b></label>
															<input type="text" name="name" id="name" class="form-control" value="<?php echo isset($this->userInfo['data']['ref_sponsor_id'])? $this->userInfo['data']['name'] : '' ?>">
														</div>

														<div class="form-group">
															<label for="" class="lblTxt"><b>Email</b></label>   
															<input type="email" name="email_address" id="email_address" class="form-control" value="<?php echo $this->user_cat['profile_image'][0]['comm_email']?>">  
														</div>
														<div class="form-group1">
															<label for="" class="lblTxt"><b>Country Code</b></label>
																<select id="int_ph" name="int_ph" class="form-control">						
																  <?php   if(!empty($this->user_cat['country_data']) && sizeof($this->user_cat['country_data'])>0)
																		{
																			for($i=0;$i<sizeof($this->user_cat['country_data']);$i++)
																			{?>

																				<option <?php if($this->user_cat['country_data'][$i]['ccode']==$this->userInfo['data']['country']) { ?> selected="true" <?php } ?>><?php echo $this->user_cat['country_data'][$i]['ccode']; ?></option>

																			<?php }
																		}?>
																</select>

														</div> 
												<div class="form-group2" >
													 <label for="" class="lblTxt" style=""><b>Phone</b></label>
													<input type="phone" name="contact_phone" id="contact_phone" class="form-control nokey" maxlength="12" value="<?php echo isset($this->userInfo['data']['phone'])? $this->userInfo['data']['phone'] : '' ?>" />
												</div> 													
												
													<div style="display:none;">
									
															<input class="file-upload form-control" id="fileChooser" name="image" type="file" style="padding:10px;" accept="image/*"/>		

													</div> 	  
												</div> 
											  </div>
												 
												<button type="button" class="btn btn-primary btn-md" style="margin-top: 33px;margin-bottom: 24px;" onclick="updateProfile();">UPDATE PROFILE</button>
												<div id="preloaderId" class="" style="float:right;margin-top:40px;display:none;">
													<img src="<?php echo BASEPATH; ?>/images/ajax_loader_2.gif" height="24" width="24">
												</div>		
										

									</form>
									</div>
								</div>

								</div> 
							</div>						
						
						</div>
					</div>	
					<div class="row   "> 
						<div class="col-lg-6">
							<div class="panel panel-color panel-primary">
								<div class="panel-heading"> 
									<h3 class="panel-title">Change Password</h3> 
								</div> 
								<div class="panel-body" style="min-height: 410px;" id="pass_div"> 
								<div class="row">
									<div class="col-md-12">
										<form>
												<div id="err_div_pass" name="err_div_pass"></div>
													  <div class="form-group sizecls">
														  <label for="" class="lblTxt"><b>Old Password</b></label>
															<input type="password" class="form-control CommonInputBox" placeholder="Old Password" id="old_pass">
													  </div>

													   <div class="form-group sizecls">
														   <label for="" class="lblTxt"><b>New Password</b></label>
															<input type="password" class="form-control CommonInputBox" placeholder="New Password" id="new_pass">
													  </div>

													   <div class="form-group sizecls">
														   <label for="" class="lblTxt"><b>Repeat New Password</b></label>
															<input type="password" class="form-control CommonInputBox" placeholder="Repeat New Password" id="repeat_pass">
													  </div>


												


											  <button type="button" class="btn btn-primary btn-md" style="margin-bottom: 16px;margin-top: 16px;" onclick="change_pass()">CHANGE PASSWORD</button>	
												<div id="preloader" class="" style="float:right;margin-top:20px;display:none;">
													<img src="<?php echo BASEPATH; ?>/images/ajax_loader_2.gif" height="24" width="24">
												</div>		

											</form>									
										</div>
									</div>
								</div> 
							</div>	
						</div>
						<div class="col-lg-6">
							<div class="panel panel-color panel-primary">
								<div class="panel-heading"> 
									<h3 class="panel-title">Security Setting</h3> 
								</div> 
								<div class="panel-body"  style="min-height: 410px;"> 
									<div class="row">
									<div class="col-md-12">
										 <div class="list-group">
											<div class="list-group-item bg-pop-header-profile" style="color:#fff;">
												<b>2 FACTOR AUTHENTICATION</b>
											</div>
                                            <div class="list-group-item" style="text-align:center;">
												<form>

												<div id="auth_err_div" name="auth_err_div"></div>

												<?php if(!empty($this->userInfo['data']['authentication_type']) && $this->userInfo['data']['authentication_type']==2) { ?>
												<div class="form-group">
												<div for="" id="headsel" class="lblTxt" style="color:green">2 Factor authentication is enabled.</div>

												 </div>


												   <div class="form-group">
													   <span>
															<input type="radio" onclick="openAuthPopup();" checked  id="enble" name="authentication" value="1" tabindex="15">
															Enable
													  </span>
													  <span>
															<input type="radio" onclick="openAuthPopup();"  id="disble" name="authentication" value="2" tabindex="15">
															 Disable
													  </span>
												 </div>



											   <?php } else { ?>
												<div class="form-group">
													<div for="" class="lblTxt" id="headsel" style="color:#ff0000;">2 Factor authentication is disabled.</div>

												</div>

												<div class="form-group">
													<span>
															<input type="radio" onclick="openAuthPopup();" id="enble" name="authentication" value="1" tabindex="15">
															Enable
													 </span>
													  <span style="margin-left: 8%;">
															<input type="radio" onclick="openAuthPopup();" checked   id="disble" name="authentication" value="2" tabindex="15">
															Disable

													 </span>
												 </div>

												  <div class="form-group">

												 </div>

											   <?php } ?>




											</form>											
											 </div>											 
										</div>	 
									</div>
									<div class="col-md-12">
										 <div class="list-group">
											<div class="list-group-item bg-pop-header-profile" style="color:#fff;">
												<b>PLACEMENT</b>
											</div>
                                            <div class="list-group-item" style="text-align:center;min-height:110px;"><br/>
											   <span style="margin-left: 9%;">
													<input <?php if ($this->userInfo['data']['placement']=='L'){ ?> checked="true"  <?php } ?> type="radio" onclick="choosePlacement(this)" checked  id="lplace" name="place" value="L" tabindex="15" <?php if($this->totalchild < 1){?> disabled <?php }?>>
													Left
											  </span>
											  <span style="margin-left: 14%;">
													<input <?php if ($this->userInfo['data']['placement']=='R'){ ?> checked="true"  <?php } ?> type="radio" onclick="choosePlacement(this)"  id="rplace" name="place" value="R" tabindex="15" <?php if($this->totalchild < 1){?> disabled <?php }?>>
													 Right
											  </span>
											  <span style="margin-left: 8%;">
												   <?php if($this->totalchild < 1){ ?>
													  <p class="note" style="font-size:11px;margin-top:19px;margin-bottom:10px;">**Please Note: You need to place first child in your power leg in order to place users in both legs.</p> 
												  <?php } ?>

											  </span>											
											</div>											 
										</div>	 
									</div>		
								</div>	
								</div> 
							</div>							
						</div>
					</div>						

					</div> 
                </div>					
          <input type="hidden" id="autheticate" value="">
                   <div class="modal req-admin bg-popup" id="google-auth">
						<div class="modal-dialog popup height-popup big-pop-center" >
							<div class="modal-content no-padding">
								<div class="bg-pop-header">
									<span class="text-pop-header">ENABLE AUTHENTICATION</span>
									<button type="button" class="close"	data-dismiss="modal" aria-hidden="true" onclick="closePopup();">
											<i class="fa fa-close" style="color:#fff;"></i>
									</button>

								</div>
                                <div style="padding:25px;height:450px;overflow-y:auto;" class="form-basic">
                                    <a href="javascript:void(0)"><img alt="" src="<?php echo BASEPATH; ?>/images/login-logo.png" class="img-responsive center-block"></a>
									
                                    <div style="padding:20px;">
                                     
                                    <div class="bar-code" style="text-align:center;"><img src="<?php echo $this->qrCodeUrl; ?>" alt="" height="150" width="150"></div>
                                    <div class="alert alert-danger" id="err_div" style="display:none;padding:5px;"></div>
										<h5>Scan QR code and enter code</h5>										
										
                                        <input type="text" id="code" name="code" class="form-control">
                                    </div>
                                    <div style="text-align:center;">
                                    	<button type="button" value="SUBMIT" class="btn btn-primary btn-lg" onclick="authenticater();">SUBMIT</button>
									</div>                                     
                                    <div class="row m-t-20">
                                        <div class="col-md-12"><p class="" style="text-align:-webkit-center;">We recommend to use <a href="http://authy.com">Authy app</a> for backup and restore option, in case of 2FA device lost. <br/>Take screenshot or save QR Code image by right click on it for backup and restore option.</p></div>
                                        <div class="col-md-12">
										<div class="row">
                                          <div class="col-md-6 col-xs-12"><a href="https://itunes.apple.com/en/app/authy/id494168017?mt=8"><img alt="" src="<?php echo BASEPATH; ?>/images/g-store.png" class="img-responsive center-block" width="200" height="62"></a></div>
                                          <div class="col-md-6 col-xs-12"><a href="https://play.google.com/store/apps/details?id=com.authy.authy&hl=en"><img alt="" src="<?php echo BASEPATH; ?>/images/g-play.png" class="img-responsive center-block"  width="200" height="62"></a></div>
                                        </div>
										</div>
                                    </div>



                                </div>

                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div>
					
 					<div class="modal req-admin bg-popup" id="google-auth-verify">
						<div class="modal-dialog height-popup big-pop-center" >
							<div class="modal-content no-padding">
								<div class="bg-pop-header">
									<span class="text-pop-header">2 FACTOR AUTHENTICATION</span>
									<button type="button" class="close"	data-dismiss="modal" aria-hidden="true" onclick="closePopup();">
											<i class="fa fa-close" style="color:#fff;"></i>
									</button>

								</div>
                                <div style="padding:25px;height:450px;overflow-y:auto;" class="form-basic">
									<form  onsubmit="return false">

										<a href="javascript:void(0)"><img alt="" src="<?php echo BASEPATH; ?>/images/login-logo.png" class="img-responsive center-block"></a>
										<div style="padding:20px;">
										<div class="alert alert-danger" id="err_div" style="display:none;padding:5px;"></div>

											<h5>Enter google authentication code</h5>										
											<input type="text" id="vcode" name="vcode" class="form-control">
										</div>
										<div style="text-align:center;">
											<button type="button" value="SUBMIT" class="btn btn-primary btn-lg" onclick="return verify();">SUBMIT</button>
										</div> 
									</form>
										
                                    <div class="row m-t-20">
                                        <div class="col-md-12"><p class="">We recommend to use <a href="http://authy.com">Authy app</a> for backup and restore option, in case of 2FA device lost. <br/>Take screenshot or save QR Code image by right click on it for backup and restore option.</p></div>
                                        <div class="col-md-12">
										<div class="row">
                                          <div class="col-md-6 col-xs-12"><a href="https://itunes.apple.com/en/app/authy/id494168017?mt=8"><img alt="" src="<?php echo BASEPATH; ?>/images/g-store.png" class="img-responsive center-block" width="200" height="62"></a></div>
                                          <div class="col-md-6 col-xs-12"><a href="https://play.google.com/store/apps/details?id=com.authy.authy&hl=en"><img alt="" src="<?php echo BASEPATH; ?>/images/g-play.png" class="img-responsive center-block"  width="200" height="62"></a></div>
                                        </div>
										</div>
                                    </div>
                                </div>

                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div>
					
					<div class="modal req-admin bg-popup" id="google-auth-disble">
						<div class="modal-dialog height-popup big-pop-center" >
							<div class="modal-content no-padding">
								<div class="bg-pop-header">
									<span class="text-pop-header">DISABLE AUTHENTICATION</span>
									<button type="button" class="close"	data-dismiss="modal" aria-hidden="true" onclick="closePopup();">
											<i class="fa fa-close" style="color:#fff;"></i>
									</button>

								</div>
                                <div style="padding:25px;height:450px;overflow-y:auto;" class="form-basic">
									<form  onsubmit="return false">

										<a href="javascript:void(0)"><img alt="" src="<?php echo BASEPATH; ?>/images/login-logo.png" class="img-responsive center-block"></a>
										<div style="padding:20px;">
										<div class="alert alert-danger" id="err_div" style="display:none;padding:5px;"></div>

											<h5>Enter google authentication code</h5>										
											<input type="text" id="gcode" name="gcode" class="form-control">
										</div>
										<div style="text-align:center;">
											<button type="button" value="SUBMIT" class="btn btn-primary btn-lg" onclick="deauthenticater();">SUBMIT</button>
										</div> 
									</form>
										
                                    <div class="row m-t-20">
                                        <div class="col-md-12"><p class="">We recommend to use <a href="http://authy.com">Authy app</a> for backup and restore option, in case of 2FA device lost. <br/>Take screenshot or save QR Code image by right click on it for backup and restore option.</p></div>
                                        <div class="col-md-12">
										<div class="row">
                                          <div class="col-md-6 col-xs-12"><a href="https://itunes.apple.com/en/app/authy/id494168017?mt=8"><img alt="" src="<?php echo BASEPATH; ?>/images/g-store.png" class="img-responsive center-block" width="200" height="62"></a></div>
                                          <div class="col-md-6 col-xs-12"><a href="https://play.google.com/store/apps/details?id=com.authy.authy&hl=en"><img alt="" src="<?php echo BASEPATH; ?>/images/g-play.png" class="img-responsive center-block"  width="200" height="62"></a></div>
                                        </div>
										</div>
                                    </div>
                                </div>

                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div>
         
<input type="hidden" id="unm" name="unm" value="<?php echo $this->userInfo['data']['username'];?>">
 	
		

<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
<div class="clearfix">&nbsp;</div>










  <!--      <div class="col-lg-12">
<div class="panel panel-primary buynowbox col-lg-6">
              <div class="panel-heading buynowbox Titleheading faqtitlebg">
               Security Settings : GOOGLE 2FA 
              </div>

              <div class="panel-body revenuebg">
          <form>

	 <div id="auth_err_div" name="auth_err_div"></div>
 
   <?php if(!empty($this->userInfo['data']['authentication_type']) && $this->userInfo['data']['authentication_type']==2) { ?>
   <div class="form-group">
    <div for="" id="headsel" class="lblTxt" style="color:green">2 Factor authentication is enabled.</div>

  </div>


   <div class="form-group">
   <span>
  <input type="radio" onclick="openAuthPopup();" checked  id="enble" name="authentication" value="1" tabindex="15">
  Enable
  </span>
  <span>
    <input type="radio" onclick="openAuthPopup();"  id="disble" name="authentication" value="2" tabindex="15">
  Disable
  </span>
 </div>
 


   <?php } else { ?>
      <div class="form-group">
    <div for="" class="lblTxt" id="headsel" style="color:green">2 Factor authentication is disabled.</div>

  </div>
   
<div class="form-group">
<span>
  <input type="radio" onclick="openAuthPopup();" id="enble" name="authentication" value="1" tabindex="15">
  Enable
 </span>
  <span style="margin-left: 8%;">
   <input type="radio" onclick="openAuthPopup();" checked   id="disble" name="authentication" value="2" tabindex="15">
  Disable

 </span>
 </div>
 
   <?php } ?>



  
</form>
  </div>
 </div>

 </div>
 
 
 
 
 </div> -->
<div class="clearfix">&nbsp;</div>
        </div>

            <!-- /.row -->
            
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
 <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">   
    <script>
    /*** upload image ******/
    
    $(document).ready(function() {   
	    var readURL = function(input) {
	        if (input.files && input.files[0]) {
	            var reader = new FileReader();
	
	            reader.onload = function (e) {
	                $('.profile-pic').attr('src', e.target.result);
	            }
	    
	            reader.readAsDataURL(input.files[0]);
	        }
	    }
	    
	
	    $(".file-upload").on('change', function(){
	        readURL(this);
	    });	    
	    
	});
    
    
    </script>
	<script>

	
		
	/*open: function(event, ui) {
	    setTimeout(function(){
		    alert("inside");
	        	$('#cat_alt').removeClass('openpop');                
	    }, 3000);
	}*/
	function openAuthPopup()
	{
		

	var selectedval= $("input[name='authentication']:checked").val();

		if(selectedval==1)
		{
		//	$('#google-auth').css("display","block"); 
			$('#google-auth').addClass('openpop'); 
			//authenticater();
		}
		else
		{
			//$('#google-auth-disble').css("display","block");
			$('#google-auth-disble').addClass('openpop'); 
			//deauthenticater();
		}
	}
	
	
	function authenticater()
	{
		
		
	var code=$('#code').val();
					 $.ajax({
						url:"<?php echo BASEPATH; ?>/Profile/enableauth",
						type: "POST",    
					    data: 'code='+code,
						dataType: "json",
				  		success: function(response)
			      		{ 
						
							if(response.success=="success")
							{
								$('#auth_err_div').empty();
								$('#headsel').empty();
								$('#headsel').css("color","green");
								$('#headsel').append("2 Factor authentication is enabled");
								isebable=2;
								
							/*	//$("#disble").removeAttr('disabled');;
								//$("#disble").removeAttr('checked');;
								$( "#disble" ).removeAttr("disabled");
								$( "#disble" ).removeAttr("checked");
								//$("#enble").addAttr('checked');	
								$( "#enble" ).attr( "checked", "checked" );
								$( "#enble" ).attr( "disabled", "disabled");
								//$("#enble").addAttr('disabled');*/
							
							    //window.location="<?php echo BASEPATH;?>/Profile";
								closePopup();
								
							}
							else
							{
								$('#auth_err_div').css("color","red");
								$('#auth_err_div').css("display","block");
								$('#auth_err_div').empty();
								$('#auth_err_div').append("Invalid 2FA otp");
								
								$( "#enble" ).removeAttr("checked");
								$("#disble").prop( "checked", "true" );	
								closePopup();
							}
						
			      			
			      		}
					});
	}
	
	function deauthenticater()
	{
		
	var code=$('#gcode').val();
					 $.ajax({
						url:"<?php echo BASEPATH; ?>/Profile/disableauth",
						type: "POST",    
					    data: 'code='+code,
						dataType: "json",
				  		success: function(response)
			      		{
						
							if(response.success=="success")
							{
								
								isebable=1;
							
								$('#auth_err_div').empty();
								$('#headsel').empty();
								$('#headsel').css("color","red");
								$('#headsel').append("2 Factor authentication is disabled");
								
								
								//window.location="<?php echo BASEPATH;?>/Profile";
									closePopup();
								
							}
							else
							{
								$('#auth_err_div').css("color","red");
								$('#auth_err_div').css("display","block");
								$('#auth_err_div').empty();
								$('#auth_err_div').append("Invalid 2FA otp");
								
								$( "#disble" ).removeAttr("checked");
								$("#enble").prop( "checked", "true" );
								closePopup();
							}
						
			      			
			      		}
					});
	}
	
	function closePopup()
	{

		$('.modal ').removeClass('openpop');
		window.location="<?php echo BASEPATH;?>/Profile";
	}
	function verify()
	{
		    $('#err_div_auth').empty();
		    $('#vcode').empty();
			var code=$('#vcode').val();

			if(!code || code=='' || code==null)
			{
				$('#err_div_auth').css("display","block");
				$('#err_div_auth').empty();
				$('#err_div_auth').append("Please enter 2FA Authentication code");
				$('#err_div_auth').css("color","red");
				return false;
				//alert(Loginpin.length);
			}
			 
					 $.ajax({
						url:"<?php echo BASEPATH; ?>/Profile/verifyauth",
						type: "POST",    
					    data: 'code='+code,
						dataType: "json",
				  		success: function(response)
			      		{
							
							if(response.success=="success")
							{
								closePopup();
								
								var autheticate=$('#autheticate').val();
                                if(autheticate == 'changepass'){
								savepinautheticate();
							}else if(autheticate == 'savepin' ){
								savepinauthenticate();
							}else if(autheticate == 'changeprofile' ){
								changeprofileauthenticate();
							}
								
							}
							else
							{
								
								$('#err_div_auth').css("display","block");
								$('#err_div_auth').empty();
								$('#err_div_auth').append("Incorrect One Time Password for 2FA Authentication. Please generate a new OTP");
								$('#err_div_auth').css("color","red");
								return false;
							}
						
			      			
			      		}
					});
	}


	function selCategory(id)
	{
		var token = $('#token').val();
		 $.ajax({
				url:"<?php echo BASEPATH; ?>/Profile/enablecategoty",
				type: "POST",    
			    data: 'cat_id='+id+'&token='+token,
		  		success: function(response)
	   			{	
					if(response!="failed")
					{
						var innerdata='<b> Program subscription done successfully.</b>';	
						$('#cont_hold').empty();
						$('#cont_hold').append(innerdata);	
						$('#cat_alt').addClass('openpop');
					}
					else
					{
						var innerdata='<b style="color:red;">Invalid Input</b>';	
						$('#cont_hold').empty();
						$('#cont_hold').append(innerdata);	
						$('#cat_alt').addClass('openpop');
					}
							
	   			}
			})
	}
	function closealt()
	{
		$('#cat_alt').removeClass('openpop');
		var str=$('#cont_hold').text();
		
		if (str.toLowerCase().indexOf("placement") >= 0 || str.toLowerCase().indexOf("login")>0)
		{
			
		}
		else
		{
			location.reload(); 
		}
	
	}

	function choosePlacement(id)
	{
		
		var token = $('#token').val();
		var myRadio = $('input[name=place]:checked').val();
		var dataString='place='+myRadio+'&token='+token+'&username=';
		if(myRadio=='L')
		{
			var placement='Left';
		}
		else
		{
			var placement='Right';
		}
		 $.ajax({
				url:"<?php echo BASEPATH; ?>/Profile/chooseplacement", 
				type: "POST",    
				data: dataString,
				success: function(response)
				{
					if(response!="failed")
					{
						var innerdata='<b> You have choosen '+placement+' placement.</b>';	
						$('#cont_hold').empty();
						$('#cont_hold').append(innerdata);	
						$('#cat_alt').addClass('openpop');
					}
					else
					{
						var innerdata='<b style="color:red;">Invalid Input Found.</b>';	
						$('#cont_hold').empty();
						$('#cont_hold').append(innerdata);	
						$('#cat_alt').addClass('openpop');
					}
				}
		 });
		 setTimeout(function(){
			 $('#cat_alt').removeClass('openpop');
			},5000);
		
	}

	function savePin()
	{
		$('#vcode').val('');
		$('#err_div_auth').empty();
		var Loginpin= $('#Loginpin').val();
		var token = $('#token').val();
		var authenticationtype="<?php echo $this->userInfo['data']['authentication_type'];?>"
		
		if(!Loginpin || Loginpin=='' || Loginpin==null)
		{
			$('#cont_hold').empty();
			$('#cont_hold').append("Please enter Login Pin.");	
			$('#cat_alt').addClass('openpop');
			return false;
			//alert(Loginpin.length);
		}
		if((Loginpin.length)!=4)
		{
			$('#cont_hold').empty();
			$('#cont_hold').append("Please enter 4 digit Login Pin.");	
			$('#cat_alt').addClass('openpop');
			return false;
		}
		if(authenticationtype==2)
		{
			
			document.getElementById('autheticate').value='savepin';
			$('#google-auth-verify ').addClass('openpop');
		}
	
		else
		{
			 $.ajax({
					url:"<?php echo BASEPATH; ?>/Profile/setpin", 
					type: "POST",    
					data: 'pin='+Loginpin+'&token='+token,
					success: function(response)
					{
						var data=	JSON.parse(response);
						if(data['success']!='')
						{
							$('#cont_hold').empty();
							$('#cont_hold').append(data['data']);	
							$('#cat_alt').addClass('openpop');
							return false;
						}
						else
						{
							if(data['failure']!='')
							{
								$('#cont_hold').empty();
								$('#cont_hold').append(data['failure']);	
								$('#cat_alt').addClass('openpop');
								return false;
							}
							else
							{
								$('#cont_hold').empty();
								$('#cont_hold').append('Failed to set Login Pin. Please try again.');	
								$('#cat_alt').addClass('openpop');
								return false;
							}
							
						}
					}
			 });
		}
	}
function savepinauthenticate(){
	var Loginpin= $('#Loginpin').val();
	var token = $('#token').val();
	$.ajax({
		url:"<?php echo BASEPATH; ?>/Profile/setpin", 
		type: "POST",    
		data: 'pin='+Loginpin+'&token='+token,
		success: function(response)
		{
			var data=	JSON.parse(response);
			if(data['success']!='')
			{
				$('#cont_hold').empty();
				$('#cont_hold').append(data['data']);	
				$('#cat_alt').addClass('openpop');
				return false;
			}
			else
			{
				if(data['failure']!='')
				{
					$('#cont_hold').empty();
					$('#cont_hold').append(data['failure']);	
					$('#cat_alt').addClass('openpop');
					return false;
				}
				else
				{
					$('#cont_hold').empty();
					$('#cont_hold').append('Failed to set Login Pin. Please try again.');	
					$('#cat_alt').addClass('openpop');
					return false;
				}
				
			}
		}
 });
}
	--></script>
