<?php 
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); $misc_obj->generateToken();
?>
<style>
.form-group label{
    width: 150px;
}
.form-group {
    display: inline-block;
    margin-right: 25px;
    width: 300px;
    float:left;
}

.msg {
    display: none;
    color: red;
}
select {
    border: 1px solid #ddd !important;
    width: 46%;
}
.field {
		margin-top:-30px;
}
</style>
<div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12 offset-1">
                    <h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
              <ol class="breadcrumb">
                  <li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a> > </li>
                  <li>Setting > </li>
                  <li class="active"><a href="<?php echo BASEPATH?>/Subadmin">Sub Admin User</a> > </li>
                  <li>Add Sub Admin</li>
  
            </ol>
           

          <div class="clearfix">&nbsp;</div>

         
 <div class="clearfix">
         <div class="panel panel-primary buynowbox col-lg-12">

              <div class="panel-heading buynowbox Titleheading faqtitlebg">
               Add Sub Admin
              </div>

              <div class="panel-body revenuebg">
			 
          <form>
          <div class="err1">
          <label style="color:red" for="" class="lblTxt"> </label>
          </div>
          <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
	<?php if(!empty($this->msg) && isset($this->msg) && $this->msg !='') { ?>
  
  <?php //header('Location:http://gainbitcoin.test.com/Subadmin');  ?>
  
   
   
    <label style="color:red" for="" class="lblTxt"><?php echo $this->msg;  ?></label>
      

 <?php } ?>
   <div>




      
  </div>
  
  <div class="form-group">
    <label for="" class="lblTxt">First Name</label>

     <input class="form-control CommonInputBox" type="text" name="fname" id="fname" placeholder="First Name">


      
  </div>
  <div class="form-group">
    <label for="" class="lblTxt">Last Name</label>

     <input class="form-control CommonInputBox" type="text" id="lname" name="lname" placeholder="Last Name">


      
  </div>
   <div class="form-group">
    <label for="" class="lblTxt">Password</label>

     <input class="form-control CommonInputBox" type="password" name="password"  id="password" placeholder="password">


      
  </div>
  <div class="form-group">
    <label for="" class="lblTxt">Email</label>
	
     <input class="form-control CommonInputBox" type="text" onblur="emailvalidation()" name="email"  id="email" placeholder="Email">
	<!-- changes start -->
	<span class="msg error">Enter Valid Email Id!</span>
	<!-- changes end -->

      
  </div>
  <div class="form-group">
    <label for="" class="lblTxt">Contact Number</label>

     <input class="form-control CommonInputBox isnumber" type="text" name="mobile"  id="mob" placeholder="Contact Number" value="<?php echo isset($this->result->mob)?$this->result->mob:''; ?>">


      
  </div>
  <div class="form-group">
    <label for="" class="lblTxt">Status</label>

        <div class="col-lg-4 form-group" style="float:left;padding-left:5px;">
                                            <select class="form-control CommonInputBox"  name="status" id="status" style="	border: 1px solid !important;border-radius: 5px !important; width:292px;">
                                             <option value="select">Select</option>
                                                <option value="1">Active</option>
                                                <option value="0">Inactive</option>
                                            </select>
                                        </div>


      
  </div><br><br><br>


<div class="form-group" style="width:100%;">
 <input type="hidden" name="userid" id="userid"/> 
  <button type="button" class="btn btn-default Commonbtn" onclick="editsetting()">SUBMIT</button>
</div>
  
</form>
  </div>
          </div>
       
      


       
    
       <!--  <div class="col-lg-6 col-lg-offset-3 col-xs-offset-1 center-text ">
           <ul class="pagination pagination-sm">
              <li><a href="#"><img src="images/leftarw.png" alt=""></a></li>
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#"><img src="images/rightarw.png" alt=""></a> </li> 
      </ul>
    </div>-->
    <?php  // echo "<div align='center'>".$this->pagination($this->pagination_config)."</div>";
				//echo "<div>&nbsp;</div>";?>
        
      
    </div>
         
      
    

   

 
     




               
             
                
          
          </div>
      
            <!-- /.row -->
            
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



    </div>
    <script>
    function editsetting()
    {
        var firstname=$("#fname").val();
        var lastname=$("#lname").val();
        var password=$("#password").val();
        var email=$("#email").val();
        var contact_no=$("#mob").val();
        var status=$("#status").val();
		var userid=$("#userid").val();
		var token = $('#token').val();	


		if((firstname).trim()==''){
			$(".err1").html('<label for="" class="lblTxt" style="color:red;">Please enter First Name.</label>');
			return false;
		}	
		if((lastname).trim()==''){
			$(".err1").html('<label for="" class="lblTxt" style="color:red;">Please enter Last Name.</label>');
			return false;
		}
		if((password).trim()==''){
			$(".err1").html('<label for="" class="lblTxt" style="color:red;">Please enter Password.</label>');
			return false;
		}
		
		if((email).trim()==''){
			$(".err1").html('<label for="" class="lblTxt" style="color:red;">Please enter Email.</label>');
			return false;
		}
		if(!Emailfunc(email)){
			$(".err1").html('<label for="" class="lblTxt" style="color:red;">Please enter valid Email Id.</label>');
			return false;
		}
		if((contact_no).trim()==''){
			$(".err1").html('<label for="" class="lblTxt" style="color:red;">Please enter Contact No.</label>');
			return false;
		}
		if(!mobilefunc(contact_no)){
			$(".err1").html('<label for="" class="lblTxt" style="color:red;">Please enter 10 digit Contact No.</label>');
			return false;
		}
		if(status=="select"){
			$(".err1").html('<label for="" class="lblTxt" style="color:red;">Please select Status.</label>');
			return false;
		}
		
else{
	
var dataString ='firstname='+firstname+'&lastname='+lastname+'&password='+password+'&email='+email+'&contact_no='+contact_no+'&status='+status+'&token='+token;
		 $.ajax({
	 			url:"<?php echo BASEPATH;?>/Addsubadmin",
	 			type: "POST",    
	 			data: dataString,
	 			
	 	  	success: function(response)
	  		{
	 				 var data=JSON.parse(response);
	 				//alert(data);return;
					 if(data['success']!='')
					 {	
				           $(".err1").html('<label for="" class="lblTxt" style="color:green;">'+data['success']+'</label>');        
				          window.location ="<?php echo BASEPATH;?>/Subadmin";
					 }
					 	
					 else
					 {
						// alert( data['failure']);
						 $(".err1").html('<label for="" class="lblTxt" style="color:red;">'+data['failure']+'</label>');        
				         //window.location ="<?php echo BASEPATH;?>/Subadmin";
					 }
	  		}
	 		});
	}
		
        
    }
    function namefunc(name)
	{
		var pattern12 = new RegExp(/^[a-zA-Z ]+$/);
		return pattern12.test(name);
	}
   
    function Emailfunc(email) {
        var re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        return re.test(email);
    }

    function mobilefunc(contact_no){
    	var mob = /^[1-9]{1}[0-9]{9}$/;
    	return mob.test(contact_no)
    }
    </script>
    <script>
    
    </script>
