<?php $authUserNamespace = new Zend_Session_Namespace("Aranca_Auth"); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="<?php echo BASEPATH;?>/shared/style.css" rel="stylesheet" type="text/css" />
<script language="JavaScript" src="<?php echo BASEPATH;?>/shared/htmlDatePicker1.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/jquery-1.4.2.min.js"></script>
<script src="<?php echo BASEPATH;?>/js/jquery.alerts.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASEPATH;?>/css/jquery.alerts.css" />
<link href="<?php echo BASEPATH;?>/shared/htmlDatePicker.css" rel="stylesheet">
<script src="<?php echo BASEPATH;?>/shared/ga.js" async="" type="text/javascript"></script>
<!--<script type="text/javascript" src="<?php echo BASEPATH;?>/shared/jquery-1.js"></script>
--><script type="text/javascript" src="<?php echo BASEPATH; ?>/js/jquery.ui.core.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/js/mootools-1.2.4-core-yc.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/js/mediaboxAdv-1.2.4.js"></script>
<link media="screen" type="text/css" href="<?php echo BASEPATH ;?>/css/mediaboxAdvWhite.css" rel="stylesheet">

<script>



</script>
</head>
<body>
<div id="subheader">
	<div class="wrapper" style="text-align:left">
		<?php if (($this->score_list != "") || (isset($this->score_list))){?>
		<?php foreach($this->score_list as $view_list){ ?>
  		<div class="readfix" id="holder" >
  		
        	<label>Analyst Name:</label>
            <span class="readonly">
			<select  id="teammember">
              <option selected="selected" value="">Please Select</option>
              <?php	foreach ($this->teammember_list as $teammember_list){?>
			  <option value="<?php  if(isset($teammember_list->e_id) && $teammember_list->e_id !=""){ echo $teammember_list->teammembername;}?>"<?php if($this->e_id==$teammember_list->e_id) echo "selected";?>><?php echo $teammember_list->teammembername;?></option>
			  <?php } ?>
			  </select>
			</span>
        </div>
     
  		<div class="readfix" id="holder" >
  		
        	<label>Project Name:</label>
            <span class="readonly"><?php if(isset($this->score_list)) echo $view_list->title;?></span>
        </div>
        <div class="readfix" id="holder">
        	<label>Project Duration:</label>
            <span class="readonly">120 Hrs</span>
        </div>
        <div style="width:233px;" class="readfix" id="holder">
        	<label>Analyst Budgeted Hrs:</label>
            <span class="readonly"><?php if(isset($this->score_list)) echo $view_list->budgeted_hrs;?></span>
        </div>
        <br class="clear">
        <div style="width:215px;" class="readfix" id="holder">
        	<label>Actual Analyst Hrs:</label>
            <span class="readonly">140 Hrs</span>
        </div>
        <div class="readfix" id="holder">
        	<label class="left">Manager:</label>
            <span class="readonly"><?php if(isset($this->score_list)) echo $view_list->manager;?></span>
        </div>
        <div class="readfix" id="holder">
        	<label class="left">Start Date:</label>
            <span class="readonly"><?php if(isset($this->score_list)) echo $view_list->st_date;?></span>
        </div>
        <div class="readfix" id="holder">
        	<label class="left">End Date:</label>
            <span class="readonly"><?php if(isset($this->score_list)) echo $view_list->end_date;?></span>
        </div>
        <?php }}?>
  	</div>
  <br class="clear">
</div>

<div id="contentbg">
	<div class="frame">
    	<br class="clear">
    	<!--Starts Here -->
   	  <div class="wrapper">
   	  
      	<div id="tablebg">
        	<div class="col-first _m">Criteria</div>
          	<div class="col _prj">Parameters</div>
            <div class="col _prj">Weightage</div>
          	<div style="width:455px;text-align:left;" class="col _l">Corrective Comments</div>
            <div style="margin:0;" class="col _prj" style="text-align:left">Scores</div>
        </div>
            <?php  if(isset($this->listing) && sizeof($this->listing)>0){
					
        		foreach($this->listing as $view_list){ 
        ?>
        <div id="rowbg">
       	  	<div style="margin-left:5px;" class="col _prj"><input type="text" value="<?php echo $view_list->criteria;?>" class="field" name="project"></div>
            <div class="col _prj"><input type="text" value="<?php echo $view_list->parameter;?>" class="field" name="project"></div>
            <div class="col _prj"><input type="text" value="<?php echo $view_list->weightage;?>" class="field" name="project"></div>
            <div class="col _prj"><input type="text" style="width:440px;" value="<?php echo $view_list->comments;?>" class="field" name="project"></div>
            <div style="float:right;" class="col _prj"><input type="text"   id="score"  value="<?php echo $view_list->score;?>" class="field" name="project"></div>
        </div>
 
   		<?php }}?>
   
     	     <?php if(isset($this->score) && $this->score!="") { foreach($this->score as $score_list){ ?>
					      		
        <div style="float:right;" class="pagination" >Total Score: <a class="active" id="totalscore"><?php if(isset($this->score_list)) echo $score_list->totalscore; else echo "0";?></a></div>
        <?php } }?>
        <br class="clear">
      </div>
        <!--Ends Here -->
    </div>
</div>
</body>
</html>