<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>



<?php 
	$news = $this->result;
?>
	<link rel="stylesheet" href="<?php echo BASEPATH; ?>/css/lightbox.css" type="text/css" />
    <script src="<?php echo BASEPATH;?>/js/jssor.slider-23.1.6.min.js" type="text/javascript"></script>
    <script src="<?php echo BASEPATH;?>/js/lightbox.js" type="text/javascript"></script>
    <script type="text/javascript">
        jssor_1_slider_init = function() {

            var jssor_1_options = {
              $AutoPlay: 1,
              $AutoPlaySteps: 4,
              $SlideDuration: 160,
              $SlideWidth: 200,
              $SlideSpacing: 3,
              $Cols: 4,
              $ArrowNavigatorOptions: {
                $Class: $JssorArrowNavigator$,
                $Steps: 4
              },
              $BulletNavigatorOptions: {
                $Class: $JssorBulletNavigator$,
                $SpacingX: 1,
                $SpacingY: 1
              }
            };

            var jssor_1_slider = new $JssorSlider$("jssor_1", jssor_1_options);

            /*responsive code begin*/
            /*remove responsive code if you don't want the slider scales while window resizing*/
            function ScaleSlider() {
                var refSize = jssor_1_slider.$Elmt.parentNode.clientWidth;
                if (refSize) {
                    refSize = Math.min(refSize, 809);
                    jssor_1_slider.$ScaleWidth(refSize);
                }
                else {
                    window.setTimeout(ScaleSlider, 30);
                }
            }
            ScaleSlider();
            $Jssor$.$AddEvent(window, "load", ScaleSlider);
            $Jssor$.$AddEvent(window, "resize", ScaleSlider);
            $Jssor$.$AddEvent(window, "orientationchange", ScaleSlider);
            /*responsive code end*/
        };
    </script>
    <style>

        .jssorb03 {
            position: absolute;
        }
        .jssorb03 div, .jssorb03 div:hover, .jssorb03 .av {
            position: absolute;
            /* size of bullet elment */
            width: 21px;
            height: 21px;
            text-align: center;
            line-height: 21px;
            color: white;
            font-size: 12px;
            background: url('<?php echo BASEPATH;?>/images/img/b03.png') no-repeat;
            overflow: hidden;
            cursor: pointer;
        }
        .jssorb03 div { background-position: -5px -4px; }
        .jssorb03 div:hover, .jssorb03 .av:hover { background-position: -35px -4px; }
        .jssorb03 .av { background-position: -65px -4px; }
        .jssorb03 .dn, .jssorb03 .dn:hover { background-position: -95px -4px; }
        .jssora03l, .jssora03r {
            display: block;
            position: absolute;
            /* size of arrow element */
            width: 55px;
            height: 55px;
            cursor: pointer;
            background: url('<?php echo BASEPATH;?>/images/img/a03.png') no-repeat;
            overflow: hidden;
        }
        .jssora03l { background-position: -3px -33px; }
        .jssora03r { background-position: -63px -33px; }
        .jssora03l:hover { background-position: -123px -33px; }
        .jssora03r:hover { background-position: -183px -33px; }
        .jssora03l.jssora03ldn { background-position: -243px -33px; }
        .jssora03r.jssora03rdn { background-position: -303px -33px; }
        .jssora03l.jssora03lds { background-position: -3px -33px; opacity: .3; pointer-events: none; }
        .jssora03r.jssora03rds { background-position: -63px -33px; opacity: .3; pointer-events: none; }
    </style>

  <!-- Page-Title -->
  <div class="content">
	<div class="page-title-group">
		<h4 class="page-title">Gallery</h4>
		<a href="<?php echo BASEPATH;?>/Gallery"><h5 class="text-muted page-title-alt">Back to Gallery</h5></a>
	</div>
	<div class="cb-page-content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="card-box-content form-compoenent">
							<div class="row" id="mainDiv-one-related">
								<div class="col-lg-12">
									<div class="row">
										<div class="col-lg-12">
											<div class="card-box">
												<div class="card-box-content p-l-0 p-r-0">
													<div class="row">
														<div class="col-lg-12">
															<div class="card-box">
																<?php if(!empty($this->result[0]['video_links']) || !empty($this->result1)){?>
																	<div class="card-box-head  border-b m-t-0 ">
																		<h4 class="header-title">
																			<b><?php 
																			$title = str_replace("_"," ",$this->result[0]['title']);
																			echo $title;

																			?></b></h4>
																	</div>
																<?php } ?>
															</div>	 
														</div>
													</div>
													
													<?php if(!empty($this->result[0]['video_links'])){?>

													<div class="row">
														<div class="col-lg-12" style="box-sizing:border-box;">
															<div class="card-box">
																<div class="card-box-head " style="padding:0px 20px;">
																		<h4 class="header-title">Videos</h4>
																</div>
															</div>	 
														</div>
													<?php 
														$links = explode(",",$this->result[0]['video_links']);
													
														for($i=0;$i<sizeof($links);$i++){
													?>	
														<div class="col-lg-4">
															<div class="card-box">
																<div class="card-box-content p-l-0 p-r-0">
																	<div class="contact-list  nicescroll">
																		<iframe src="<?php echo $links[$i];?>" width="250" height="170" frameborder="0" allowfullscreen></iframe>										
																	</div>				
																</div>								
															</div>
														</div>
													<?php }?>		
	
													</div>	
													
													<?php } ?>
													
													<div class="row">
														<div class="col-lg-12">
															<div class="card-box">
																<div class="card-box-head " style="padding:0px 20px;">
																	<?php if(!empty($this->result1)){?>
																		<h4 class="header-title">Images</h4>
																	<?php }?>
																</div>
															</div>	 
														</div>														
														<div class="col-lg-12">
														<!-- carousal starts -->

															   <div id="jssor_1" style="position:relative;margin:0 auto;top:0px;left:0px;width:809px;height:150px;overflow:hidden;visibility:hidden;">
																<!-- Loading Screen -->
																<div data-u="loading" style="position:absolute;top:0px;left:0px;background:url('<?php echo BASEPATH;?>/images/img/loading.gif') no-repeat 50% 50%;background-color:rgba(0, 0, 0, 0.7);"></div>
																<div data-u="slides" style="cursor:default;position:relative;top:0px;left:0px;width:809px;height:150px;overflow:hidden;">
																	
																	<?php for($i=0;$i<sizeof($this->result1);$i++){ ?>
																	<div>
																		<a href="data:image/jpeg;base64,<?php echo base64_encode($this->result1[$i]['subimage']);?>" data-lightbox="gallery"><img
																			name="image"
																			id="image"
																			value=""
																			class="profile-pic"
																			height="150"
																			width="200"
																			src="data:image/jpeg;base64,<?php echo base64_encode($this->result1[$i]['subimage']);?>"
																		/></a>
																	</div>
																	<?php } ?>
																</div>
																<!-- Bullet Navigator -->
																<div data-u="navigator" class="jssorb03" style="bottom:10px;right:10px;">
																	<!-- bullet navigator item prototype -->
																	<div data-u="prototype" style="width:21px;height:21px;">
																		<div data-u="numbertemplate"></div>
																	</div>
																</div>
																<!-- Arrow Navigator -->
																<span data-u="arrowleft" class="jssora03l" style="top:0px;left:8px;width:55px;height:55px;" data-autocenter="2"></span>
																<span data-u="arrowright" class="jssora03r" style="top:0px;right:8px;width:55px;height:55px;" data-autocenter="2"></span>
															</div><!-- carousal ends-->
														</div>
													</div>
												</div>
											</div>						
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

					
<script data-cfasync="false"  type="text/javascript">
	jssor_1_slider_init();
	$("#mainDiv-one").on('click', function() {
	$("#mainDiv").hide();
	$("#mainDiv-one-related").show();
  });

	$("#close").on('click', function() {
		window.location="<?php echo BASEPATH;?>/Gallery";	
  });	

</script>										
					
					