<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>

 <script>
 function edit(id)
 {
	 // window.location="<?php echo BASEPATH; ?>/Editsubadmin?id="+id;
	   document.getElementById('form_edit'+id).submit();
		 
 }
 
 function setpermission(id)
 {
	//window.location="<?php echo BASEPATH; ?>/Setpermission?id="+id;
	   document.getElementById('form_set'+id).submit();
		
 }
 </script>
 <style>
 .table-responsive {
    min-height: 0.01%;
    overflow-x: hidden;
}
.Commonbtn {
    padding: 4px 7px !important;
} 
 </style>
 <div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12 offset-1">
                    <h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
              <ol class="breadcrumb">
                  <li class="active"><a href="<?php echo BASEPATH?>/Admindashboard">Home</a> > </li>
                  <li>Setting > </li>
                  <li>Sub Admin User</li>
  
            </ol>
<div class="clearfix">&nbsp;</div>           
<a href="<?php echo BASEPATH; ?>/Addsubadmin"><button style="float:right; margin-right:35px;" class="btn btn-default Commonbtn" type="submit">ADD SUBADMIN</button></a>  
<a href="<?php echo BASEPATH; ?>/Querytypeassign"><button style="float:right; margin-right:35px;" class="btn btn-default Commonbtn" type="submit">ASSIGN QUERY TYPE </button></a>  
				
<div class="clearfix">&nbsp;</div>

        <div class="col-lg-12 ">
      
            <div class="clearfix lightgraybg">

                <div class="bs-example table-responsive" data-example-id="bordered-table"> 

             
                     <table id="data-table-simple"  class="table table-bordered innertbl display" cellspacing="0"> 
                     <thead>
                    <tr>
                       <th class="sortdesc">SR.<br>NO </th>
                        <th class="sortboth">USERNAME</th> 
                        <th class="sortboth">EMAIL</th>
                         <th class="sortboth">MOB</th> 
                         <th class="sortboth">cREATED ON</th> 
                          <th class="sortboth">STATUS</th>
                         <th>ACTION</th> 
                           
                     </tr> 
                 </thead>
                  <tbody> 
                  <?php 
                  $j=1;
                  foreach($this->result as $result)
                  {
                  ?>
                  <tr>
                  <td><?php echo $j;?></td>
                  <td><?php echo $result['first_name'];?></td>
                  <td><?php echo $result['email'];?></td>
                   <td><?php echo $result['mob'];?></td>
                    <td><?php echo $result['created_on'];?></td>
				  <td><?php if($result['status']=='1'){?>
				  <label>Active</label>
				  <?php }else{?>
				   <label>Inactive</label>
				  <?php }?>
				  </td>
				  <td>
				  
				  <form method="post" action="<?php echo BASEPATH; ?>/Editsubadmin" name="form" id="form_edit<?php echo $result['id'];?>">
			
			
					<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
			
					<input type="hidden" value="<?php echo $result['id'];?>" id="edit_<?php echo $result['id'];?>" name="edit_id">
			
					<a href="#" onclick="edit('<?php echo $result['id'];?>')">Edit</a>
			
				</form>/
				  <form method="post" action="<?php echo BASEPATH; ?>/setpermission" name="form1" id="form_set<?php echo $result['id'];?>">
			
			
					<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
			
					<input type="hidden" value="<?php echo $result['id'];?>" id="set_<?php echo $result['id'];?>" name="setpermission_id">
			
					<a href="#" onclick="setpermission('<?php echo $result['id'];?>')">Set Permission</a>
			
				</form>
			
				</td>
				  
				  
				  
				  
				  
				  
			<!--    <td> <a href="<?php echo BASEPATH; ?>/Editsubadmin?id=<?php echo $result['id']; ?>" onclick="edit(<?php echo $result['id']; ?>)">Edit</a> /
				  <a onclick="setpermission(<?php echo $result['id']; ?>)">Set Permission</a></td>-->
                  </tr>
                  <?php $j++; }?>
                 </tbody>
                  </table> 
              </div>

        </div>

    </div>

  
	 
       <!--   <div class="col-lg-6 col-lg-offset-3 col-xs-offset-1 center-text ">
           <ul class="pagination pagination-sm">
              <li><a href="#"><img src="images/leftarw.png" alt=""></a></li>
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#"><img src="images/rightarw.png" alt=""></a> </li> 
      </ul>
    </div>-->
       
 <?php //  echo "<div align='center'>".$this->pagination($this->pagination_config)."</div>";
				//echo "<div>&nbsp;</div>";?>
				

  
   				<!--  <div class='grid-row2'>
			<div align='center' style="width:95%;font-weight:bold;">No Records Found</div>
		</div>-->
   
      
    </div>
         
      
    

   

 
     




               
             
                
          
          </div>
   <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">   
            <!-- /.row -->
            
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



    </div>
