<?php 
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); $misc_obj->generateToken();
?>
 
 <style>
 @media (min-width: 320px) and (max-width:430px){
 	.labelcls{
	 	width:100% !important;
	 }
 }
  @media (max-width:1199px){
  	.sizecls{
  	
  	}
  
  }
 @media (max-width:680px){
 	.margincls{
		margin-left: 0px !important;
		width:72% !important;
	}
	.contactcls{
	 	width:100% !important;
	}
	.col-lg-2 {
	    width: 22% !important;
	}
 }
 
 .labelcls{
 	width:50%;
 	margin-bottom: 28px;
 	float:left;
 }
 .form-control-static {
    font-weight: bold;
 }
 .contactcls{
 	width:40%;
 }
 .col-lg-2 {
    width: 10%;
 }
 .inputcls{
	width:85%;
 }
 .margincls{
	width:40%;
	float:left;
	margin-left: 15px;
 }
 </style>
 
  <div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12">
                    <h1 class="page-header gain-bit-Titletxt">Country </h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
            
              <ol class="breadcrumb">
                  <li class="active"><a href="#">Home</a></li>
                  <li>Country</li>
  
            </ol>
           
                   
					
					
					
					
					
			

         <div class="col-lg-12">
         

           

<div class="clearfix">&nbsp;</div>




<div class="clearfix">&nbsp;</div>

           <div class="panel panel-primary buynowbox col-lg-12">

              <div class="panel-heading buynowbox Titleheading faqtitlebg">
               Country Details
              </div>

              <div class="panel-body revenuebg">
     <form>

	 <div id="err_div_cont" name="err_div_cont"></div>
 <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">

  
  
  <div class="clearfix" style="float:left;">&nbsp;</div>
  <div class="form-group col-lg-2 offset-1 contactcls" style="float:left;">
	    <label for="" class="lblTxt">Country</label>
	
	    <select onchange="run(this.options[this.selectedIndex].value);"   class="myclass">
	     <option value = "">Choose country</option>
	  <?php   if(!empty($this->country['countrydata']) && sizeof($this->country['countrydata'])>0)
		{
	for($i=0;$i<sizeof($this->country['countrydata']);$i++)
	{?>
		
	  	<option value="<?php echo $this->country['countrydata'][$i]['ccode']; ?>" ><?php echo $this->country['countrydata'][$i]['country'];?></option>
	  	
	  	
	  	 <?php }
	}?>
		</select>

  </div> 
<div class="clearfix">&nbsp;</div>
 <div id="statedetails" class="form-group col-lg-2 offset-1 contactcls" style="float:left;">
	    <label for="" class="lblTxt">State</label>
	
	    <select  class="myclass">
	     <option>
	     		
	     
	     </option>
	
		</select>

  </div> 
 <div id="districtdetails" class="form-group col-lg-2 offset-1 contactcls" style="float:center;">
	    <label for="" class="lblTxt">District</label>
	
	    <select  class="myclass">
	     <option>
	     		
	     
	     </option>
	
		</select>

  </div>
 
  
  
</form>
  </div>
          </div>



         </div>

            <!-- /.row -->
            
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
	<script><!--
	function run(countryVal)
	{ //alert(id);

	var countryid=countryVal;
	
	
	 $.ajax({
			
			url:"<?php echo BASEPATH; ?>/Country/state", 
			type: "POST",    
		    data: 'countryid='+countryid,
			
	  		success:function(response)
	  		{
				
				var data=JSON.parse(response);
				var innerhtml='';	
				innerhtml+='<select onchange="clickFun(this.options[this.selectedIndex].value);">';
				innerhtml+='<option value = "">Choose state</option>';
				
				for(var k=0;k<(data['data'].length);k++)
				{
					//alert(data['data'][k]['state_id']);
					
					 innerhtml+='<option value="'+data['data'][k]['stateid']+'">'+data['data'][k]['statename']+'</option>';
					
				}
				innerhtml+='</select>';
				$('#statedetails').empty();
				//$('#districtdetails').empty();
				//$('#districtdetails').append("");
				$('#statedetails').append(innerhtml);	
				
			}
		 });
		
		
	}

	
function clickFun(val)
{
	var stateid=val;


	$.ajax({
		
		url:"<?php echo BASEPATH; ?>/Country/district", 
		type: "POST",    
	    data: 'stateid='+stateid,
		
  		success:function(response)
  		{
	  		
			var data=JSON.parse(response);
			var innerhtml='';	
			//innerhtml+='<select onchange="clickFun(this.options[this.selectedIndex].value);">';
			innerhtml+='<option value= "">Choose district</option>';
			
			//alert(data['data'][1]['districtid']);
			for(var j=0;j<(data['data'].length);j++)
			{
				 innerhtml+='<option value="'+data['data'][j]['districtid']+'">'+data['data'][j]['districtname']+'</option>';
					
			}
				
			//innerhtml+='</select>';
			$('#districtdetails').empty();
			$('#districtdetails').append(innerhtml);
	  		
		}
	 });
	
	
}
	


	
	</script>