 <?php  
	$unique = rand(1111, 9999);
?> 
<?php 
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth');
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$misc_obj->generateToken();
?>


     
 <style>
	#menu, #sample .footer ,  #sample p,.breadcrumb>li+li:before {
	  display: none;
	}
	li a:hover, a li:focus {
	  background: transparent;
	  color: #364a5e;
	}

	.accordion dl dt.pay::before {
		content: "";
	}    
</style>
	
	<div id="innerpage-wrapper">
      <div class="row lightgraybg">
        <div class="col-lg-12 offset-1">
          <h1 class="page-header gain-bit-Titletxt innpercontentPad">Make Payment</h1>
        </div>
        <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->
      <div class="row">
        <ol class="breadcrumb">
          <li><a href="<?php echo BASEPATH; ?>/Dashboard">Dashboard ></a></li>
          <li><a href="javascript:void(0)">Make Payment</a></li>

        </ol>
        <div class="accordion">

          <dl>
            <dt class="pay">Payment Details</dt>
            <dd id="payment_details" style="display:block;">
              <div class="pay-container" id="pay-container">
                <div class="pay-note">
                  <div class="pay-n">
                    Note: Kit activation may take upto 1 Hour to 24 Hours
                  </div>
                  <div class="pay-btn">
                    <input type="button" value="CHECK KIT STATUS AFTER PAYMENT" class="btn_">
                  </div>
                </div>
				<?php if(!empty($this->result['price']) && $this->result['price']>5) { ?>
				    <div  class = "message cyan">Please click on "SUBMIT AFTER PAYMENT" button or send transaction id regarding payment via contact form or send it through mail on mail id: thegainbitcoinhelp@gmail.com</div>
                <div class="row-fluid" style = "padding:20px;">

                  <div class="span12">
                    <div class="row-fluid">
                      <div>
                        <p>Please send <?php echo $price_in_btc ?> BTC to</p> 
                        <span>1EYSiRC2nUi2xLMTuwkWhHtpTTVVZ6KNrz</span>
                        <img src = "https://blockchain.info/qr?data=1EYSiRC2nUi2xLMTuwkWhHtpTTVVZ6KNrz&size=200" />
                       <div class="btn_container"><input type="button" class="btn_" value="SUBMIT AFTER PAYMENT"></div>
                       </div>
                      </div>
                    </div>
                  </div>
				<?php }else if(!empty($this->result['payment_url']) && $this->result['payment_url']!='') { ?>
                <iframe width="100%" height="100%" src="<?php echo $this->result['payment_url']; ?>" style="visibility:visible;border:0px;min-height:950px;" id="if1"></iframe>
				<?php } else {?>
					<div class = "center">
						<img src = '<?php echo BASEPATH; ?>/res/images/oops.png'> 
					</div>
				<?php } ?>

                </div>  

              </dd>
            </dl>

          </div>
        </div>
      </div>
	<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">  
	 	