<?php 
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); 
	$misc_obj->generateToken();
	
	
	/*print_r($this->contracttype);exit;*/
	?>
<style>
.innertbl th.sortboth {
    background: rgba(0, 0, 0, 0) url("../images/sort_both.png") no-repeat scroll 100% 10px;
}

.innertbl th.sortdesc {
    background: rgba(0, 0, 0, 0) url("../images/sort_desc.png") no-repeat scroll 100% 6px;
}
</style> 
 
 <div id="innerpage-wrapper">
            <div class="row lightgraybg">
                <div class="col-lg-12 offset-1">
                    <h1 class="page-header gain-bit-Titletxt innpercontentPad"></h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="row">
              <ol class="breadcrumb">
                  <li class="active"><a href="<?php echo BASEPATH; ?>/Admindashboard">Home</a> > </li>
                  <li>Contract/Hardware > </li>
                  <li>Contracts</li>
  
            </ol>
 <a class="btn btn-default Commonbtn text-uppercase"   style="float:right;margin-right:35px;"name="add" id="add" href="<?php echo BASEPATH; ?>/Addcontract" role="button">Add</a>
       
 <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token"> 
<div class="clearfix">&nbsp;</div>

        <div class="col-lg-12 ">
       
            <div class="clearfix lightgraybg">

                <div class="bs-example table-responsive" data-example-id="bordered-table"> 

             
                    <table id="data-table-simple"  class="table table-bordered innertbl display" cellspacing="0">
                     <thead>
                    <tr>
                     <th class="sortdesc">Sr.<br>No </th>
                       <th class="sortdesc">Contract Name</th>
                        <th class="sortboth">Contract Qty</th> 
                         <th class="sortboth">Total Rate</th> 
                          <th class="sortboth">Contract Type</th> 
                        <th class="sortboth">Description</th>
                         <th class="sortboth">Contract Description</th>
                        
                         <th>Action</th>
                         <th>status</th>  
                     </tr> 
                 </thead>
                  <tbody> 
                   <?php $j=1;
                   foreach($this->result as $result){?>
                   <tr>
                     <td scope="row"><?php echo $j;?></td> 
                     <td><?php echo $result['contract_name'];?></td>
                      <td><?php echo $result['contract_qty'];?></td> 
                       <td><?php echo $result['total_price'];?></td> 
                       <td><?php echo $result['contract_type'];?></td>
                      <td><?php echo $result['description'];?></td>
                       <td><?php echo $result['contract_descr'];?></td>
                     
                     <td>
                     
                     <form method="post" action="<?php echo BASEPATH; ?>/Editcontract" name="form" id="form<?php echo $result['contract_id'];?>">
			
			
					<input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
			
					<input type="hidden" value="<?php echo $result['contract_id'];?>" id="<?php echo $result['contract_id'];?>" name="contract_id">
			
					<a href="#" onclick="document.getElementById('form<?php echo $result['contract_id'];?>').submit()">Edit</a>
			
					</form>
					
					</td>
                     
                   
                     <!--  <td>
                        <a name="edit" id="edit" href="<?php echo BASEPATH; ?>/Editcontract?contract_id=<?php echo $result['contract_id'];?>" role="button">Edit</a>

                      </td>-->

                      <td>
                    <?php if($result['status']==1){?>
                    Active
                    <?php }else{?>
                    Inactive
                    <?php }?>
                     </td>
                  </tr> 

               

                

                  

               
             
             <?php $j++;}  ?>  
             
                 </tbody>
                  </table> 
              </div>

        </div>

    </div>

  
	 
       <!--   <div class="col-lg-6 col-lg-offset-3 col-xs-offset-1 center-text ">
           <ul class="pagination pagination-sm">
              <li><a href="#"><img src="images/leftarw.png" alt=""></a></li>
              <li class="active"><a href="#">1</a></li>
              <li><a href="#">2</a></li>
              <li><a href="#">3</a></li>
              <li><a href="#">4</a></li>
              <li><a href="#">5</a></li>
              <li><a href="#"><img src="images/rightarw.png" alt=""></a> </li> 
      </ul>
    </div>-->
       
 <?php  // echo "<div align='center'>".$this->pagination($this->pagination_config)."</div>";
				//echo "<div>&nbsp;</div>";?>
				

  

   
      
    </div>
         
      
   </div>
      
            <!-- /.row -->
            
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->



    </div>
