<?php $authUserNamespace = new Zend_Session_Namespace("Aranca_Auth"); ?>
<?php echo  $authUserNamespace->user11id1.$authUserNamespace->task11id1;?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href="<?php echo BASEPATH;?>/shared/style.css" rel="stylesheet" type="text/css" />
<script language="JavaScript" src="<?php echo BASEPATH;?>/shared/htmlDatePicker1.js" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/jquery-1.4.2.min.js"></script>
<script src="<?php echo BASEPATH;?>/js/jquery.alerts.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASEPATH;?>/css/jquery.alerts.css" />
<link href="<?php echo BASEPATH;?>/shared/htmlDatePicker.css" rel="stylesheet">
<script src="<?php echo BASEPATH;?>/shared/ga.js" async="" type="text/javascript"></script>
<!--<script type="text/javascript" src="<?php echo BASEPATH;?>/shared/jquery-1.js"></script>-->
<script type="text/javascript" src="<?php echo BASEPATH; ?>/js/jquery.ui.core.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/js/mootools-1.2.4-core-yc.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/js/mediaboxAdv-1.2.4.js"></script>
<link media="screen" type="text/css" href="<?php echo BASEPATH ;?>/css/mediaboxAdvWhite.css" rel="stylesheet">
<link media="screen" type="text/css" href="<?php echo BASEPATH ;?>/shared/skillboxaranca.css" rel="stylesheet"/>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/shared/skillslideraranca.js"></script>

<script>

window.onbeforeunload = function(e) {
	var isFirefox = typeof InstallTrigger !== 'undefined';
	if(isFirefox)
	{
		return  givealert();
	}
	else
	{
		return  "Please close open task before closing the browser";
	}
};

	

			/*$(window).bind('beforeunload',function(){  
				  givealert();
			});*/
			function givealert()
			{
				
						return false;
				if(confirm('Please close open task before closing the browser'))
				{
					close_window();
				}
				else
				{
					return false;
				}
			}
			function close_window() {
				window.open('', '_self', '');
				window.close();
			}
	
//window.onbeforeunload = function(e) {
//	
//	$.ajax({
//		url: "<?php echo BASEPATH; ?>/task/checksession",
//		type: "POST",    
//		data: "",
//	    success: function(response)
//	    {
//			response = response.replace(/"/g,'');
//			//alert(response);
//			response = response.replace("[","");
//			response = response.replace("]","");
//			//alert("vb"+response);
//			if(response == 'success')
//			{
//				
//				var task_id = '<?php echo $authUserNamespace->taskid1 ;?>';
//				var user_id = '<?php echo $authUserNamespace->userid1 ;?>';
//				
//				if(confirm('Please close open task before closing the browser'))
//				{
//					$.ajax({
//						url: "<?php echo BASEPATH; ?>/task/updateendtime",
//						type: "POST",    
//						data: "user_id="+user_id+"&task_id="+task_id,
//					    success: function(response)
//					    {
//							close_window();
//							return true;
//					    }
//					
//					});
//					setTimeout(function(){return true},3000);
//					//alert("call2");
//					
//				}
//				else
//				{
//					//alert("call3");
//					return false;
//				}
//			}
//			else
//			{
//				//alert('welcome');
//				return false;
//			}
//	    }
//	
//	});
//	return false;
//	
//	};
////	
//function close_window() 
//{
//	window.open('', '_self', '');
//	window.close();
//	
//}	
window.onload=function()
{
	var ptype=document.getElementById("projecttype").value;
	populate_dropdown(ptype,'1');
};
function isNumber(evt) 
{
    evt = (evt) ? evt : window.event;
    var charCode = (evt.which) ? evt.which : evt.keyCode;
    if (charCode > 31 && (charCode < 48 || charCode > 57)) {
        return false;
    }
    return true;
}

function isNumber1(evt)
{
   var charCode = (evt.which) ? evt.which : event.keyCode;
   if (charCode != 46 && charCode > 31 
     && (charCode < 48 || charCode > 57))
      return false;

   return true;
}

function view(cmd,view)
{
			if($('#taskedit_'+cmd).val() == 1)
			{
	    	window.location.href = '<?php echo BASEPATH;?>/taskpl/addselftask/id/'+cmd+'/view/'+view;
			}
			else
			{
			window.location.href = '<?php echo BASEPATH;?>/taskpl/allocatetask/id/'+cmd+'/view/'+view;
			}
}


function ed(cmd)
{
	
			if($('#taskedit_'+cmd).val() == 1)
			{
	    	window.location.href = '<?php echo BASEPATH;?>/taskpl/addselftask/id/'+cmd;
			}
			else
			{
			window.location.href = '<?php echo BASEPATH;?>/taskpl/allocatetask/id/'+cmd;
			}
}
$(document).ready(function(){
	$('.taskstart').click(function(){
		if($(this).hasClass('unable'))
		{
			$('.deleteicon').hide();
			startime($(this).attr('rel'),$(this));	
		}	
	});

	$('.taskend').click(function(){
		if($(this).hasClass('unable'))
		{
			$('.deleteicon').show();
			endtime($(this).attr('rel'),$(this));	
		}	
	});
});

function deletiontaskpl(cmd)
{
	//alert(cmd);
	jConfirm('Are you sure you want to delete the task ?', 'Delete Box', function(r) {
	    if(r){
	    	window.location.href = '<?php echo BASEPATH;?>/taskpl/deletetaskpl/id/'+cmd;
	      return true;
	    }
	    else
	      return false;
	  });
	
}

function startime(id)
{
	$(this).attr('disabled','disabled'); 
	$.ajax({
				url: "<?php echo BASEPATH; ?>/analyst/emptask",
				type: "POST",    
			    data: "id="+id,
			    success: function(response)
			    {
					response = response.replace(/"/g,'');
				    if(response != "fail")
				    {   
				    var jsonObject = JSON.parse(response);
				    var taskid = jsonObject[1]['task_id'];
				    
				    $('body').find('.Drow').each(function(){
				    	 $('.status_id').attr('disabled','disabled');
				    });
				
				    $('#status_'+id).removeAttr('disabled','disabled');

				    $('#status_'+id).find('option').each(function(){
					    if($(this).val() == '22')
					    {
						    $(this).attr('disabled','disabled'); 
					    }
					});
				    $('#checksession').val('1');
				    
				    }
				    if(response=="fail")
				    {
				    	  
					$('.deleteicon').show();
							    
							   
						
				    	$(this).removeAttr('disabled','disabled'); 
				    	jAlert('Please change the status to WIP before starting the task');
				    }
				    else
				    {
					    jAlert('Your Time has Started');
					    $('body').find('.Drow').each(function(){
						    $(this).find('.taskstart').attr('title','Play').attr('src','<?php echo BASEPATH;?>/images/common/play-disable.gif');
						    $(this).find('.taskend').attr('title','Stop').attr('src','<?php echo BASEPATH;?>/images/common/stop-disable.gif');
						});
					    $('.taskstart,.taskend').each(function(){
					    	$(this).removeClass('unable').addClass('disabled');
						});
						$('#endBtn_'+id).addClass('unable').removeClass('disabled').attr('title','Stop').attr('src','<?php echo BASEPATH;?>/images/common/stop.gif');
				    }
				    
			    }
			});
}

function endtime(id)
{
			$.ajax({
				url: "<?php echo BASEPATH; ?>/taskpl/emptaskupdate",
				type: "POST",    
			    data: "id="+id,
			    success: function(response)
			    {
					//response = response.replace(/"/g,'');
					 var jsonObject = JSON.parse(response);
					
					   
					     	$('#checksession').val('0');
						    $('body').find('.Drow').each(function(){
						    	 $('.status_id').removeAttr('disabled','disabled');
						    });

						    $('#status_'+id).removeAttr('disabled','disabled');

						    $('#status_'+id).find('option').each(function(){
							    if($(this).val() == '22')
							    {
								    $(this).attr('disabled','disabled'); 
							    }
							});

						    $('#status_'+id).find('option').each(function(){
							    if($(this).val() != 'New')
							    {
							    	$('#deleteicon_'+id).hide();
							    }
							    else
								{
							   		$('#deleteicon_'+id).show();
								}
							});
							
						    
						    var i=0;
							 
							for(;i<jsonObject.length;i++)
							{
								//alert(jsonObject[i]['id']);
								$('#status_'+jsonObject[i]['id']).attr('disabled','disabled');
							}
						
						    
					if(response='success')
				    {
					    jAlert('Your Time is Ended.Please change the Progress %.');
					   
					    $('body').find('.Drow').each(function(){
						    $(this).find('.taskstart').attr('title','Play').attr('src','<?php echo BASEPATH;?>/images/common/play.gif');
						    $(this).find('.taskend').attr('title','Stop').attr('src','<?php echo BASEPATH;?>/images/common/stop-disable.gif');
						});
					    $('.taskstart').each(function(){
					    	$(this).removeClass('disabled').addClass('unable');
						});
						$('.taskend').each(function(){
					    	$(this).removeClass('unable').addClass('disabled');
						});

						var i=0;
						 
						for(;i<jsonObject.length;i++)
						{
							 $('body').find('.Drow').each(function(){
							  $(this).find('#startBtn_'+jsonObject[i]['id']).attr('title','Play').attr('src','<?php echo BASEPATH;?>/images/common/play-disable.gif');
							  $(this).find('#startBtn_'+jsonObject[i]['id']).removeClass('unable').addClass('disabled');
								 });
						}
						
				    }
					else
					{
						jAlert('An error occurred');
					}
			    }
			});
}

function submitForm(){
	var getValue = '6';
	//alert(getValue);
	
	//var getText = document.getElementById("tasktitle").value;
	var getText1 = document.getElementById("projecttype").value;
	var getText2 = document.getElementById("projectname").value;
	var getText3 = document.getElementById("clientname").value;
	//var getText4 = document.getElementById("actualhrs").value;
	//var getText5 = document.getElementById("budgetedhrs").value;
	//var getText6 = document.getElementById("startdate").value;
	
	
//	if (getText6 != "")
//	  {
//		var positionval  = getText6.split('/');
//		if(positionval.length>1)
//			var date = positionval[2]+"-"+positionval[0]+"-"+positionval[1];
//		else
//			var date = positionval[0];
//		
//	  }
//	else
//	{
//		var date= "";
//	}
//	
//	var getText7 = document.getElementById("enddate").value;
//	if (getText7 != "")
//	  {
//		var positionval1  = getText7.split('/');
//		if(positionval1.length>1)
//			var date1 = positionval1[2]+"-"+positionval1[0]+"-"+positionval1[1];
//		else
//			var date1 = positionval1[0];
//	  }
//	else
//	{
//		var date1= "";
//	}
	//var getText8=document.getElementById("status").value;
//	if(getText8 != "")
//	{
//		if(getText1 == "")
//		{
//			jAlert('Please Select ProjectType');
//		}
//		else
//		{
//			window.location="<?php echo BASEPATH; ?>/taskpl/index/searchtext1/"+getText1+"/searchtext2/"+getText2+"/searchtext3/"+getText3+"/sortby/<?php echo $this->sortBy;?>/ord/<?php echo $this->ordVal;?>/getPageValue/"+getValue;
//		}
//		
//	}	
//	else if(getText3 != "")
//	{
//		if(getText1 == "")
//		{
//			jAlert('Please Select ProjectType');
//		}
//		else
//		{
//			window.location="<?php echo BASEPATH; ?>/taskpl/index/searchtext/"+getText+"/searchtext1/"+getText1+"/searchtext2/"+getText2+"/searchtext3/"+getText3+"/searchtext4/"+getText4+"/searchtext5/"+getText5+"/searchtext6/"+date+"/searchtext7/"+date1+"/searchtext8/"+getText8+"/sortby/<?php echo $this->sortBy;?>/ord/<?php echo $this->ordVal;?>/getPageValue/"+getValue;
//		}
//	}
//	else
//	{
		window.location="<?php echo BASEPATH; ?>/taskpl/index/searchtext1/"+getText1+"/searchtext2/"+getText2+"/searchtext3/"+getText3+"/sortby/<?php echo $this->sortBy;?>/ord/<?php echo $this->ordVal;?>/getPageValue/"+getValue;
//	}
	
	
	
}

function resetform()
{
	$('#clientname').val('');
	$('#projecttype').val('');
	$('#projectname').val('');

	window.location = '<?php echo BASEPATH; ?>/taskpl/index';
	
}
function inputfile(file)
{
	jAlert("File Uploaded Successfully");
	var upload = $('#upload1').val(file);
}

function populate_dropdown(tasktype,check)
{
	document.getElementById('cat_loader1').style.display = 'block';
	//$('#projectname').width(125);
	var counter="0";
	
	$.ajax({
		url:"<?php echo BASEPATH; ?>/taskpl/index",
		type: "POST",    
	    data: "tasktype="+tasktype,
	    success: function(response)
	    { 
		   
			j=0;
			if((response!="") && (response!=null))
			 { 
			 	var jsonObject = JSON.parse(response);
					var option_ele=document.getElementById('projectname');
					
					for(k=option_ele.length;k>0;k--)
					{
						
						option_ele.remove(k);
					}
				
					for(m=0;m<jsonObject.length;m++)
						{
						
							var option_element= new Option(jsonObject[m]['name'],jsonObject[m]['id']);
							document.getElementById('projectname').options[++j]=option_element;

							if(check=="1"){
							<?php if(isset($this->searchText2) && $this->searchText2!="")
							{?>
							var pro_ID = '<?php echo $this->searchText2;?>';
							
							if(jsonObject[m]['id']==pro_ID)
							{
								document.getElementById('projectname').options[j].selected = "selected";
							}
							<?php
							 }?>
							}
						}
					
			}
			
			document.getElementById('cat_loader1').style.display = 'none';
			//$('#projectname').width(140);
				
		}
	});
	
}


function update_status(editid,status){
	//jAlert(status);
		var counter="0";
		$.ajax({
			url:"<?php echo BASEPATH; ?>/analyst/updatestatus",
			type: "POST",    
		    data: "status="+status+"&editid="+editid,
		    success: function(response)
		    { 
			
				if((response!="") && (response!=null))
					 { 

					if($('#status_'+editid).val() == '47')
					{
						$('#status_'+editid).find('option').each(function(){
							    if($(this).val() == '22')
							    {
								    $(this).attr('disabled','disabled'); 
							    }
							});
					}
					 
					 var jsonObject = JSON.parse(response);
						
						jAlert('updated successfully');
				
					}
				
					
			}
		});
	}

	function update_progress(editid,progress){
		var counter="0";
		$.ajax({
			url:"<?php echo BASEPATH; ?>/analyst/updateprogress",
			type: "POST",    
		    data: "progress="+progress+"&editid="+editid,
		    success: function(response)
		    { 		
				
					response = response.replace(/"/g,'');
					jAlert('updated successfully');
					if((response!="") && (response!=null) && response == '46')	
					{
						endtime(editid);
						$('#status_'+editid).find('option').each(function(){
						    if($(this).val() == '23')
						    {
							    $(this).removeAttr('disabled','disabled'); 
						    }
						});
						$('#status_'+editid).val('23');
						$('#status_'+editid).attr('disabled','disabled'); 
						$('#progress_'+editid).attr('disabled','disabled');
						$('body').find('.Drow').each(function(){
							  $(this).find('#startBtn_'+editid).attr('title','Play').attr('src','<?php echo BASEPATH;?>/images/common/play-disable.gif');
							  $(this).find('#startBtn_'+editid).removeClass('unable').addClass('disabled');
								 });
						
					}
						
				
				
					
			}
		});
	}
	function Sortbydate(sortby)
	{
			document.getElementById('Sort').value = sortby;
			var date =  document.getElementById('Sort').value;
			var getValue = '6';

			var getText1 = document.getElementById("projecttype").value;
			var getText2 = document.getElementById("projectname").value;
			var getText3 = document.getElementById("clientname").value;
			
		window.location="<?php echo BASEPATH; ?>/taskpl/index/date/"+date+"/searchtext1/"+getText1+"/searchtext2/"+getText2+"/searchtext3/"+getText3+"/getPageValue/"+getValue;

			
	}		
	
function norecord()
{
	
	jAlert('No File To Download');
}

</script>
<style>
.col-first {
    float: left;
    margin: 0 20px 0 15px;
    width: 315px;
}
select.field
{
	width:144px;
}
#contentbg .frame {min-height:0;}
.disabled
{cursor:default;}
</style>
</head>
<body>
<div id="subheader">
	<div class="wrapper">
<!--	    <div id="holder">-->
<!--        	<label>Task Title</label>-->
<!--            <input name="tasktitle" id="tasktitle" type="text" value="<?php if(isset($this->searchText) && $this->searchText!=""){echo $this->searchText ;}?>" class="field" style="width:366px;"/>-->
<!--            -->
<!--        </div>-->
 		<div id="holder">
        	<label>Client Name</label>
            <select name="clientname"  id="clientname" class="field">
              <option value="">Please Select</option>
          	  <?php	foreach ($this->client as $client){?>
			  <option <?php if(isset($this->searchText3)) {if($client->id == $this->searchText3) {?> selected="selected" <?php }} ?> value="<?php  if(isset($client->id) && $client->id !=""){ echo $client->id;}?>"><?php echo $client->name;?></option>
			  <?php } ?>
            </select>
           
        </div> 
        <div id="holder" style="">
        	<label>Project Type</label>
            <select name="projecttype" id="projecttype" class="field" onchange="populate_dropdown(this.value,'0');" >
              <option <?php if(isset($this->searchText1)) {if('adhoc' == $this->searchText1) {?> selected="selected" <?php }} ?> value="adhoc">Adhoc Project</option>
              <option <?php if(isset($this->searchText1)) {if('contract' == $this->searchText1) {?> selected="selected" <?php }} ?> value="contract">Sub Project</option>
            </select>
        </div>
        <div id="holder" style="margin-right:1px;">
        	<label style="margin-left:0px;">Project Name</label>
        	<select  name="projectname" id="projectname" class="field" errortag="Project Name" <?php if(isset($this->view1) && $this->view1!= "" ){?> disabled="disabled" <?php }?>>
			<option  value="">Please select</option>
            
       		</select>
<!--            <input name="projectname" id="projectname" value="<?php if(isset($this->searchText2) && $this->searchText2!=""){echo $this->searchText2 ;}?>" type="text" class="field"/>-->
        </div>
  		<div id="cat_loader1" style="display: none; float:left;margin-top: 8px;">
			<img src="<?php echo BASEPATH;?>/images/loading19.gif">
		</div>
        <br class="clear">
<!--	<div id="holder">-->
<!--        	<label>Date</label>-->
<!--            <input name="startdate" id="startdate" type="text" class="field calendar" value="<?php if(isset($this->searchText6) && $this->searchText6!=""){echo $this->searchText6 ;}?>" id="SelectedDate" readonly onClick="GetDate(this);"/>-->
<!--            <input name="enddate"  id="enddate" type="text" class="field calendar" value="<?php if(isset($this->searchText7) && $this->searchText7!=""){echo $this->searchText7 ;}?>" id="SelectedDate" readonly onClick="GetDate(this);"/>-->
<!--   	  </div>-->
      
<!--        <div id="holder" style="margin:0">-->
<!--        	<label>Status</label>-->
<!--            <select name="status" id="status" class="field">-->
<!--              <option value="">Please Select</option>-->
<!--          	  <?php	foreach ($this->status as $status){?>-->
<!--			  <option <?php if(isset($this->searchText8)) {if($status->id == $this->searchText8) {?> selected="selected" <?php }} ?> value="<?php  if(isset($status->id) && $status->id !=""){ echo $status->id;}?>"><?php echo $status->value;?></option>-->
<!--			  <?php } ?>-->
<!--            </select>-->
<!--        </div>-->
<!--	<br class="clear">-->
<!--        <div id="holder">-->
<!--        	<label>Actual Hours</label>-->
<!--            <input name="actualhrs" id="actualhrs" type="text" onkeypress="return isNumber1(event)" value="<?php if(isset($this->searchText4) && $this->searchText4!=""){echo $this->searchText4 ;}?>" class="field"/>-->
<!--        </div>-->
<!--  		<div id="holder">-->
<!--        	<label>Budgeted Hours</label>-->
<!--            <input name="budgetedhrs" id="budgetedhrs" type="text" onkeypress="return isNumber(event)" value="<?php if(isset($this->searchText5) && $this->searchText5!=""){echo $this->searchText5 ;}?>" class="field"/>-->
<!--        </div>-->
        
        <br class="clear">
  		<div class="flow_right"><a href="#" class="searchbg" onclick="javascript:submitForm();">Search</a></div>
  		<div class="flow_right"><a style="margin-right:17px;" class="searchbg" href="#" onclick="javascript:resetform();">Reset</a></div>
  	</div>
    <br class="clear" />
</div>
<div id="contentbg">
	<div class="frame">
    	<br class="clear">
    	<!--Starts Here -->
   	  <div class="wrapper">
   	    <div class="flow_right">
   	     <a href="<?php echo BASEPATH;?>/taskpl/allocatetask" class="createbg" style="margin-right:32px;">Allocate Task</a>
   	    <a href="<?php echo BASEPATH;?>/taskpl/addselftask" class="createbg">Create Self Task</a>
   	   
   	    </div>
        <br class="clear">
        <br class="clear">

        
        <div id="tablebg">
        	<div class="col-first" style="width:487px;">Task Title</div>
            <div class="col">&nbsp;</div>
            <div class="col" style="width:103px;">&nbsp;</div>
         	<input type="hidden" name="Sort" id="Sort">
            <div class="col" style="width:64px;margin-left:0px">Start Date<div style="float:left; margin-left: 64px;margin-top: -13px; cursor:pointer; width:30px;"><img  src="<?php echo BASEPATH;?>/images/common/sorting_date1.gif" border="1" onclick="Sortbydate(2);" title="Sort" /><div style="float:left; margin-left: 0px; cursor:pointer;"><img  src="<?php echo BASEPATH;?>/images/common/sorting_date.gif" border="1" onclick="Sortbydate(1);" title="Sort" /></div></div></div>
            <div class="col" style="width:64px;margin-left:9px"">End Date<div style="float:left;margin-left: 64px;margin-top: -13px; cursor:pointer; width:30px;"><img  src="<?php echo BASEPATH;?>/images/common/sorting_date1.gif" border="1" onclick="Sortbydate(3);" title="Sort"  /><div style="float:left; margin-left: 0px; cursor:pointer;"><img  src="<?php echo BASEPATH;?>/images/common/sorting_date.gif" border="1" onclick="Sortbydate(0);" title="Sort" /></div></div></div> 
          
        </div>
         <?php if(isset($this->final_result) && sizeof($this->final_result)>0){
         ?>
        
         <?php $i=0;foreach ($this->final_result as $tasklist){
 					
      		 		$taskObj = new Aranca_Model_DbTable_Task();
					$clientObj= new Aranca_Model_DbTable_Client();
					$emp_taskObj = new Aranca_Model_DbTable_Emptask();
					
						//$where.= "  et.task_id ='$tasklist[$i]['editid']'";
						$id =$tasklist['editid'];
					 
					$listing = $emp_taskObj->fetchAll($emp_taskObj->select()
										->setIntegrityCheck(false)
											->from(array('et'=>DATABASE_PREFIX."emp_task"),array('et.id as editid','et.task_id as task_id','et.st_time as st_time','et.end_time as end_time'))
											->where("et.task_id =$id")
										);
										
										
					$hours=0;
					$totalhours=0;	
					$totalminits=0;
					$result="0.0";							
					foreach ($listing as $list)
					{	if(isset($list->st_time) && $list->st_time!="" && $list->st_time!="0000-00-00 00:00:00" && isset($list->end_time) && $list->end_time!="" && $list->end_time!="0000-00-00 00:00:00")
					{								
						$date_a = new DateTime($list['st_time']);
						$date_b = new DateTime($list['end_time']);	
						$diff=$date_b->diff($date_a);
						$hours=$diff->h;
						$minits=$diff->i;
						$totalminits+=$minits;
						$totalhours+=$hours+($diff->d*24);	
						
					}				
					} 
       			if($totalminits>60)
					 {
					 	$hrs=$totalminits/60;
					 	$hrs = $hrs; 
					 	$minit=$totalminits%60;
					 	$minit =$minit;
					 	$totalhours+=$hrs;
					 	$min1 = 0;
					 	if($totalminits >9)
						{
						 
				           $result=$totalhours.".".$minit;
						}
						else 
						{
						$result=$totalhours.".".$min1.$minit;	
						}
					 	
					 	//echo $result;
					 }
						else
					{
						$min = 0;
						if($totalminits >9)
						{
						 
				           $result=$totalhours.".".$totalminits;
						}
						else 
						{
						$result=$totalhours.".".$min.$totalminits;	
						}
					}
					
					$actual_hour =$result;
					
       		 ?>
         
  
        <div id="rowbg" class="Drow">
   	  	  <div class="col-first" style="width:487px;"><a onclick="view(<?php echo $tasklist['editid'];?>,'view')" href="javascript:void(0)"><?php if(isset($tasklist['title']) && $tasklist['title'] !=""){echo $tasklist['title'];} ?> </a><br><span style="color:black;font-weight:normal;text-decoration:none;" ><?php if($tasklist['project_type'] == "contract"){ if(isset($tasklist['title1'])&& $tasklist['title1']!=""){echo $tasklist['title1'];}?> (S) <?php } else{if(isset($tasklist['title1'])&& $tasklist['title1']!=""){echo $tasklist['title1'];}?> (A) <?php } ?> | <?php if($tasklist['project_type'] == "contract"){ if(isset($tasklist['name1'])&& $tasklist['name1']!=""){echo $tasklist['name1'];}}else{if(isset($tasklist['name1'])&& $tasklist['name1']!=""){echo $tasklist['name1'];}} ?></span><br>Budgeted Hrs: <?php if(isset($tasklist['budgeted_hrs']) && $tasklist['budgeted_hrs'] !=""){echo $tasklist['budgeted_hrs'];}?>   |  Actual Hrs: <?php echo $actual_hour;?>   | 
   	  	   Status: <select class="status_id" <?php if(isset($authUserNamespace->taskid1) && $authUserNamespace->taskid1!=""){
	             if($tasklist['editid'] != $authUserNamespace->taskid1 ){
	             	
	             	 ?>disabled<?php }}?> id="status_<?php echo $tasklist['editid']; ?>" name="practice" onchange="update_status(<?php echo $tasklist['editid'];?>,this.value);" <?php if(isset($tasklist['status_id']) && $tasklist['status_id']!="" && $tasklist['status_id']==23){?> disabled="disabled" <?php }?>>
               <option  selected="selected"  value=""> Select</option>
                <?php	foreach ($this->status_list as $status_list){?>
			  <option <?php if(isset($authUserNamespace->taskid1) && $authUserNamespace->taskid1!=""){
	             if($tasklist['editid'] == $authUserNamespace->taskid1 ){
	             	if(isset($status_list->id) && $status_list->id !="" && isset($status_list->id) && $status_list->id =='22') {
	             	 ?>disabled<?php }}}?>
	             	 <?php if($tasklist['status_id'] == '47'){ ?>
	             	  <?php if(isset($status_list->id) && $status_list->id !="" && $status_list->id == '22'){?>disabled<?php }?>
	             	 <?php }?> 
	             	 <?php if($tasklist['progress_id'] != '46'){?>
	             	 <?php if(isset($status_list->id) && $status_list->id !="" && $status_list->id == '23'){?>disabled<?php } }?>
	             	 value="<?php  if(isset($status_list->id) && $status_list->id !=""){ echo $status_list->id;}?>"<?php if($tasklist['status_id']==$status_list->id) echo "selected";?> ><?php echo $status_list->value;?></option>
			  <?php } ?>
<!--              <option>Open</option>-->
<!--              <option>Completed</option>-->
            </select>   Progress %: <select class="progress_<?php echo $tasklist['editid'];?>" id="progress_<?php echo $tasklist['editid'];?>" name="practice" onchange="update_progress(<?php echo $tasklist['editid'];?>,this.value);" <?php if(isset($tasklist['progress_id']) && $tasklist['progress_id']!="" && $tasklist['progress_id']==46){?> disabled="disabled" <?php }?>>
            	<option selected="selected" value=""> Select</option>
              <?php	foreach ($this->progress_list as $progress_list){?>
			  <option value="<?php  if(isset($progress_list->id) && $progress_list->id !=""){ echo $progress_list->id;}?>"<?php if($tasklist['progress_id']==$progress_list->id) echo "selected";?>><?php echo $progress_list->value;?></option>
			  <?php } ?>
            </select>
   	  	  
   	  	  
   	  	  
<!--   	  	   Status:<?php if(isset($tasklist->value1) && $tasklist->value1 !=""){echo $tasklist->value1;}  ?>-->
            </div>
            <div class="col" style="width:127px;;">
	            
	             <a rel="<?php echo BASEPATH ;?>/task/uploadfile/id/<?php echo $tasklist['editid'];?>" href="javascript:void(0);" id="upload" class="openskillbox"><img border="0" title="Upload" src="<?php echo BASEPATH;?>/images/common/up.gif"></a>
	            
	         <a <?php if(isset($tasklist['file_path']) && $tasklist['file_path'] !="") {?> target="_blank" href="<?php echo BASEPATH;?><?php echo $tasklist['file_path'] ;?>" <?php }else {?> href="javascript:norecord();"<?php }?> >
            <?php if(isset($tasklist['file_path']) && $tasklist['file_path']!="") {?><img title="Download" title="Download" src="<?php echo BASEPATH;?>/images/common/down.gif" border="0" /><?php }else {?><img title="Download" title="Download" class="disabled" src="<?php echo BASEPATH;?>/images/common/down-disable.gif" border="0" /><?php }?></a>
<!--	            <a  <?php if(isset($tasklist->file_path) && $tasklist->file_path !="") {?> target="_blank" href="<?php echo BASEPATH;?><?php echo $tasklist[$i]['file_path'] ;?>" <?php }else {?>href="javascript:norecord();"<?php }?> >-->
<!--	            <img title="Download" src="<?php echo BASEPATH;?>/images/common/d.gif" border="0" /></a> -->
				<?php if(isset($tasklist['status_id']) && $tasklist['status_id']!="" && $tasklist['status_id']==23) {
				?>
				<a href="javascript:void(0)"><img id="startBtn_<?php echo $tasklist['editid'];?>" class="taskstart disabled" src="<?php echo BASEPATH;?>/images/common/play-disable.gif" title="Play" border="0"  /></a> 
	            <a href="javascript:void(0)"><img id="endBtn_<?php echo $tasklist['editid'];?>" class="taskend disabled" src="<?php echo BASEPATH;?>/images/common/stop-disable.gif" title="Stop"  border="0" /></a>
	           <?php }else {
	             if((isset($authUserNamespace->taskid1) && $authUserNamespace->taskid1!="" )||( isset($authUserNamespace->task11id1) && $authUserNamespace->task11id1!="")){
	             if($tasklist['editid'] == $authUserNamespace->taskid1 || $tasklist['editid'] == $authUserNamespace->task11id1){
	             ?>
	            <a href="#"><img id="startBtn_<?php echo $tasklist['editid'];?>" class="taskstart disabled" src="<?php echo BASEPATH;?>/images/common/play-disable.gif" title="Play" border="0" rel="<?php echo $tasklist['editid'];?>" /></a> 
	            <a href="#"><img id="endBtn_<?php echo $tasklist['editid'];?>" class="taskend unable" src="<?php echo BASEPATH;?>/images/common/stop.gif" title="Stop" rel="<?php echo $tasklist['editid'];?>" border="0" /></a>
            	<?php  }else{
            	?>
            	<a href="#"><img id="startBtn_<?php echo $tasklist['editid'];?>" class="taskstart disabled" src="<?php echo BASEPATH;?>/images/common/play-disable.gif" title="Play" border="0" rel="<?php echo $tasklist['editid'];?>" /></a> 
	            <a href="#"><img id="endBtn_<?php echo $tasklist['editid'];?>" class="taskend disabled" src="<?php echo BASEPATH;?>/images/common/stop-disable.gif" title="Stop" rel="<?php echo $tasklist['editid'];?>" border="0" /></a>
            	<?php }}else{?>
            	<a href="#"><img id="startBtn_<?php echo $tasklist['editid'];?>" class="taskstart unable" src="<?php echo BASEPATH;?>/images/common/play.gif" title="Play" border="0" rel="<?php echo $tasklist['editid'];?>" /></a> 
	            <a href="#"><img id="endBtn_<?php echo $tasklist['editid'];?>" class="taskend disabled" src="<?php echo BASEPATH;?>/images/common/stop-disable.gif" title="Stop" rel="<?php echo $tasklist['editid'];?>" border="0" /></a>
            	<?php } 
	           }?>
            </div>
            <div class="col" style="width:60px;text-align:left;">
           
               <?php if(isset($tasklist['member_id']) && $tasklist['member_id'] !="" && $tasklist['member_id']== $authUserNamespace->id  && $tasklist['allocate_id']== '0'){?>
	            <a href="#"><img src="<?php echo BASEPATH;?>/images/common/edit.gif" border="0" onclick="ed(<?php echo $tasklist['editid'];?>)"   /></a> &nbsp; 
               <?php }else if(isset($tasklist['allocate_id']) && $tasklist['allocate_id'] !="" && $tasklist['allocate_id']== $authUserNamespace->id ){?>
           			<a href="#"><img src="<?php echo BASEPATH;?>/images/common/edit.gif" border="0" onclick="ed(<?php echo $tasklist['editid'];?>)"   /></a> &nbsp; 
<!--            <a href="#"><img src="<?php echo BASEPATH;?>/images/common/view.gif" border="0" onclick="view(<?php echo $tasklist->editid;?>,'view')"/></a>-->
          <?php  }?>
          
         
          
          
          
          <?php if(isset($tasklist['member_id']) && $tasklist['member_id'] !="" && $tasklist['member_id']== $authUserNamespace->id  && $tasklist['allocate_id']== '0'){?>
	            <a href="#"><img id="deleteicon_<?php echo $tasklist['editid']; ?>" class="deleteicon" src="<?php echo BASEPATH;?>/images/cross.png" border="0" onclick="deletiontaskpl(<?php echo $tasklist['editid'];?>)"   /></a> &nbsp; 
               <?php }else if(isset($tasklist['allocate_id']) && $tasklist['allocate_id'] !="" && $tasklist['allocate_id']== $authUserNamespace->id ){?>
           			<a href="#"><img id="deleteicon_<?php echo $tasklist['editid']; ?>" class="deleteicon" src="<?php echo BASEPATH;?>/images/cross.png" border="0" onclick="deletiontaskpl(<?php echo $tasklist['editid'];?>)"   /></a> &nbsp; 
<!--            <a href="#"><img  src="<?php echo BASEPATH;?>/images/common/view.gif" border="0" onclick="view(<?php echo $tasklist->editid;?>,'view')"/></a>-->
          <?php  }?>
            
            
            </div>
            
            <div class="col" style="width:64px;"><?php if(isset($tasklist['st_date']) && $tasklist['st_date'] !=""){echo $tasklist['st_date'];}?></div>
            <div class="col" style="width:64px; margin-left:12px;"><?php if(isset($tasklist['end_date']) && $tasklist['end_date'] !=""){echo $tasklist['end_date'];}?></div>
            <input type="hidden" id="taskedit_<?php echo $tasklist['editid'];?>" <?php if(isset($tasklist['member_id']) && $tasklist['member_id'] !="" && $tasklist['member_id']== $authUserNamespace->id && isset($tasklist['allocate_id']) && $tasklist['allocate_id'] == 0  ){?> value="1" <?php }else{?>value=0<?php }?>/>
            <br class="clear">
          </div>
          <?php $i++; } 
          echo "<div class='pagination'>".$this->pagination($this->pagination_config)."</div>";
				//echo "<div>&nbsp;</div>";
         } else {?>
         <div class='grid-row2'>
		<div align='center' style="width:95%;font-weight:bold;">No Records Found</div>
		</div>
         <?php  } ?>
          
        <!-- <div class="pagination"><a href="#" class="active">1</a> <a href="#">2</a> <a href="#">3</a> <a href="#">4</a> <a href="#">Next</a></div> -->
      </div>
        <!--Ends Here -->
    </div>
</div>
<script>
var project_type ='';
<?php if(isset($this->searchText1) && $this->searchText1!=""){?>
project_type='<?php echo $this->searchText1?>';
<?php } ?>


</script>
</body>
<script >
$(document).ready(function(){
	<?php 

		      if(isset($authUserNamespace->status_message)){
		      	
		?>
		   jAlert("<?php echo $authUserNamespace->status_message; ?>");
		 
		      
		<?php
		  unset($authUserNamespace->status_message);
		}
		?>
});
</script>