<?php $authUserNamespace = new Zend_Session_Namespace("Aranca_Auth"); ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Aranca: Research.Analyze.Communicate</title>
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/crud.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/jquery-1.4.2.min.js"></script>
<script language="JavaScript" src="<?php echo BASEPATH;?>/shared/htmlDatePicker1.js" type="text/javascript"></script>
<link href="<?php echo BASEPATH;?>/shared/htmlDatePicker.css" rel="stylesheet" />
<script src="<?php echo BASEPATH;?>/js/jquery.alerts.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASEPATH;?>/css/jquery.alerts.css" />
<link rel="stylesheet" type="text/css"  href="<?php echo BASEPATH;?>/shared/style.css" />
<!--<script type="text/javascript" src="<?php echo BASEPATH;?>/shared/jquery-1.js"></script>
--><script type="text/javascript" src="<?php echo BASEPATH; ?>/js/jquery.ui.core.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/js/mootools-1.2.4-core-yc.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/js/mediaboxAdv-1.2.4.js"></script>
<link media="screen" type="text/css" href="<?php echo BASEPATH ;?>/css/mediaboxAdvWhite.css" rel="stylesheet"/>

<link media="screen" type="text/css" href="<?php echo BASEPATH ;?>/shared/skillboxaranca.css" rel="stylesheet"/>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/shared/skillslideraranca.js"></script>

<script type="text/javascript">

$(document).ready(function(){
	var totalQty = 0;
	var price = 0;
	
	$('#rowbg .col1').each(function(){
		if($(this).text()!="" && $(this).text()!= "-")
		totalQty = totalQty+parseFloat($(this).text());
		var total1 = parseFloat(totalQty).toFixed(2);
		$('#total').html(total1);
		//$('#total').html(totalQty);
		//price = price+(parseInt($(this).text())*parseInt($(this).next().find('.price').text()));
		$('#Tqty').html(totalQty);
		
		//$('#finPrice').html(price);
	});
	$('#rowbg .col1').each(function(){
		if($(this).text()!="" && $(this).text()!= 0  && $(this).text()!= "-")
		{
			var t = parseFloat(parseFloat($(this).text())/totalQty).toFixed(2);
			var t1 = parseFloat(t * 100).toFixed();
			//var t1 = parseFloat(t * 100).toFixed(2);
			$(this).next().text(t1+'%');
		}
		else
		{
			$(this).next().text("-");
		}
	});
});

	function search()
	{	
		
		var startdate=document.getElementById('startdate').value;
		if (startdate != "")
		  {
			var positionval  = startdate.split('/');
			startdate = positionval[2]+"-"+positionval[0]+"-"+positionval[1];
			
		  }
		else
		{
			var startdate= "";
		}
		//alert(startdate);
		var enddate=document.getElementById('enddate').value;
		if (enddate != "")
		  {
			var positionval1  = enddate.split('/');
			enddate = positionval1[2]+"-"+positionval1[0]+"-"+positionval1[1];
		  }
		else
		{
			enddate= "";
		}
		
		window.location="<?php echo BASEPATH; ?>/taskpl/practicelevelreportannualc/startdate/"+startdate+"/enddate/"+enddate;
	}


	function export1()
	{	
		
		var startdate=document.getElementById('startdate').value;
		if (startdate != "")
		  {
			var positionval  = startdate.split('/');
			startdate = positionval[2]+"-"+positionval[0]+"-"+positionval[1];
			
		  }
		else
		{
			var startdate= "";
		}
		//alert(startdate);
		var enddate=document.getElementById('enddate').value;
		if (enddate != "")
		  {
			var positionval1  = enddate.split('/');
			enddate = positionval1[2]+"-"+positionval1[0]+"-"+positionval1[1];
		  }
		else
		{
			enddate= "";
		}
		
		window.location="<?php echo BASEPATH; ?>/taskpl/exportpracticelevelreportannualc/startdate/"+startdate+"/enddate/"+enddate;
	}
</script>


<script>

	
</script>
<style>
.col-first {
    width: 315px;
}
.greenClass
{
	background-repeat:repeat-x;
	background-color:#8EC555;
    height: 32px;
    margin: -8px 0 0;
    padding: 8px 0 0;
    background-image:url("<?php echo BASEPATH ;?>/images/common/menubg-grn.gif");
}
</style>

</head>
<body>
<div id="subheader">
	<form id="searchprojectform" name="searchprojectform" action="" method="post">
	<div class="wrapper">
	<div id="holder" style="margin:0;">
        	<label>From Date<em>*</em></label>
            <input name="startdate" id="startdate" type="text" class="field calendar" value="<?php if(isset($this->startdate) && $this->startdate!=""){echo $this->startdate; } ?>" id="SelectedDate" readonly onClick="GetDate(this);"/>
            <label>To Date<em>*</em></label>
            <input name="enddate" id="enddate" type="text" class="field calendar" value="<?php if(isset($this->enddate) && $this->enddate!=""){echo $this->enddate; }?>" id="SelectedDate" readonly onClick="GetDate(this);"/>
      </div>
      <br class="clear">
       <br class="clear" />
	
      <br class="clear">
        <br class="clear">
  		<div class="flow_right" style="margin:0 10px 0 0" onclick="export1();"><a href="javascript:void(0);" class="searchbg">Export</a></div>
  		<div class="flow_right" style="margin:0 10px 0 0" onclick="search();"><a href="javascript:void(0);" class="searchbg">Submit</a></div>
  		<div class="flow_right" style="margin:0 10px 0 0"><a href="<?php echo BASEPATH?>/taskpl/reportscreenindex" style="margin-right:532px;" class="searchbg">Report-homepage</a></div>
  	</div>
    <br class="clear" />
    </form>
</div>
<div id="contentbg">
	<div class="frame">
    	<br class="clear">
    	<!--Starts Here -->
   	  <div class="wrapper">

        <br class="clear">
        <br class="clear">
      
     
   
    <br class="clear">
       <div id="tablebg" style=" height: 40px;">
        	<div class="col-first" style="width:130px;">Summary</div>
        	<div class="col" style="width:155px;">Analyst/Associate</div>
            <div class="col" style="width:100px;">Associate Vice President</div>
            <div class="col" style="width:100px;">Editorial</div>
            <div class="col" style="width:100px;">Others</div>
            <div class="col" style="width:100px;">Project Managers</div>
            <div class="col" style="width:100px;">Senior Research Analyst</div>
        </div>
        
      <div id="rowbg">
        <div class="col-first" style="width:130px;">Total Hrs in office</div>
        	<div class="col" style="width:155px;"><?php if(isset($this->type1_final_result['totalHrInOffice'])) echo $this->type1_final_result['totalHrInOffice'];?></div>
            <div class="col" style="width:100px;"><?php if(isset($this->type2_final_result['totalHrInOffice'])) echo $this->type2_final_result['totalHrInOffice'];?></div>
            <div class="col" style="width:100px;"><?php if(isset($this->type3_final_result['totalHrInOffice'])) echo $this->type3_final_result['totalHrInOffice'];?></div>
            <div class="col" style="width:100px;"><?php if(isset($this->type4_final_result['totalHrInOffice'])) echo $this->type4_final_result['totalHrInOffice'];?></div>
             <div class="col" style="width:100px;"><?php if(isset($this->type5_final_result['totalHrInOffice'])) echo $this->type5_final_result['totalHrInOffice'];?></div>
              <div class="col" style="width:100px;"><?php if(isset($this->type6_final_result['totalHrInOffice'])) echo $this->type6_final_result['totalHrInOffice'];?></div>
            
        </div> 
        
        <div id="rowbg">
        <div class="col-first" style="width:130px;">Chargeable Hrs(A)</div>
        	<div class="col" style="width:155px;"><?php if(isset($this->type1_final_result['chargeablehrs'])) echo $this->type1_final_result['chargeablehrs'];?></div>
            <div class="col" style="width:100px;"><?php if(isset($this->type2_final_result['chargeablehrs'])) echo $this->type2_final_result['chargeablehrs'];?></div>
            <div class="col" style="width:100px;"><?php if(isset($this->type3_final_result['chargeablehrs'])) echo $this->type3_final_result['chargeablehrs'];?></div>
            <div class="col" style="width:100px;"><?php if(isset($this->type4_final_result['chargeablehrs'])) echo $this->type4_final_result['chargeablehrs'];?></div>
             <div class="col" style="width:100px;"><?php if(isset($this->type5_final_result['chargeablehrs'])) echo $this->type5_final_result['chargeablehrs'];?></div>
              <div class="col" style="width:100px;"><?php if(isset($this->type6_final_result['chargeablehrs'])) echo $this->type6_final_result['chargeablehrs'];?></div>
            
        </div>  
        <div id="rowbg">
        <div class="col-first" style="width:130px;">Non Chargeable Hrs(B)</div>
        	<div class="col" style="width:155px;"><?php if(isset($this->type1_final_result['nonchargeablehrs'])) echo $this->type1_final_result['nonchargeablehrs'];?></div>
            <div class="col" style="width:100px;"><?php if(isset($this->type2_final_result['nonchargeablehrs'])) echo $this->type2_final_result['nonchargeablehrs'];?></div>
            <div class="col" style="width:100px;"><?php if(isset($this->type3_final_result['nonchargeablehrs'])) echo $this->type3_final_result['nonchargeablehrs'];?></div>
            <div class="col" style="width:100px;"><?php if(isset($this->type4_final_result['nonchargeablehrs'])) echo $this->type4_final_result['nonchargeablehrs'];?></div>
             <div class="col" style="width:100px;"><?php if(isset($this->type5_final_result['nonchargeablehrs'])) echo $this->type5_final_result['nonchargeablehrs'];?></div>
              <div class="col" style="width:100px;"><?php if(isset($this->type6_final_result['nonchargeablehrs'])) echo $this->type6_final_result['nonchargeablehrs'];?></div>
            
        </div>  
        <div id="rowbg">
        <div class="col-first" style="width:130px;">Rework Hrs</div>
        	<div class="col" style="width:155px;"><?php if(isset($this->type1_final_result['reworkhrs'])) echo $this->type1_final_result['reworkhrs'];?></div>
            <div class="col" style="width:100px;"><?php if(isset($this->type2_final_result['reworkhrs'])) echo $this->type2_final_result['reworkhrs'];?></div>
            <div class="col" style="width:100px;"><?php if(isset($this->type3_final_result['reworkhrs'])) echo $this->type3_final_result['reworkhrs'];?></div>
            <div class="col" style="width:100px;"><?php if(isset($this->type4_final_result['reworkhrs'])) echo $this->type4_final_result['reworkhrs'];?></div>
             <div class="col" style="width:100px;"><?php if(isset($this->type5_final_result['reworkhrs'])) echo $this->type5_final_result['reworkhrs'];?></div>
              <div class="col" style="width:100px;"><?php if(isset($this->type6_final_result['reworkhrs'])) echo $this->type6_final_result['reworkhrs'];?></div>
            
        </div>  
        <div id="rowbg">
        <div class="col-first" style="width:130px;">Chargeable Hrs %</div>
        	<div class="col" style="width:155px;"><?php if(isset($this->type1_final_result['chargeableHrsPerc'])) echo $this->type1_final_result['chargeableHrsPerc'];?></div>
            <div class="col" style="width:100px;"><?php if(isset($this->type2_final_result['chargeableHrsPerc'])) echo $this->type2_final_result['chargeableHrsPerc'];?></div>
            <div class="col" style="width:100px;"><?php if(isset($this->type3_final_result['chargeableHrsPerc'])) echo $this->type3_final_result['chargeableHrsPerc'];?></div>
            <div class="col" style="width:100px;"><?php if(isset($this->type4_final_result['chargeableHrsPerc'])) echo $this->type4_final_result['chargeableHrsPerc'];?></div>
             <div class="col" style="width:100px;"><?php if(isset($this->type5_final_result['chargeableHrsPerc'])) echo $this->type5_final_result['chargeableHrsPerc'];?></div>
              <div class="col" style="width:100px;"><?php if(isset($this->type6_final_result['chargeableHrsPerc'])) echo $this->type6_final_result['chargeableHrsPerc'];?></div>
            
        </div>  
       
<!--        <div class="pagination"><a href="#" class="active">1</a> <a href="#">2</a> <a href="#">3</a> <a href="#">4</a> <a href="#">Next</a></div>-->
      </div>
        <!--Ends Here -->
    </div>
</div>
</body>
<script>

</script>
</html>