<?php $authUserNamespace = new Zend_Session_Namespace("Aranca_Auth"); ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Aranca: Research.Analyze.Communicate</title>
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/crud.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/jquery-1.4.2.min.js"></script>
<script language="JavaScript" src="<?php echo BASEPATH;?>/shared/htmlDatePicker1.js" type="text/javascript"></script>
<link href="<?php echo BASEPATH;?>/shared/htmlDatePicker.css" rel="stylesheet" />
<script src="<?php echo BASEPATH;?>/js/jquery.alerts.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASEPATH;?>/css/jquery.alerts.css" />
<link rel="stylesheet" type="text/css"  href="<?php echo BASEPATH;?>/shared/style.css" />
<!--<script type="text/javascript" src="<?php echo BASEPATH;?>/shared/jquery-1.js"></script>
--><script type="text/javascript" src="<?php echo BASEPATH; ?>/js/jquery.ui.core.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/js/mootools-1.2.4-core-yc.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/js/mediaboxAdv-1.2.4.js"></script>
<link media="screen" type="text/css" href="<?php echo BASEPATH ;?>/css/mediaboxAdvWhite.css" rel="stylesheet"/>

<link media="screen" type="text/css" href="<?php echo BASEPATH ;?>/shared/skillboxaranca.css" rel="stylesheet"/>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/shared/skillslideraranca.js"></script>
<style>
.col-first {
    width: 315px;
}
.greenClass
{
	background-repeat:repeat-x;
	background-color:#8EC555;
    height: 32px;
    margin: -8px 0 0;
    padding: 8px 0 0;
    background-image:url("<?php echo BASEPATH ;?>/images/common/menubg-grn.gif");
}


.col a {
    color: rgb(30, 89, 159);
    font-weight: bold;
    text-decoration: underline;
     
}
.col {
 width: 100%;
 margin-left: 354px;
 text-align: left;
 margin-bottom: 5px;
}
</style>

</head>
<body>

<div id="contentbg">
	<div class="frame" style="height: 606px;">
    	<br class="clear">
    	<!--Starts Here -->
   	  <div class="wrapper">

        <br class="clear">
        <br class="clear">
       
  		<div class="col"><a href="<?php echo BASEPATH;?>/taskpl/reportscreen">Individual time spent report(Date Range)</a></div>
  		<div class="col"><a href="<?php echo BASEPATH;?>/taskpl/pwtimespentreport">Practice time spent report(Date Range)</a></div>
  		<div class="col"><a href="<?php echo BASEPATH;?>/taskpl/projectwisedetail">Project wise detailed report</a></div>
  		<div class="col"><a href="<?php echo BASEPATH;?>/taskpl/openprojects">Open projects summary report(By Milestone)</a></div>
  		<div class="col"><a href="<?php echo BASEPATH;?>/taskpl/capacityutilizationweekly">Capacity utilization weekly summary report</a></div>
  		<div class="col"><a href="<?php echo BASEPATH;?>/taskpl/reportcapacityutilizationbyanalyst">Capacity utilization by Analyst</a></div>
  		<div class="col"><a href="<?php echo BASEPATH;?>/taskpl/practicelevelreportap">Practice level summary report - Adhoc Projects</a></div>
  		<div class="col"><a href="<?php echo BASEPATH;?>/taskpl/practicelevelreportannualc">Practice level summary report - Annual Contracts</a></div>
  		<div class="col"><a href="<?php echo BASEPATH;?>/taskpl/profitabiltyclosedprojects">Profitabilty report(Adhoc Projects) - closed projects</a></div>
  		<div class="col"><a href="<?php echo BASEPATH;?>/taskpl/profitabiltyopenprojects">Profitabilty report(Adhoc Projects) - open projects</a></div>
       </div> 
 
        
        
       
<!--        <div class="pagination"><a href="#" class="active">1</a> <a href="#">2</a> <a href="#">3</a> <a href="#">4</a> <a href="#">Next</a></div>-->
      </div>
        <!--Ends Here -->
    </div>
</div>
</body>
<script>

</script>
</html>