<?php $authUserNamespace = new Zend_Session_Namespace("Aranca_Auth"); ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Aranca: Research.Analyze.Communicate</title>
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/crud.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/jquery-1.4.2.min.js"></script>
<script language="JavaScript" src="<?php echo BASEPATH;?>/shared/htmlDatePicker1.js" type="text/javascript"></script>
<link href="<?php echo BASEPATH;?>/shared/htmlDatePicker.css" rel="stylesheet" />
<script src="<?php echo BASEPATH;?>/js/jquery.alerts.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASEPATH;?>/css/jquery.alerts.css" />
<link rel="stylesheet" type="text/css"  href="<?php echo BASEPATH;?>/shared/style.css" />
<!--<script type="text/javascript" src="<?php echo BASEPATH;?>/shared/jquery-1.js"></script>
--><script type="text/javascript" src="<?php echo BASEPATH; ?>/js/jquery.ui.core.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/js/mootools-1.2.4-core-yc.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/js/mediaboxAdv-1.2.4.js"></script>
<link media="screen" type="text/css" href="<?php echo BASEPATH ;?>/css/mediaboxAdvWhite.css" rel="stylesheet"/>

<link media="screen" type="text/css" href="<?php echo BASEPATH ;?>/shared/skillboxaranca.css" rel="stylesheet"/>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/shared/skillslideraranca.js"></script>

<script type="text/javascript">


$(document).ready(function(){
	var totalQty = 0;
	var price = 0;
	
	$('#rowbg .col1').each(function(){
		if($(this).val()!="" && $(this).val()!="-" )
		totalQty = totalQty+parseInt($(this).val());
		
		
	});
	$('#rowbg .col1').each(function(){
		
		if($(this).val()!="" && $(this).val() != "-" && totalQty !="" && totalQty!= 0)
		{
			var t = parseFloat(parseInt($(this).val())/totalQty);
			var t1 = parseFloat(t * 100).toFixed(0);
			$(this).prev().text(t1+'%');
		}else
		{
			$(this).prev().text("-");
		}
		
	});
});


	function search()
	{	
		var startdate=document.getElementById('startdate').value;
		if (startdate != "")
		  {
			var positionval  = startdate.split('/');
			startdate = positionval[2]+"-"+positionval[0]+"-"+positionval[1];
			
		  }
		else
		{
			var startdate= "";
		}
		//alert(startdate);
		var enddate=document.getElementById('enddate').value;
		if (enddate != "")
		  {
			var positionval1  = enddate.split('/');
			enddate = positionval1[2]+"-"+positionval1[0]+"-"+positionval1[1];
		  }
		else
		{
			enddate= "";
		}
		//alert(enddate);
		window.location="<?php echo BASEPATH; ?>/taskpl/reportnonchargeable/startdate/"+startdate+"/enddate/"+enddate;
	}
	function exportdata()
	{	
		var startdate=document.getElementById('startdate').value;
		if (startdate != "")
		  {
			var positionval  = startdate.split('/');
			startdate = positionval[2]+"-"+positionval[0]+"-"+positionval[1];
			
		  }
		else
		{
			var startdate= "";
		}
		//alert(startdate);
		var enddate=document.getElementById('enddate').value;
		if (enddate != "")
		  {
			var positionval1  = enddate.split('/');
			enddate = positionval1[2]+"-"+positionval1[0]+"-"+positionval1[1];
		  }
		else
		{
			enddate= "";
		}
		//alert(enddate);
		window.location="<?php echo BASEPATH; ?>/taskpl/nonchargeableexport/startdate/"+startdate+"/enddate/"+enddate;
	}
	

</script>


<script>

	
</script>
<style>
.col-first {
    width: 315px;
}
.greenClass
{
	background-repeat:repeat-x;
	background-color:#8EC555;
    height: 32px;
    margin: -8px 0 0;
    padding: 8px 0 0;
    background-image:url("<?php echo BASEPATH ;?>/images/common/menubg-grn.gif");
}
</style>

</head>
<body>
<div id="subheader">
<?php

	  function minutetohr($minute)
	{
		$hr=$minute/60;
		$minute =intval($minute);
		$hr= intval($minute/60);
		$hr=round($minute/60,2);
		$hr1 = explode('.', $hr);
		$min=$minute%60;
		if($min < 10)
		{
			$hrs=$hr1[0].".0".$min;
		}
		else 
		{
			$hrs=$hr1[0].".".$min;
		}
		
		return $hrs;
	}

?>
	<form id="searchprojectform" name="searchprojectform" action="" method="post">
	<div class="wrapper">
	<div id="holder" style="margin:0;">
        	<label>From Date<em>*</em></label>
            <input name="startdate" id="startdate" type="text" class="field calendar" value="<?php if(isset($this->startdate) && $this->startdate!=""){echo $this->startdate; } ?>" id="SelectedDate" readonly onClick="GetDate(this);"/>
            <label>To Date<em>*</em></label>
            <input name="enddate" id="enddate" type="text" class="field calendar" value="<?php if(isset($this->enddate) && $this->enddate!=""){echo $this->enddate; }?>" id="SelectedDate" readonly onClick="GetDate(this);"/>
      </div>
      <br class="clear">
        <br class="clear">
  		<div class="flow_right" style="margin:0 10px 0 0" onclick="exportdata();"><a href="javascript:void(0);" class="searchbg">Export</a></div>
  		<div class="flow_right" style="margin:0 10px 0 0" onclick="search();"><a href="javascript:void(0);" class="searchbg">Submit</a></div>
  		<div class="flow_right" style="margin:0 10px 0 0"><a href="<?php echo BASEPATH?>/taskpl/reportscreenindex" style="margin-right:532px;" class="searchbg">Report-homepage</a></div>
  	</div>
    <br class="clear" />
    </form>
</div>
<div id="contentbg">
	<div class="frame">
    	<br class="clear">
    	<!--Starts Here -->
   	  <div class="wrapper">

        <br class="clear">
        <br class="clear">
        
        <div id="tablebg" style="height:40px;width:80%;">
        	<div class="col-first" style="width:260px;">Activities</div>
            <div class="col" style="width:260px;">Hours</div>
            <div class="col" style="width:108px;">%</div>
        </div>
        
        <?php  if(isset($this->result) && sizeof($this->result)>0){
        	
        	
        		
        	foreach($this->result as $f){
        		
        		
        		$result_explode_editid = array();
        		$result_explode_editid = explode(",", $this->result_task[$f['vname']]['editid']);
        		
        		$sum = 0;
        		for($i=0;$i<sizeof($result_explode_editid);$i++)
        		{
        		$taskObj = new Aranca_Model_DbTable_Task();
					$clientObj= new Aranca_Model_DbTable_Client();
					$emp_taskObj = new Aranca_Model_DbTable_Emptask();
					$editid = $result_explode_editid[$i]; 
					$startdate = $this->startdate1;
					$enddate = $this->enddate1;
					
					if($startdate !="" && $enddate !="")
					{
						$where = " et.task_id = '$editid' &&  '$startdate' <= DATE(et.st_time) && DATE(et.end_time) <= '$enddate' ";
					}
					else 
					{
						$where = "  et.task_id = '$editid' ";
					}
						
					
	
					$listing = $emp_taskObj->fetchAll($emp_taskObj->select()
											->setIntegrityCheck(false)
											->from(array('et'=>DATABASE_PREFIX."emp_task"),array('et.id as editid','et.task_id as task_id','et.st_time as st_time','et.end_time as end_time'))
											->where($where)
										);
					$hours=0;
					$totalhours=0;	
					$totalminits=0;
					$result="0.0";							
					foreach ($listing as $list)
					{	if(isset($list->st_time) && $list->st_time!="" && $list->st_time!="0000-00-00 00:00:00" && isset($list->end_time) && $list->end_time!="" && $list->end_time!="0000-00-00 00:00:00")
					{								
						$date_a = new DateTime($list['st_time']);
						$date_b = new DateTime($list['end_time']);						
						$diff=$date_b->diff($date_a);
						$hours=$diff->h;
						$minits=$diff->i;
						$totalminits+=$minits;
						$totalhours+=$hours+($diff->d*24);	
						$total_min = $totalhours*60;
						$result = $total_min+$totalminits;	
					}				
					} 
					
					$actual_hour =$result;
					$sum =$sum +$actual_hour;
        		}
        		//if(isset($sum) && $sum!="")		
				//$final['sum']=gmdate("H:i",($sum*60));
        		//echo $sum;	
        ?>
        <div id="rowbg"  style="width: 80%;">
        <div class="col-first" style="width:260px;"><a href="#"><?php if(isset($f['vname'])&& $f['vname']!=""){echo $f['vname']; }else{echo "-";}?></a></div>
        
            <div class="col" style="width:260px;"><?php if(isset($sum) && $sum!=""){echo minutetohr($sum);}else{echo "-";} ?></div>
            <div class="col" style="width:108px;"></div>
            <input type="hidden" id="indisum" name="indisum" class="col1"  value="<?php if(isset($sum) && $sum!=""){echo $sum;} ?>"/>
             <input type="hidden" id="total" name="total"   value=""/>
        </div>
        <?php
				}
				 //code for pagination in the phtml file
				echo "<div align='center' style='width:80%;'>".$this->pagination($this->pagination_config)."</div>";
				//echo "<div>&nbsp;</div>";

			}
			else{
		?>
		<div class='grid-row2'>
			<div align='' style="width:95%;font-weight:bold;">No Records Found</div>
		</div>
		<?php } ?>
       
<!--        <div class="pagination"><a href="#" class="active">1</a> <a href="#">2</a> <a href="#">3</a> <a href="#">4</a> <a href="#">Next</a></div>-->
      </div>
        <!--Ends Here -->
    </div>
</div>
</body>
<script>

</script>
</html>