<?php $authUserNamespace = new Zend_Session_Namespace("Aranca_Auth"); ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Aranca: Research.Analyze.Communicate</title>
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/crud.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH;?>/js/jquery-1.4.2.min.js"></script>
<script language="JavaScript" src="<?php echo BASEPATH;?>/shared/htmlDatePicker1.js" type="text/javascript"></script>
<link href="<?php echo BASEPATH;?>/shared/htmlDatePicker.css" rel="stylesheet" />
<script src="<?php echo BASEPATH;?>/js/jquery.alerts.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" media="screen" href="<?php echo BASEPATH;?>/css/jquery.alerts.css" />
<link rel="stylesheet" type="text/css"  href="<?php echo BASEPATH;?>/shared/style.css" />
<!--<script type="text/javascript" src="<?php echo BASEPATH;?>/shared/jquery-1.js"></script>
--><script type="text/javascript" src="<?php echo BASEPATH; ?>/js/jquery.ui.core.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/js/mootools-1.2.4-core-yc.js"></script>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/js/mediaboxAdv-1.2.4.js"></script>
<link media="screen" type="text/css" href="<?php echo BASEPATH ;?>/css/mediaboxAdvWhite.css" rel="stylesheet"/>

<link media="screen" type="text/css" href="<?php echo BASEPATH ;?>/shared/skillboxaranca.css" rel="stylesheet"/>
<script type="text/javascript" src="<?php echo BASEPATH; ?>/shared/skillslideraranca.js"></script>

<script type="text/javascript">

	function search()
	{	
		var startdate=document.getElementById('startdate').value;
		if (startdate != "")
		  {
			var positionval  = startdate.split('/');
			startdate = positionval[2]+"-"+positionval[0]+"-"+positionval[1];
			
		  }
		else
		{
			var startdate= "";
		}
		//alert(startdate);
		var enddate=document.getElementById('enddate').value;
		if (enddate != "")
		  {
			var positionval1  = enddate.split('/');
			enddate = positionval1[2]+"-"+positionval1[0]+"-"+positionval1[1];
		  }
		else
		{
			enddate= "";
		}
		//alert(enddate);
		var teammember=document.getElementById('teammember').value;
		window.location="<?php echo BASEPATH; ?>/taskpl/scoreindex/startdate/"+startdate+"/enddate/"+enddate+"/teammember/"+teammember;
	}
	function exportdata()
	{	
		var startdate=document.getElementById('startdate').value;
		if (startdate != "")
		  {
			var positionval  = startdate.split('/');
			startdate = positionval[2]+"-"+positionval[0]+"-"+positionval[1];
			
		  }
		else
		{
			var startdate= "";
		}
		//alert(startdate);
		var enddate=document.getElementById('enddate').value;
		if (enddate != "")
		  {
			var positionval1  = enddate.split('/');
			enddate = positionval1[2]+"-"+positionval1[0]+"-"+positionval1[1];
		  }
		else
		{
			enddate= "";
		}
		//alert(enddate);
		var teammember=document.getElementById('teammember').value;
		window.location="<?php echo BASEPATH; ?>/taskpl/scoreexport/startdate/"+startdate+"/enddate/"+enddate+"/teammember/"+teammember;
	}
	

</script>


<script>

	
</script>
<style>
.col-first {
    width: 315px;
}
.greenClass
{
	background-repeat:repeat-x;
	background-color:#8EC555;
    height: 32px;
    margin: -8px 0 0;
    padding: 8px 0 0;
    background-image:url("<?php echo BASEPATH ;?>/images/common/menubg-grn.gif");
}
</style>

</head>
<body>
<div id="subheader">
	<form id="searchprojectform" name="searchprojectform" action="" method="post">
	<div class="wrapper">
	<div id="holder" style="margin:0;">
        	<label>From Date<em>*</em></label>
            <input name="startdate" id="startdate" type="text" class="field calendar" value="<?php if(isset($this->startdate) && $this->startdate!=""){echo $this->startdate; } ?>" id="SelectedDate" readonly onClick="GetDate(this);"/>
            <label>To Date<em>*</em></label>
            <input name="enddate" id="enddate" type="text" class="field calendar" value="<?php if(isset($this->enddate) && $this->enddate!=""){echo $this->enddate; }?>" id="SelectedDate" readonly onClick="GetDate(this);"/>
      </div>
      <br class="clear">
        <br class="clear">
       
        	<div id="holder" style="margin:0;float:left; margin-left: -14px;">
        	<label>Team Member<em>*</em></label>
            <select name="teammember" id="teammember" class="field">
              <option value="">Please Select</option>
              <?php	foreach ($this->teammember_list as $teammember_list){?>
			<option value="<?php  if(isset($teammember_list->e_id) && $teammember_list->e_id !=""){ echo $teammember_list->e_id;}?>"<?php if($this->teammember==$teammember_list->e_id) echo "selected";?>><?php echo $teammember_list->teammembername;?></option>
			<?php } ?>
              
            </select>
        </div>
     
  		<div class="flow_right" style="margin:0 10px 0 0" onclick="exportdata();"><a href="javascript:void(0);" class="searchbg">Export</a></div>
  		<div class="flow_right" style="margin:0 10px 0 0" onclick="search();"><a href="javascript:void(0);" class="searchbg">Submit</a></div>
  	</div>
    <br class="clear" />
    </form>
</div>
<div id="contentbg">
	<div class="frame">
    	<br class="clear">
    	<!--Starts Here -->
   	  <div class="wrapper">

        <br class="clear">
        <br class="clear">
        
        <div id="tablebg" style="height:40px;">
        	<div class="col-first" style="width:260px;">Project Name</div>
            <div class="col" style="width:108px;">Project Planning And Execution </div>
            <div class="col" style="width:108px;">Research Quality</div>
            <div class="col" style="width:121px;">Process adherence </div>
            <div class="col" style="width:108px;">Work ethics</div>
           <div class="col greenClass" style="width:108px;">Overall</div>
        </div>
        
        <?php  if(isset($this->final_result) && sizeof($this->final_result)>0){
        		
        	foreach($this->final_result as $final_result){
        			//print_r($final_result[0]['title']);exit;
        			$title=$final_result[0]['title'];
        			$p1="0";
        			$p2="0";
        			$p3="0";
        			$p4="0";
        			
        			
        			if(isset($final_result[0]['score']) && $final_result[0]['score']!="")
        			{	
        				if($final_result[0]['score']=='84'){
        					$p1=1;
        				}else if($final_result[0]['score']=='85'){
        					$p1=2;
        				}else if($final_result[0]['score']=='86'){
        					$p1=3;
        				}else if($final_result[0]['score']=='87'){
        					$p1=4;
        				}
        			}
        			else {
        				$p1="0";
        			}
        			if(isset($final_result[1]['score']) && $final_result[1]['score']!="")
        			{
        				if($final_result[1]['score']=='84'){
        					$p2=1;
        				}else if($final_result[1]['score']=='85'){
        					$p2=2;
        				}else if($final_result[1]['score']=='86'){
        					$p2=3;
        				}else if($final_result[1]['score']=='87'){
        					$p2=4;
        				}
        			}
        			else {
        				$p2="0";
        			}
        			if(isset($final_result[2]['score']) && $final_result[2]['score']!="")
        			{
        				if($final_result[2]['score']=='84'){
        					$p3=1;
        				}else if($final_result[2]['score']=='85'){
        					$p3=2;
        				}else if($final_result[2]['score']=='86'){
        					$p3=3;
        				}else if($final_result[2]['score']=='87'){
        					$p3=4;
        				}
        			}
        			else {
        				$p3="0";
        			}
        			if(isset($final_result[3]['score']) && $final_result[3]['score']!="")
        			{
        				if($final_result[3]['score']=='84'){
        					$p4=1;
        				}else if($final_result[3]['score']=='85'){
        					$p4=2;
        				}else if($final_result[3]['score']=='86'){
        					$p4=3;
        				}else if($final_result[3]['score']=='87'){
        					$p4=4;
        				}
        			}
        			else {
        				$p4="0";
        			}
        			
        			$total=(($p1*30)+($p2*50)+($p3*10)+($p4*10))/100;
        ?>
        <div id="rowbg">
        <div class="col-first" style="width:260px;"><span style="color: #1E599F;font-weight: bold;text-decoration: underline;" ><?php echo $title; ?></span></div>
            <div class="col" style="width:108px;"><?php echo $p1; ?></div>
            <div class="col" style="width:108px;"><?php echo $p2; ?></div>
            <div class="col" style="width:108px;"><?php echo $p3; ?></div>
            <div class="col" style="width:108px;"><?php echo $p4; ?></div>
            <div class="col" style="width:108px;"><?php echo$total; ?></div>
        </div>
        <?php
				}
				 //code for pagination in the phtml file
				echo "<div align='center'>".$this->pagination($this->pagination_config)."</div>";
				//echo "<div>&nbsp;</div>";

			}
			else{
		?>
		<div class='grid-row2'>
			<div align='' style="width:95%;font-weight:bold;">No Records Found</div>
		</div>
		<?php } ?>
       
<!--        <div class="pagination"><a href="#" class="active">1</a> <a href="#">2</a> <a href="#">3</a> <a href="#">4</a> <a href="#">Next</a></div>-->
      </div>
        <!--Ends Here -->
    </div>
</div>
</body>
<script>

</script>
</html>