<?php 
	$misc_obj = new Gbc_Model_Custom_Miscellaneous();
	$authUserNamespace = new Zend_Session_Namespace('Gbc_Auth'); $misc_obj->generateToken();

?>
<style>
#menu, #sample .footer ,  #sample p,.breadcrumb>li+li:before {
  display: none;
}
li a:hover, a li:focus {
  background: transparent;
  color: #364a5e;
}    
</style>   
   <div id="innerpage-wrapper">
      <div class="row lightgraybg">
        <div class="col-lg-12 offset-1">
          <h1 class="page-header gain-bit-Titletxt innpercontentPad">Tabular Form</h1>
        </div>
        <!-- /.col-lg-12 -->
      </div>
      <!-- /.row -->
      <input type="hidden" value="<?php echo $authUserNamespace->token;?>" id="token" name="token">
      <div class="row">
        <ol class="breadcrumb">
          <li><a href="<?php echo BASEPATH; ?>/Dashboard">Dashboard ></a></li>
          <li>MY Network ></li>
          <li class="active">Tabular Form</li>
        </ol>
        <div class="network-info">
          <div class="col-lg-5 left-inline">
            <div class="col-xs-6">
              <div class="input-type-select">
                <select name="search_level" id = "search_level" disabled>
                  <option value="">Search by Level</option>
          
                </select>
              </div>
            </div>
            <div class="col-xs-6">
              <div class="input-type-select">
                <select name="search_user" id = "search_user" disabled>
                  <option>Search by Name</option>
				 <option value = "">Search by Name</option>
                </select>
              </div>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="col-lg-7">
            <div class="col-lg-9">
             &nbsp

            </div>
             <div class="col-lg-3"><input id="refresh_network" type="button" class="btn_" value="REFRESH"></div>
          </div>
          <div class="clearfix"></div>
        </div>
        <div class="summary-container">
          <div class="sum-header">My Summary</div>
          <div class="sum-content">
            <div class="sum-row-head">
              <div class="col-xs-4 head">Left Users</div>
              <div class="col-xs-4">&nbsp</div>
              <div class="col-xs-4 head">Right Users</div>
              <div class="clearfix"></div>
            </div>
            <div class="sum-row">
                <div class="col-xs-4"><?php if(!empty($this->userdata['leftContracts']) && $this->userdata['leftContracts'] !='' ) { echo $this->userdata['leftContracts']; }else{ echo 0; } ?> BTC</div>
                <div class="col-xs-4 info">Total Contracts</div>
                <div class="col-xs-4"><?php if(!empty($this->userdata['rightContracts']) && $this->userdata['rightContracts'] !='' ) { echo $this->userdata['rightContracts']; }else{ echo 0; } ?> BTC</div>
                <div class="clearfix"></div>
             </div>
               <div class="sum-row">
                <div class="col-xs-4"><?php if(!empty($this->userdata['totalLeftUsers']) && $this->userdata['totalLeftUsers'] != '') { echo $this->userdata['totalLeftUsers']; }else{ echo 0; } ?></div>
                <div class="col-xs-4 info">Total Users</div>
                <div class="col-xs-4"><?php if(!empty($this->userdata['totalRightUsers']) && $this->userdata['totalRightUsers'] !='' ) { echo $this->userdata['totalRightUsers']; }else{ echo 0; } ?></div>
                <div class="clearfix"></div>
              </div>
             <div class="sum-row">
                <div class="col-xs-4"><?php if(!empty($this->userdata['activeLeftUsers']) && $this->userdata['activeLeftUsers'] !='' ) { echo $this->userdata['activeLeftUsers']; }else{ echo 0; } ?></div>
                <div class="col-xs-4 info">Active Users</div>
                <div class="col-xs-4"><?php if(!empty($this->userdata['activeRightUsers']) && $this->userdata['activeRightUsers'] !='' ) { echo $this->userdata['activeRightUsers']; }else{ echo 0; } ?></div>
                <div class="clearfix"></div>
              </div>
            <div class="sum-row">
                <div class="col-xs-4"><?php if(!empty($this->userdata['inactiveLeftUsers']) && $this->userdata['inactiveLeftUsers'] !='' ) { echo $this->userdata['inactiveLeftUsers']; }else{ echo 0; } ?></div>
                <div class="col-xs-4 info">Inactive Users</div>
                <div class="col-xs-4"><?php if(!empty($this->userdata['inactiveRightUsers']) && $this->userdata['inactiveRightUsers'] !='' ) { echo $this->userdata['inactiveRightUsers']; }else{ echo 0; } ?></div>
                <div class="clearfix"></div>
              </div>
          </div>
        </div>
        <div class="user-info">
          <div class="col-lg-6 user-content">
            <div class="summary-container">
              <div class="sum-header">Left Users</div>
             <div class="sum-content">
              
       <div class="bs-example table-responsive" data-example-id="bordered-table">
           <table id="data-table-simple-1"  class="table table-bordered innertbl display" cellspacing="0">
       <thead>
       <tr>
				<?php if(!empty($this->binarydata) && sizeof($this->binarydata)>0) { 
				?>
				  
                  <th class="sortdesc">Username</th>
                  <th class="sortdesc">Sponsor ID</th>
                  <th class="sortdesc">Contracts</th>
                  <th class="sortdesc">Activated on</th>
                
                </tr>
              </thead>
              <tbody>
             
				<?php
				foreach ($this->binarydata as $leftdata)
				{
				
				?>
               
			  	<tr>
                  <td><?php echo $leftdata['name']; ?></td>
                  <td><?php echo $leftdata['ref_sponsor_id']; ?></td>
                  <td><?php echo $leftdata['ContractPrice']; ?></td>
                  <td><?php echo $leftdata['created_on']; ?></td>
                 </tr>
              
      
				<?php
					
					}
				}
				?>
				
				</tbody>
	</table>
	<ul class="pagination">
		 <?php 
		 if(!empty($_GET['page']) && $_GET['page']!='')
		 {
			 $StartPage=$_GET['page'];
		 }
		 else
		 {
			 $StartPage=1; 
		 }
		
	
		 if($this->pages <= 5){
			  $StartPage = 1;
		 }else if(!empty($_GET['page']) && $_GET['page'] < $this->pages-6){
			 // $pageDiff = $pages - $_GET['page'];
			// $StartPage = $pages - $pageDiff;
			 $StartPage = $_GET['page'];
		 }else if(!empty($_GET['page']) && $_GET['page'] >= $this->pages-6){
			 $StartPage = $this->pages - 5;
		 }
			
		 if($this->pages > 5){
			 $limitPage = $StartPage + 4;
		 }else{
			 $limitPage = $this->pages;
		 }
		 
			
		 if(!empty($_GET['page']) && $_GET['page'] > 1){
		 
		 ?>
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Binraynetwrk?page=1"></a></li>
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Binraynetwrk?page=<?php echo $_GET['page']-1; ?>"><i class="mdi-navigation-chevron-left"></i></a></li>
			 <?php 
				}
			 ?>
			
			<?php 
			
			for($j=$StartPage;$j<=$limitPage;$j++){
                    ?>
			<li class="active"><a href="<?php echo BASEPATH;?>/Binraynetwrk?page=<?php echo $j; ?>"><?php echo $j; ?></a></li>
			<?php }
			
			 if( $_GET['page'] < $this->pages-1){
				 
                    ?>
			
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Binraynetwrk?page=<?php echo $_GET['page']+1; ?>"><i class="mdi-navigation-chevron-right"></i></a></li>
			<li class="waves-effect"><a href="<?php echo BASEPATH;?>/Binraynetwrk?page=<?php echo $this->pages-1; ?>"></a></li>
			<?php }
			
                    ?>
		 </ul>
	</div>
              </div>
            </div>
          </div>
          <div class="col-lg-6 user-content">
            <div class="summary-container">
              <div class="sum-header">Right Users</div>
              <div class="sum-content">
             <div class="bs-example table-responsive" data-example-id="bordered-table">
           <table id="data-table-simple-2"  class="table table-bordered innertbl display" cellspacing="0">
       <thead>
       <tr>
              	<?php if(!empty($this->binarydata) && sizeof($this->binarydata)>0) { 
				?>
				  
                  <th class="sortboth">Username</th>
                  <th class="sortboth">Sponsor ID</th>
                  <th class="sortboth">Contracts</th>
                  <th class="sortboth">Activated on</th>
                  
               
               </tr>
              </thead>
              <tbody>
				<?php
				foreach ($this->binarydata as $rightdata)
				{
				if($rightdata['child_position']=='R' && $rightdata['name']!='amol12dxscdsds3fsdfsdf' && $rightdata['name']!='amol12dxsxghcdsds3fsdfsdf')
				{
				if($rightdata['name']!='N/A')
				{
				?>
               <tr>
                  <td><?php echo $rightdata['name']; ?></td>
                  <td><?php echo $rightdata['ref_sponsor_id']; ?></td>
                  <td><?php echo $rightdata['ContractPrice']; ?></td>
                  <td><?php echo $rightdata['created_on']; ?></td>
                  </tr>
                
      
				<?php
						}}
					}
				}
				?>
	</tbody>
	</table>
	</div>
   
              </div>
            </div>
          </div>
          <div class="clearfix"></div>
        </div>

      </div>
    </div>
	  <input type="hidden" id="binarydatarr" value='<?php  echo json_encode( $this->binarydata); ?>'>
		<input type = "hidden" id = "history_counter" />
		<input type = "hidden" id = "master" value="<?php echo $this->username; ?>"/>
		<input type = "hidden" id = "child_user" value="<?php if (!empty($this->binarydata[0]['name'])) { ?> <?php echo $this->binarydata[0]['name']; } else { echo ""; }?>"/>
		<input type = "hidden" id = "parent_user" value="<?php if (!empty($this->binarydata[0]['name'])) { ?> <?php echo $this->binarydata[0]['name']; } else { echo ""; }?>" />
<script type="text/javascript">
 $("#refresh_network").click(function(){
			var user = $("#child_user").val();
			var master = $("#master").val();
			networkDetails(master,master,1,1);
		});
		
	//networkDetails(userName,1);
	
function networkDetails(userName,master,popup,status){
	if(!popup){
		$("#Popup").show();
	}
	$("#child_user").val(userName);
	$("#parent_user").val(userName);
	var statusParam  = '';
	if(status){
		statusParam  = '&status='+status;
	}
	if(userName){
		$.ajax({
			type:"GET",
			 url: '<?php echo BASEPATH; ?>/Networktab?usr='+userName+'&master='+master,
			success: function(networkDetails){  
			if(!networkDetails || networkDetails==null || networkDetails=='')
			{
				alert("User not exists!!");
			}
			//alert(networkDetails);
				/*if(networkDetails == -1){
					$("#error").html("user not exist");
				}else{
					$("#network").html(networkDetails);
				}*/
			else
			{
				document.open();
				document.write(networkDetails);
				document.close();
				search_by_level(userName);
			}
				
			}
		});
	}
}
var userName = $('#parent_user').val();
search_by_level(userName);
function search_by_level(userName){
	if(userName){
		$.ajax({
			type:"POST",
			 url: '<?php echo BASEPATH; ?>/Binarynetwork/searchbyuser',
			 data : 'usr='+userName+'&search_by_level=1',
			success: function(networkDetails){  
				$("#search_level").removeAttr('disabled');
				$("#search_level").html(networkDetails);
			}
		});
	}
}

$("#search_level").change(function(){
	// alert($(this).val());
	var level = $(this).val();
	if(level){
		searchUser_by_level(userName,level);
	}
	
});

function searchUser_by_level(userName,level){
	//$("#search_by_level").append('<div id = "ajax-loader2" style = " float: left;"><img src = "<?php echo BASEPATH; ?>/images/ajax-loader.gif" style ="width: 70px;" /></div>');

	if(userName){
		$.ajax({
			type:"POST",
			 url: '<?php echo BASEPATH; ?>/Binarynetwork/searchbyuser',
			 data : 'usr='+userName+'&level='+level+'&search_by_user=1',
			success: function(networkDetails){ 
				// alert(networkDetails);
			//	$("#ajax-loader2").remove();
				$("#search_user").removeAttr('disabled');
				$("#search_user").html(networkDetails);
			}
		});
	}
}

$("#search_user").change(function(){
	// alert($(this).val());
	var UserName = $(this).val();
	var master=$('#master').val();
	if(UserName){
		networkDetails(UserName,master);
	}
});

$("#search_network").click(function(){
	var user = $("#searchUser").val();
	var master=$('#master').val();
	if(user == ''){
		return false;
	}else{
		$("#error").html("");
		networkDetails(user,master);
	}
});
</script>   
<script>
$(window).load(function() {
	
	var oTable1 = $('#data-table-simple-1').dataTable();
	//responsive: true,
	responsive: true;	
	$('.top').hide();
	$('.col-sm-6').hide();
	
	
});
$(window).load(function() {
	//responsive: true;
	var oTable1 = $('#data-table-simple-2').dataTable();	
	$('.top').hide();
	$('.col-sm-6').hide();
	$('.col-sm-5').remove();
	$('.col-sm-7').css("width","100%");
	
});
</script>